# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime
from typing import Any, Literal, TypeAlias

from pydantic import TypeAdapter

import memos_unofficial_sdk.types as _response_types
from memos_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    encode_path_segment,
    omit_unset,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from memos_unofficial_sdk.types import (
    Attachment,
    ListMemoAttachmentsResponse,
    Location,
    Memo,
    Memo_Property,
    MemoRelation,
    Reaction,
    Status,
)
from memos_unofficial_sdk.validation import validate_date_time
from memos_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


MemoServiceGetMemoError: TypeAlias = Status


async def memo_service_get_memo(
    _client_config: ClientConfig,
    memo: str,
    *,
    request_options: RequestOptions | None = None,
) -> Memo:
    """Retrieves a memo by its identifier. Use the `memo` path parameter to specify which
    memo to retrieve.

    GetMemo gets a memo.

    Args:
        memo: The memo id.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v1/memos/{encode_path_segment(memo)}",
        operation_id="memo_service_get_memo",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_validate_response_enums(_resp.data, "Memo"), Memo)


def memo_service_get_memo_sync(
    _client_config: ClientConfig,
    memo: str,
    *,
    request_options: RequestOptions | None = None,
) -> Memo:
    """Retrieves a memo by its identifier. Use the `memo` path parameter to specify which
    memo to retrieve.

    GetMemo gets a memo.

    Args:
        memo: The memo id.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v1/memos/{encode_path_segment(memo)}",
        operation_id="memo_service_get_memo",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_validate_response_enums(_resp.data, "Memo"), Memo)


MemoServiceDeleteMemoError: TypeAlias = Status


async def memo_service_delete_memo(
    _client_config: ClientConfig,
    memo: str,
    force: bool | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Deletes the named memo and its owned resources without deleting other memos. Use
    `force` to delete the memo even when it has associated data; incident relations are
    removed.

    DeleteMemo deletes only the named memo and its owned resources. It removes incident
    relations but never deletes another memo.

    Args:
        memo: The memo id.
        force: Optional. If set to true, the memo will be deleted even if it has associated
            data.
    """

    _resp = await sdk_request(
        "DELETE",
        f"/api/v1/memos/{encode_path_segment(memo)}",
        params=serialize_query([("force", force, "form", True)]),
        operation_id="memo_service_delete_memo",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


def memo_service_delete_memo_sync(
    _client_config: ClientConfig,
    memo: str,
    force: bool | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Deletes the named memo and its owned resources without deleting other memos. Use
    `force` to delete the memo even when it has associated data; incident relations are
    removed.

    DeleteMemo deletes only the named memo and its owned resources. It removes incident
    relations but never deletes another memo.

    Args:
        memo: The memo id.
        force: Optional. If set to true, the memo will be deleted even if it has associated
            data.
    """

    _resp = sdk_request_sync(
        "DELETE",
        f"/api/v1/memos/{encode_path_segment(memo)}",
        params=serialize_query([("force", force, "form", True)]),
        operation_id="memo_service_delete_memo",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


MemoServiceUpdateMemoError: TypeAlias = Status


async def memo_service_update_memo(
    _client_config: ClientConfig,
    memo: str,
    state: Literal["STATE_UNSPECIFIED", "NORMAL", "ARCHIVED"] | str,
    content: str,
    visibility: Literal["VISIBILITY_UNSPECIFIED", "PRIVATE", "PROTECTED", "PUBLIC", "SPACE"] | str,
    update_mask: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    creator: str | NotGiven = NOT_GIVEN,
    create_time: datetime.datetime | NotGiven = NOT_GIVEN,
    update_time: datetime.datetime | NotGiven = NOT_GIVEN,
    tags: list[str] | NotGiven = NOT_GIVEN,
    pinned: bool | NotGiven = NOT_GIVEN,
    attachments: list[Attachment] | NotGiven = NOT_GIVEN,
    relations: list[MemoRelation] | NotGiven = NOT_GIVEN,
    reactions: list[Reaction] | NotGiven = NOT_GIVEN,
    property: Memo_Property | NotGiven = NOT_GIVEN,
    parent: str | NotGiven = NOT_GIVEN,
    snippet: str | NotGiven = NOT_GIVEN,
    location: Location | NotGiven = NOT_GIVEN,
    space: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Memo:
    """Updates a memo with the fields supplied in the request body. Use `updateMask` to
    identify the fields to update; `state`, `content`, and `visibility` are required by
    the request schema.

    UpdateMemo updates a memo.

    Args:
        memo: The memo id.
        state: The state of the memo.
        content: Required. The content of the memo in Markdown format.
        visibility: The visibility of the memo. One of PRIVATE (creator only), PROTECTED (signed-in
            users), PUBLIC (anonymous-eligible), or SPACE (active space members). Defaults
            to PRIVATE on creation when unspecified.
        update_mask: Required. The list of fields to update.
        name: The resource name of the memo. Format: memos/{memo}, where memo is the
            user-defined UID.
        creator: The name of the creator. Format: users/{user}
        create_time: The creation timestamp. If not set on creation, the server will set it to the
            current time.
        update_time: The last update timestamp. If not set on creation, the server will set it to the
            current time.
        tags: Output only. The tags extracted from the content.
        pinned: Whether the memo is pinned.
        attachments: Optional. The attachments of the memo.
        relations: Optional. The relations of the memo.
        reactions: Output only. The reactions to the memo.
        property: Output only. The computed properties of the memo.
        parent: Output only. The context memo of this COMMENT relation, if any. Its identity is
            returned even when the caller cannot read the parent. Fetch the parent
            independently; this field does not grant read access. Format: memos/{memo}
        snippet: Output only. The snippet of the memo content. Plain text only.
        location: Optional. The location of the memo.
        space: Optional. The space in which this memo is placed. Format: spaces/{space}. Every
            memo, including a comment, owns its placement independently.
    """

    if not isinstance(create_time, NotGiven) and create_time is not None:
        validate_date_time("createTime", create_time)

    if not isinstance(update_time, NotGiven) and update_time is not None:
        validate_date_time("updateTime", update_time)

    _resp = await sdk_request(
        "PATCH",
        f"/api/v1/memos/{encode_path_segment(memo)}",
        params=serialize_query([("updateMask", update_mask, "form", True)]),
        json=omit_unset(
            {
                "state": (
                    NOT_GIVEN
                    if state is NOT_GIVEN
                    else to_wire(state, 'Literal["STATE_UNSPECIFIED", "NORMAL", "ARCHIVED"] | str')
                ),
                "content": (NOT_GIVEN if content is NOT_GIVEN else to_wire(content, "str")),
                "visibility": (
                    NOT_GIVEN
                    if visibility is NOT_GIVEN
                    else to_wire(
                        visibility,
                        'Literal["VISIBILITY_UNSPECIFIED", "PRIVATE", "PROTECTED", "PUBLIC", "SPACE"] | str',
                    )
                ),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "creator": (NOT_GIVEN if creator is NOT_GIVEN else to_wire(creator, "str")),
                "createTime": (
                    NOT_GIVEN
                    if create_time is NOT_GIVEN
                    else to_wire(create_time, "datetime.datetime")
                ),
                "updateTime": (
                    NOT_GIVEN
                    if update_time is NOT_GIVEN
                    else to_wire(update_time, "datetime.datetime")
                ),
                "tags": (NOT_GIVEN if tags is NOT_GIVEN else to_wire(tags, "list[str]")),
                "pinned": (NOT_GIVEN if pinned is NOT_GIVEN else to_wire(pinned, "bool")),
                "attachments": (
                    NOT_GIVEN if attachments is NOT_GIVEN else to_wire(attachments, "Attachment")
                ),
                "relations": (
                    NOT_GIVEN if relations is NOT_GIVEN else to_wire(relations, "MemoRelation")
                ),
                "reactions": (
                    NOT_GIVEN if reactions is NOT_GIVEN else to_wire(reactions, "Reaction")
                ),
                "property": (
                    NOT_GIVEN if property is NOT_GIVEN else to_wire(property, "Memo_Property")
                ),
                "parent": (NOT_GIVEN if parent is NOT_GIVEN else to_wire(parent, "str")),
                "snippet": (NOT_GIVEN if snippet is NOT_GIVEN else to_wire(snippet, "str")),
                "location": (NOT_GIVEN if location is NOT_GIVEN else to_wire(location, "Location")),
                "space": (NOT_GIVEN if space is NOT_GIVEN else to_wire(space, "str")),
            }
        ),
        operation_id="memo_service_update_memo",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_validate_response_enums(_resp.data, "Memo"), Memo)


def memo_service_update_memo_sync(
    _client_config: ClientConfig,
    memo: str,
    state: Literal["STATE_UNSPECIFIED", "NORMAL", "ARCHIVED"] | str,
    content: str,
    visibility: Literal["VISIBILITY_UNSPECIFIED", "PRIVATE", "PROTECTED", "PUBLIC", "SPACE"] | str,
    update_mask: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    creator: str | NotGiven = NOT_GIVEN,
    create_time: datetime.datetime | NotGiven = NOT_GIVEN,
    update_time: datetime.datetime | NotGiven = NOT_GIVEN,
    tags: list[str] | NotGiven = NOT_GIVEN,
    pinned: bool | NotGiven = NOT_GIVEN,
    attachments: list[Attachment] | NotGiven = NOT_GIVEN,
    relations: list[MemoRelation] | NotGiven = NOT_GIVEN,
    reactions: list[Reaction] | NotGiven = NOT_GIVEN,
    property: Memo_Property | NotGiven = NOT_GIVEN,
    parent: str | NotGiven = NOT_GIVEN,
    snippet: str | NotGiven = NOT_GIVEN,
    location: Location | NotGiven = NOT_GIVEN,
    space: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Memo:
    """Updates a memo with the fields supplied in the request body. Use `updateMask` to
    identify the fields to update; `state`, `content`, and `visibility` are required by
    the request schema.

    UpdateMemo updates a memo.

    Args:
        memo: The memo id.
        state: The state of the memo.
        content: Required. The content of the memo in Markdown format.
        visibility: The visibility of the memo. One of PRIVATE (creator only), PROTECTED (signed-in
            users), PUBLIC (anonymous-eligible), or SPACE (active space members). Defaults
            to PRIVATE on creation when unspecified.
        update_mask: Required. The list of fields to update.
        name: The resource name of the memo. Format: memos/{memo}, where memo is the
            user-defined UID.
        creator: The name of the creator. Format: users/{user}
        create_time: The creation timestamp. If not set on creation, the server will set it to the
            current time.
        update_time: The last update timestamp. If not set on creation, the server will set it to the
            current time.
        tags: Output only. The tags extracted from the content.
        pinned: Whether the memo is pinned.
        attachments: Optional. The attachments of the memo.
        relations: Optional. The relations of the memo.
        reactions: Output only. The reactions to the memo.
        property: Output only. The computed properties of the memo.
        parent: Output only. The context memo of this COMMENT relation, if any. Its identity is
            returned even when the caller cannot read the parent. Fetch the parent
            independently; this field does not grant read access. Format: memos/{memo}
        snippet: Output only. The snippet of the memo content. Plain text only.
        location: Optional. The location of the memo.
        space: Optional. The space in which this memo is placed. Format: spaces/{space}. Every
            memo, including a comment, owns its placement independently.
    """

    if not isinstance(create_time, NotGiven) and create_time is not None:
        validate_date_time("createTime", create_time)

    if not isinstance(update_time, NotGiven) and update_time is not None:
        validate_date_time("updateTime", update_time)

    _resp = sdk_request_sync(
        "PATCH",
        f"/api/v1/memos/{encode_path_segment(memo)}",
        params=serialize_query([("updateMask", update_mask, "form", True)]),
        json=omit_unset(
            {
                "state": (
                    NOT_GIVEN
                    if state is NOT_GIVEN
                    else to_wire(state, 'Literal["STATE_UNSPECIFIED", "NORMAL", "ARCHIVED"] | str')
                ),
                "content": (NOT_GIVEN if content is NOT_GIVEN else to_wire(content, "str")),
                "visibility": (
                    NOT_GIVEN
                    if visibility is NOT_GIVEN
                    else to_wire(
                        visibility,
                        'Literal["VISIBILITY_UNSPECIFIED", "PRIVATE", "PROTECTED", "PUBLIC", "SPACE"] | str',
                    )
                ),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "creator": (NOT_GIVEN if creator is NOT_GIVEN else to_wire(creator, "str")),
                "createTime": (
                    NOT_GIVEN
                    if create_time is NOT_GIVEN
                    else to_wire(create_time, "datetime.datetime")
                ),
                "updateTime": (
                    NOT_GIVEN
                    if update_time is NOT_GIVEN
                    else to_wire(update_time, "datetime.datetime")
                ),
                "tags": (NOT_GIVEN if tags is NOT_GIVEN else to_wire(tags, "list[str]")),
                "pinned": (NOT_GIVEN if pinned is NOT_GIVEN else to_wire(pinned, "bool")),
                "attachments": (
                    NOT_GIVEN if attachments is NOT_GIVEN else to_wire(attachments, "Attachment")
                ),
                "relations": (
                    NOT_GIVEN if relations is NOT_GIVEN else to_wire(relations, "MemoRelation")
                ),
                "reactions": (
                    NOT_GIVEN if reactions is NOT_GIVEN else to_wire(reactions, "Reaction")
                ),
                "property": (
                    NOT_GIVEN if property is NOT_GIVEN else to_wire(property, "Memo_Property")
                ),
                "parent": (NOT_GIVEN if parent is NOT_GIVEN else to_wire(parent, "str")),
                "snippet": (NOT_GIVEN if snippet is NOT_GIVEN else to_wire(snippet, "str")),
                "location": (NOT_GIVEN if location is NOT_GIVEN else to_wire(location, "Location")),
                "space": (NOT_GIVEN if space is NOT_GIVEN else to_wire(space, "str")),
            }
        ),
        operation_id="memo_service_update_memo",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_validate_response_enums(_resp.data, "Memo"), Memo)


MemoServiceListMemoAttachmentsError: TypeAlias = Status


async def memo_service_list_memo_attachments(
    _client_config: ClientConfig,
    memo: str,
    page_size: int | NotGiven = NOT_GIVEN,
    page_token: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ListMemoAttachmentsResponse:
    """Lists attachments associated with a specific memo. Use `pageSize` to limit the
    number of results and `pageToken` to continue through the results.

    ListMemoAttachments lists attachments for a memo.

    Args:
        memo: The memo id.
        page_size: Optional. The maximum number of attachments to return.
        page_token: Optional. A page token for pagination.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v1/memos/{encode_path_segment(memo)}/attachments",
        params=serialize_query(
            [("pageSize", page_size, "form", True), ("pageToken", page_token, "form", True)]
        ),
        operation_id="memo_service_list_memo_attachments",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListMemoAttachmentsResponse"),
        ListMemoAttachmentsResponse,
    )


def memo_service_list_memo_attachments_sync(
    _client_config: ClientConfig,
    memo: str,
    page_size: int | NotGiven = NOT_GIVEN,
    page_token: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ListMemoAttachmentsResponse:
    """Lists attachments associated with a specific memo. Use `pageSize` to limit the
    number of results and `pageToken` to continue through the results.

    ListMemoAttachments lists attachments for a memo.

    Args:
        memo: The memo id.
        page_size: Optional. The maximum number of attachments to return.
        page_token: Optional. A page token for pagination.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v1/memos/{encode_path_segment(memo)}/attachments",
        params=serialize_query(
            [("pageSize", page_size, "form", True), ("pageToken", page_token, "form", True)]
        ),
        operation_id="memo_service_list_memo_attachments",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListMemoAttachmentsResponse"),
        ListMemoAttachmentsResponse,
    )


MemoServiceSetMemoAttachmentsError: TypeAlias = Status


async def memo_service_set_memo_attachments(
    _client_config: ClientConfig,
    memo: str,
    name: str,
    attachments: list[Attachment],
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Replaces the full set of attachments associated with a memo. Pass the complete
    desired list in `attachments`; an empty list clears the memo's attachments, and
    repeating the same request is idempotent.

    SetMemoAttachments replaces the full set of attachments on a memo with the provided
    list (not an append). Pass the complete desired set; an empty list clears all
    attachments. Idempotent.

    Args:
        memo: The memo id.
        name: Required. The resource name of the memo. Format: memos/{memo}
        attachments: Required. The attachments to set for the memo.
    """

    _resp = await sdk_request(
        "PATCH",
        f"/api/v1/memos/{encode_path_segment(memo)}/attachments",
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "attachments": (
                    NOT_GIVEN if attachments is NOT_GIVEN else to_wire(attachments, "Attachment")
                ),
            }
        ),
        operation_id="memo_service_set_memo_attachments",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


def memo_service_set_memo_attachments_sync(
    _client_config: ClientConfig,
    memo: str,
    name: str,
    attachments: list[Attachment],
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Replaces the full set of attachments associated with a memo. Pass the complete
    desired list in `attachments`; an empty list clears the memo's attachments, and
    repeating the same request is idempotent.

    SetMemoAttachments replaces the full set of attachments on a memo with the provided
    list (not an append). Pass the complete desired set; an empty list clears all
    attachments. Idempotent.

    Args:
        memo: The memo id.
        name: Required. The resource name of the memo. Format: memos/{memo}
        attachments: Required. The attachments to set for the memo.
    """

    _resp = sdk_request_sync(
        "PATCH",
        f"/api/v1/memos/{encode_path_segment(memo)}/attachments",
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "attachments": (
                    NOT_GIVEN if attachments is NOT_GIVEN else to_wire(attachments, "Attachment")
                ),
            }
        ),
        operation_id="memo_service_set_memo_attachments",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


__all__ = [
    "MemoServiceDeleteMemoError",
    "MemoServiceGetMemoError",
    "MemoServiceListMemoAttachmentsError",
    "MemoServiceSetMemoAttachmentsError",
    "MemoServiceUpdateMemoError",
    "memo_service_delete_memo",
    "memo_service_delete_memo_sync",
    "memo_service_get_memo",
    "memo_service_get_memo_sync",
    "memo_service_list_memo_attachments",
    "memo_service_list_memo_attachments_sync",
    "memo_service_set_memo_attachments",
    "memo_service_set_memo_attachments_sync",
    "memo_service_update_memo",
    "memo_service_update_memo_sync",
]
