# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime
from typing import Any, TypeAlias

from pydantic import TypeAdapter

import memos_unofficial_sdk.types as _response_types
from memos_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    encode_path_segment,
    omit_unset,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from memos_unofficial_sdk.types import (
    ListMemoRelationsResponse,
    ListMemoSharesResponse,
    Memo,
    MemoRelation,
    MemoShare,
    Status,
)
from memos_unofficial_sdk.validation import validate_date_time
from memos_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


MemoServiceListMemoRelationsError: TypeAlias = Status


async def memo_service_list_memo_relations(
    _client_config: ClientConfig,
    memo: str,
    page_size: int | NotGiven = NOT_GIVEN,
    page_token: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ListMemoRelationsResponse:
    """Lists relations associated with a specific memo. Use `pageSize` to limit the number
    of results and `pageToken` to retrieve subsequent pages.

    ListMemoRelations lists relations for a memo.

    Args:
        memo: The memo id.
        page_size: Optional. The maximum number of relations to return.
        page_token: Optional. A page token for pagination.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v1/memos/{encode_path_segment(memo)}/relations",
        params=serialize_query(
            [("pageSize", page_size, "form", True), ("pageToken", page_token, "form", True)]
        ),
        operation_id="memo_service_list_memo_relations",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListMemoRelationsResponse"), ListMemoRelationsResponse
    )


def memo_service_list_memo_relations_sync(
    _client_config: ClientConfig,
    memo: str,
    page_size: int | NotGiven = NOT_GIVEN,
    page_token: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ListMemoRelationsResponse:
    """Lists relations associated with a specific memo. Use `pageSize` to limit the number
    of results and `pageToken` to retrieve subsequent pages.

    ListMemoRelations lists relations for a memo.

    Args:
        memo: The memo id.
        page_size: Optional. The maximum number of relations to return.
        page_token: Optional. A page token for pagination.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v1/memos/{encode_path_segment(memo)}/relations",
        params=serialize_query(
            [("pageSize", page_size, "form", True), ("pageToken", page_token, "form", True)]
        ),
        operation_id="memo_service_list_memo_relations",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListMemoRelationsResponse"), ListMemoRelationsResponse
    )


MemoServiceSetMemoRelationsError: TypeAlias = Status


async def memo_service_set_memo_relations(
    _client_config: ClientConfig,
    memo: str,
    name: str,
    relations: list[MemoRelation],
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Replaces the full set of mutable REFERENCE relations on a memo. Pass the complete
    desired list in `relations`; an empty list clears REFERENCE relations, while COMMENT
    relations remain unchanged and cannot be set through this operation.

    SetMemoRelations replaces the full set of mutable REFERENCE relations on a memo.
    COMMENT relations are immutable creation context and are rejected by this RPC. An
    empty list clears references without changing COMMENT.

    Args:
        memo: The memo id.
        name: Required. The resource name of the memo. Format: memos/{memo}
        relations: Required. The REFERENCE relations to set for the memo. COMMENT is invalid.
    """

    _resp = await sdk_request(
        "PATCH",
        f"/api/v1/memos/{encode_path_segment(memo)}/relations",
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "relations": (
                    NOT_GIVEN if relations is NOT_GIVEN else to_wire(relations, "MemoRelation")
                ),
            }
        ),
        operation_id="memo_service_set_memo_relations",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


def memo_service_set_memo_relations_sync(
    _client_config: ClientConfig,
    memo: str,
    name: str,
    relations: list[MemoRelation],
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Replaces the full set of mutable REFERENCE relations on a memo. Pass the complete
    desired list in `relations`; an empty list clears REFERENCE relations, while COMMENT
    relations remain unchanged and cannot be set through this operation.

    SetMemoRelations replaces the full set of mutable REFERENCE relations on a memo.
    COMMENT relations are immutable creation context and are rejected by this RPC. An
    empty list clears references without changing COMMENT.

    Args:
        memo: The memo id.
        name: Required. The resource name of the memo. Format: memos/{memo}
        relations: Required. The REFERENCE relations to set for the memo. COMMENT is invalid.
    """

    _resp = sdk_request_sync(
        "PATCH",
        f"/api/v1/memos/{encode_path_segment(memo)}/relations",
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "relations": (
                    NOT_GIVEN if relations is NOT_GIVEN else to_wire(relations, "MemoRelation")
                ),
            }
        ),
        operation_id="memo_service_set_memo_relations",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


MemoServiceListMemoSharesError: TypeAlias = Status


async def memo_service_list_memo_shares(
    _client_config: ClientConfig,
    memo: str,
    *,
    request_options: RequestOptions | None = None,
) -> ListMemoSharesResponse:
    """Lists share links that grant read-only access to a memo through opaque bearer
    tokens. The authenticated user must be the memo creator or an instance
    administrator.

    ListMemoShares lists all share links for a memo. Requires the memo creator or an
    instance administrator.

    Args:
        memo: The memo id.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v1/memos/{encode_path_segment(memo)}/shares",
        operation_id="memo_service_list_memo_shares",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListMemoSharesResponse"), ListMemoSharesResponse
    )


def memo_service_list_memo_shares_sync(
    _client_config: ClientConfig,
    memo: str,
    *,
    request_options: RequestOptions | None = None,
) -> ListMemoSharesResponse:
    """Lists share links that grant read-only access to a memo through opaque bearer
    tokens. The authenticated user must be the memo creator or an instance
    administrator.

    ListMemoShares lists all share links for a memo. Requires the memo creator or an
    instance administrator.

    Args:
        memo: The memo id.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v1/memos/{encode_path_segment(memo)}/shares",
        operation_id="memo_service_list_memo_shares",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListMemoSharesResponse"), ListMemoSharesResponse
    )


MemoServiceCreateMemoShareError: TypeAlias = Status


async def memo_service_create_memo_share(
    _client_config: ClientConfig,
    memo: str,
    name: str | NotGiven = NOT_GIVEN,
    create_time: datetime.datetime | NotGiven = NOT_GIVEN,
    expire_time: datetime.datetime | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> MemoShare:
    """Creates a share link that grants read-only access to a memo through an opaque bearer
    token. The authenticated user must be the memo creator or an instance administrator;
    set `expireTime` to limit how long the link works.

    CreateMemoShare creates a share link for a memo. Requires the memo creator or an
    instance administrator.

    Args:
        memo: The memo id.
        name: The resource name of the share. Format: memos/{memo}/shares/{share} The {share}
            segment is the opaque token used in the share URL.
        create_time: Output only. When this share link was created.
        expire_time: Optional. When set, the share link stops working after this time. If unset, the
            link never expires.
    """

    if not isinstance(create_time, NotGiven) and create_time is not None:
        validate_date_time("createTime", create_time)

    if not isinstance(expire_time, NotGiven) and expire_time is not None:
        validate_date_time("expireTime", expire_time)

    _resp = await sdk_request(
        "POST",
        f"/api/v1/memos/{encode_path_segment(memo)}/shares",
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "createTime": (
                    NOT_GIVEN
                    if create_time is NOT_GIVEN
                    else to_wire(create_time, "datetime.datetime")
                ),
                "expireTime": (
                    NOT_GIVEN
                    if expire_time is NOT_GIVEN
                    else to_wire(expire_time, "datetime.datetime")
                ),
            }
        ),
        operation_id="memo_service_create_memo_share",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_validate_response_enums(_resp.data, "MemoShare"), MemoShare)


def memo_service_create_memo_share_sync(
    _client_config: ClientConfig,
    memo: str,
    name: str | NotGiven = NOT_GIVEN,
    create_time: datetime.datetime | NotGiven = NOT_GIVEN,
    expire_time: datetime.datetime | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> MemoShare:
    """Creates a share link that grants read-only access to a memo through an opaque bearer
    token. The authenticated user must be the memo creator or an instance administrator;
    set `expireTime` to limit how long the link works.

    CreateMemoShare creates a share link for a memo. Requires the memo creator or an
    instance administrator.

    Args:
        memo: The memo id.
        name: The resource name of the share. Format: memos/{memo}/shares/{share} The {share}
            segment is the opaque token used in the share URL.
        create_time: Output only. When this share link was created.
        expire_time: Optional. When set, the share link stops working after this time. If unset, the
            link never expires.
    """

    if not isinstance(create_time, NotGiven) and create_time is not None:
        validate_date_time("createTime", create_time)

    if not isinstance(expire_time, NotGiven) and expire_time is not None:
        validate_date_time("expireTime", expire_time)

    _resp = sdk_request_sync(
        "POST",
        f"/api/v1/memos/{encode_path_segment(memo)}/shares",
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "createTime": (
                    NOT_GIVEN
                    if create_time is NOT_GIVEN
                    else to_wire(create_time, "datetime.datetime")
                ),
                "expireTime": (
                    NOT_GIVEN
                    if expire_time is NOT_GIVEN
                    else to_wire(expire_time, "datetime.datetime")
                ),
            }
        ),
        operation_id="memo_service_create_memo_share",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_validate_response_enums(_resp.data, "MemoShare"), MemoShare)


MemoServiceDeleteMemoShareError: TypeAlias = Status


async def memo_service_delete_memo_share(
    _client_config: ClientConfig,
    memo: str,
    share: str,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Deletes a share link and revokes its read-only access to a memo. The authenticated
    user must be the memo creator or an instance administrator, and the share must
    belong to the specified memo.

    DeleteMemoShare revokes a share link. Requires the memo creator or an instance
    administrator.

    Args:
        memo: The memo id.
        share: The share id.
    """

    _resp = await sdk_request(
        "DELETE",
        f"/api/v1/memos/{encode_path_segment(memo)}/shares/{encode_path_segment(share)}",
        operation_id="memo_service_delete_memo_share",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


def memo_service_delete_memo_share_sync(
    _client_config: ClientConfig,
    memo: str,
    share: str,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Deletes a share link and revokes its read-only access to a memo. The authenticated
    user must be the memo creator or an instance administrator, and the share must
    belong to the specified memo.

    DeleteMemoShare revokes a share link. Requires the memo creator or an instance
    administrator.

    Args:
        memo: The memo id.
        share: The share id.
    """

    _resp = sdk_request_sync(
        "DELETE",
        f"/api/v1/memos/{encode_path_segment(memo)}/shares/{encode_path_segment(share)}",
        operation_id="memo_service_delete_memo_share",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


MemoServiceGetSharedMemoError: TypeAlias = Status


async def memo_service_get_shared_memo(
    _client_config: ClientConfig,
    share_token: str,
    *,
    request_options: RequestOptions | None = None,
) -> Memo:
    """Retrieves the memo associated with a share token without requiring authentication.
    Use the opaque `shareToken` from the share URL; the token must be valid and
    unexpired to resolve the memo.

    GetSharedMemo resolves a share token to its memo. No authentication required.
    Returns NOT_FOUND if the token is invalid or expired.

    Args:
        share_token: Required. The opaque bearer token extracted from the share URL.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v1/shares/{encode_path_segment(share_token)}/memo",
        operation_id="memo_service_get_shared_memo",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_validate_response_enums(_resp.data, "Memo"), Memo)


def memo_service_get_shared_memo_sync(
    _client_config: ClientConfig,
    share_token: str,
    *,
    request_options: RequestOptions | None = None,
) -> Memo:
    """Retrieves the memo associated with a share token without requiring authentication.
    Use the opaque `shareToken` from the share URL; the token must be valid and
    unexpired to resolve the memo.

    GetSharedMemo resolves a share token to its memo. No authentication required.
    Returns NOT_FOUND if the token is invalid or expired.

    Args:
        share_token: Required. The opaque bearer token extracted from the share URL.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v1/shares/{encode_path_segment(share_token)}/memo",
        operation_id="memo_service_get_shared_memo",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_validate_response_enums(_resp.data, "Memo"), Memo)


__all__ = [
    "MemoServiceCreateMemoShareError",
    "MemoServiceDeleteMemoShareError",
    "MemoServiceGetSharedMemoError",
    "MemoServiceListMemoRelationsError",
    "MemoServiceListMemoSharesError",
    "MemoServiceSetMemoRelationsError",
    "memo_service_create_memo_share",
    "memo_service_create_memo_share_sync",
    "memo_service_delete_memo_share",
    "memo_service_delete_memo_share_sync",
    "memo_service_get_shared_memo",
    "memo_service_get_shared_memo_sync",
    "memo_service_list_memo_relations",
    "memo_service_list_memo_relations_sync",
    "memo_service_list_memo_shares",
    "memo_service_list_memo_shares_sync",
    "memo_service_set_memo_relations",
    "memo_service_set_memo_relations_sync",
]
