# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime
from typing import Any, Literal, TypeAlias

from pydantic import TypeAdapter

import memos_unofficial_sdk.types as _response_types
from memos_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    omit_unset,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from memos_unofficial_sdk.types import (
    Attachment,
    BatchGetLinkMetadataResponse,
    LinkMetadata,
    ListMemosResponse,
    Location,
    Memo,
    Memo_Property,
    MemoRelation,
    Reaction,
    Status,
)
from memos_unofficial_sdk.validation import validate_date_time
from memos_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


MemoServiceListMemosError: TypeAlias = Status


async def memo_service_list_memos(
    _client_config: ClientConfig,
    page_size: int | NotGiven = NOT_GIVEN,
    page_token: str | NotGiven = NOT_GIVEN,
    state: Literal["STATE_UNSPECIFIED", "NORMAL", "ARCHIVED"] | str | NotGiven = NOT_GIVEN,
    order_by: str | NotGiven = NOT_GIVEN,
    filter: str | NotGiven = NOT_GIVEN,
    show_deleted: bool | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ListMemosResponse:
    """Lists readable, non-comment memos, with support for pagination, filtering, and
    sorting. Use `filter` to select memos and `orderBy` to control their order;
    `pageToken` continues a listing from a previous response.

    ListMemos lists readable non-comment memos with pagination and filter.

    Args:
        page_size: Optional. The maximum number of memos to return. The service may return fewer
            than this value. If unspecified, at most 50 memos will be returned. The maximum
            value is 1000; values above 1000 will be coerced to 1000.
        page_token: Optional. A page token, received from a previous `ListMemos` call. Provide this
            to retrieve the subsequent page.
        state: Optional. The state of the memos to list. Default to `NORMAL`. Set to `ARCHIVED`
            to list archived memos.
        order_by: Optional. The order to sort results by. Default to "create_time desc". Supports
            comma-separated list of fields following AIP-132. Example: "pinned desc,
            create_time desc" or "update_time asc" Supported fields: pinned, create_time,
            update_time, name. Note: order_by uses create_time / update_time, while the
            filter expression uses created_ts / updated_ts for the same timestamps.
        filter: Optional. A CEL expression to filter memos. Combine terms with && and ||.
            Available fields: content (string), creator (string, e.g. "users/1"), created_ts
            / updated_ts (timestamp), pinned (bool), visibility (string: PRIVATE | PROTECTED
            | PUBLIC | SPACE), space (string resource name, or null when the memo has no
            space; supports == and comparisons against null, e.g. space != null), tags
            (list<string>; match with `"work" in tags`, not `tag == "work"`), has_task_list
            / has_link / has_code / has_incomplete_tasks (bool), has_location (bool; true
            when the memo has a location attached). Note: the time fields here are
            created_ts / updated_ts, which differ from the create_time / update_time names
            used by order_by. Examples: pinned == true && visibility == "PUBLIC" space ==
            "spaces/team" or space == null tags.exists(t, t == "urgent")
            content.contains("roadmap") && created_ts > now - duration("168h")
        show_deleted: Optional. If true, show deleted memos in the response.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v1/memos",
        params=serialize_query(
            [
                ("pageSize", page_size, "form", True),
                ("pageToken", page_token, "form", True),
                ("state", state, "form", True),
                ("orderBy", order_by, "form", True),
                ("filter", filter, "form", True),
                ("showDeleted", show_deleted, "form", True),
            ]
        ),
        operation_id="memo_service_list_memos",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListMemosResponse"), ListMemosResponse
    )


def memo_service_list_memos_sync(
    _client_config: ClientConfig,
    page_size: int | NotGiven = NOT_GIVEN,
    page_token: str | NotGiven = NOT_GIVEN,
    state: Literal["STATE_UNSPECIFIED", "NORMAL", "ARCHIVED"] | str | NotGiven = NOT_GIVEN,
    order_by: str | NotGiven = NOT_GIVEN,
    filter: str | NotGiven = NOT_GIVEN,
    show_deleted: bool | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ListMemosResponse:
    """Lists readable, non-comment memos, with support for pagination, filtering, and
    sorting. Use `filter` to select memos and `orderBy` to control their order;
    `pageToken` continues a listing from a previous response.

    ListMemos lists readable non-comment memos with pagination and filter.

    Args:
        page_size: Optional. The maximum number of memos to return. The service may return fewer
            than this value. If unspecified, at most 50 memos will be returned. The maximum
            value is 1000; values above 1000 will be coerced to 1000.
        page_token: Optional. A page token, received from a previous `ListMemos` call. Provide this
            to retrieve the subsequent page.
        state: Optional. The state of the memos to list. Default to `NORMAL`. Set to `ARCHIVED`
            to list archived memos.
        order_by: Optional. The order to sort results by. Default to "create_time desc". Supports
            comma-separated list of fields following AIP-132. Example: "pinned desc,
            create_time desc" or "update_time asc" Supported fields: pinned, create_time,
            update_time, name. Note: order_by uses create_time / update_time, while the
            filter expression uses created_ts / updated_ts for the same timestamps.
        filter: Optional. A CEL expression to filter memos. Combine terms with && and ||.
            Available fields: content (string), creator (string, e.g. "users/1"), created_ts
            / updated_ts (timestamp), pinned (bool), visibility (string: PRIVATE | PROTECTED
            | PUBLIC | SPACE), space (string resource name, or null when the memo has no
            space; supports == and comparisons against null, e.g. space != null), tags
            (list<string>; match with `"work" in tags`, not `tag == "work"`), has_task_list
            / has_link / has_code / has_incomplete_tasks (bool), has_location (bool; true
            when the memo has a location attached). Note: the time fields here are
            created_ts / updated_ts, which differ from the create_time / update_time names
            used by order_by. Examples: pinned == true && visibility == "PUBLIC" space ==
            "spaces/team" or space == null tags.exists(t, t == "urgent")
            content.contains("roadmap") && created_ts > now - duration("168h")
        show_deleted: Optional. If true, show deleted memos in the response.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v1/memos",
        params=serialize_query(
            [
                ("pageSize", page_size, "form", True),
                ("pageToken", page_token, "form", True),
                ("state", state, "form", True),
                ("orderBy", order_by, "form", True),
                ("filter", filter, "form", True),
                ("showDeleted", show_deleted, "form", True),
            ]
        ),
        operation_id="memo_service_list_memos",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListMemosResponse"), ListMemosResponse
    )


MemoServiceCreateMemoError: TypeAlias = Status


async def memo_service_create_memo(
    _client_config: ClientConfig,
    state: Literal["STATE_UNSPECIFIED", "NORMAL", "ARCHIVED"] | str,
    content: str,
    visibility: Literal["VISIBILITY_UNSPECIFIED", "PRIVATE", "PROTECTED", "PUBLIC", "SPACE"] | str,
    memo_id: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    creator: str | NotGiven = NOT_GIVEN,
    create_time: datetime.datetime | NotGiven = NOT_GIVEN,
    update_time: datetime.datetime | NotGiven = NOT_GIVEN,
    tags: list[str] | NotGiven = NOT_GIVEN,
    pinned: bool | NotGiven = NOT_GIVEN,
    attachments: list[Attachment] | NotGiven = NOT_GIVEN,
    relations: list[MemoRelation] | NotGiven = NOT_GIVEN,
    reactions: list[Reaction] | NotGiven = NOT_GIVEN,
    property: Memo_Property | NotGiven = NOT_GIVEN,
    parent: str | NotGiven = NOT_GIVEN,
    snippet: str | NotGiven = NOT_GIVEN,
    location: Location | NotGiven = NOT_GIVEN,
    space: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Memo:
    """Creates a memo owned by the authenticated user. Supply `content` in Markdown and
    choose a `visibility`; visibility defaults to PRIVATE when omitted. You must
    authenticate to create a memo.

    CreateMemo creates a memo. The request body is a Memo; set its content (Markdown)
    and visibility (PRIVATE | PROTECTED | PUBLIC | SPACE, default PRIVATE). The memo is
    owned by the authenticated user; requires authentication.

    Args:
        state: The state of the memo.
        content: Required. The content of the memo in Markdown format.
        visibility: The visibility of the memo. One of PRIVATE (creator only), PROTECTED (signed-in
            users), PUBLIC (anonymous-eligible), or SPACE (active space members). Defaults
            to PRIVATE on creation when unspecified.
        memo_id: Optional. The memo ID to use for this memo. If empty, a unique ID will be
            generated. Format: ^[a-zA-Z0-9]([a-zA-Z0-9-]{0,34}[a-zA-Z0-9])?$
        name: The resource name of the memo. Format: memos/{memo}, where memo is the
            user-defined UID.
        creator: The name of the creator. Format: users/{user}
        create_time: The creation timestamp. If not set on creation, the server will set it to the
            current time.
        update_time: The last update timestamp. If not set on creation, the server will set it to the
            current time.
        tags: Output only. The tags extracted from the content.
        pinned: Whether the memo is pinned.
        attachments: Optional. The attachments of the memo.
        relations: Optional. The relations of the memo.
        reactions: Output only. The reactions to the memo.
        property: Output only. The computed properties of the memo.
        parent: Output only. The context memo of this COMMENT relation, if any. Its identity is
            returned even when the caller cannot read the parent. Fetch the parent
            independently; this field does not grant read access. Format: memos/{memo}
        snippet: Output only. The snippet of the memo content. Plain text only.
        location: Optional. The location of the memo.
        space: Optional. The space in which this memo is placed. Format: spaces/{space}. Every
            memo, including a comment, owns its placement independently.
    """

    if not isinstance(create_time, NotGiven) and create_time is not None:
        validate_date_time("createTime", create_time)

    if not isinstance(update_time, NotGiven) and update_time is not None:
        validate_date_time("updateTime", update_time)

    _resp = await sdk_request(
        "POST",
        "/api/v1/memos",
        params=serialize_query([("memoId", memo_id, "form", True)]),
        json=omit_unset(
            {
                "state": (
                    NOT_GIVEN
                    if state is NOT_GIVEN
                    else to_wire(state, 'Literal["STATE_UNSPECIFIED", "NORMAL", "ARCHIVED"] | str')
                ),
                "content": (NOT_GIVEN if content is NOT_GIVEN else to_wire(content, "str")),
                "visibility": (
                    NOT_GIVEN
                    if visibility is NOT_GIVEN
                    else to_wire(
                        visibility,
                        'Literal["VISIBILITY_UNSPECIFIED", "PRIVATE", "PROTECTED", "PUBLIC", "SPACE"] | str',
                    )
                ),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "creator": (NOT_GIVEN if creator is NOT_GIVEN else to_wire(creator, "str")),
                "createTime": (
                    NOT_GIVEN
                    if create_time is NOT_GIVEN
                    else to_wire(create_time, "datetime.datetime")
                ),
                "updateTime": (
                    NOT_GIVEN
                    if update_time is NOT_GIVEN
                    else to_wire(update_time, "datetime.datetime")
                ),
                "tags": (NOT_GIVEN if tags is NOT_GIVEN else to_wire(tags, "list[str]")),
                "pinned": (NOT_GIVEN if pinned is NOT_GIVEN else to_wire(pinned, "bool")),
                "attachments": (
                    NOT_GIVEN if attachments is NOT_GIVEN else to_wire(attachments, "Attachment")
                ),
                "relations": (
                    NOT_GIVEN if relations is NOT_GIVEN else to_wire(relations, "MemoRelation")
                ),
                "reactions": (
                    NOT_GIVEN if reactions is NOT_GIVEN else to_wire(reactions, "Reaction")
                ),
                "property": (
                    NOT_GIVEN if property is NOT_GIVEN else to_wire(property, "Memo_Property")
                ),
                "parent": (NOT_GIVEN if parent is NOT_GIVEN else to_wire(parent, "str")),
                "snippet": (NOT_GIVEN if snippet is NOT_GIVEN else to_wire(snippet, "str")),
                "location": (NOT_GIVEN if location is NOT_GIVEN else to_wire(location, "Location")),
                "space": (NOT_GIVEN if space is NOT_GIVEN else to_wire(space, "str")),
            }
        ),
        operation_id="memo_service_create_memo",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_validate_response_enums(_resp.data, "Memo"), Memo)


def memo_service_create_memo_sync(
    _client_config: ClientConfig,
    state: Literal["STATE_UNSPECIFIED", "NORMAL", "ARCHIVED"] | str,
    content: str,
    visibility: Literal["VISIBILITY_UNSPECIFIED", "PRIVATE", "PROTECTED", "PUBLIC", "SPACE"] | str,
    memo_id: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    creator: str | NotGiven = NOT_GIVEN,
    create_time: datetime.datetime | NotGiven = NOT_GIVEN,
    update_time: datetime.datetime | NotGiven = NOT_GIVEN,
    tags: list[str] | NotGiven = NOT_GIVEN,
    pinned: bool | NotGiven = NOT_GIVEN,
    attachments: list[Attachment] | NotGiven = NOT_GIVEN,
    relations: list[MemoRelation] | NotGiven = NOT_GIVEN,
    reactions: list[Reaction] | NotGiven = NOT_GIVEN,
    property: Memo_Property | NotGiven = NOT_GIVEN,
    parent: str | NotGiven = NOT_GIVEN,
    snippet: str | NotGiven = NOT_GIVEN,
    location: Location | NotGiven = NOT_GIVEN,
    space: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Memo:
    """Creates a memo owned by the authenticated user. Supply `content` in Markdown and
    choose a `visibility`; visibility defaults to PRIVATE when omitted. You must
    authenticate to create a memo.

    CreateMemo creates a memo. The request body is a Memo; set its content (Markdown)
    and visibility (PRIVATE | PROTECTED | PUBLIC | SPACE, default PRIVATE). The memo is
    owned by the authenticated user; requires authentication.

    Args:
        state: The state of the memo.
        content: Required. The content of the memo in Markdown format.
        visibility: The visibility of the memo. One of PRIVATE (creator only), PROTECTED (signed-in
            users), PUBLIC (anonymous-eligible), or SPACE (active space members). Defaults
            to PRIVATE on creation when unspecified.
        memo_id: Optional. The memo ID to use for this memo. If empty, a unique ID will be
            generated. Format: ^[a-zA-Z0-9]([a-zA-Z0-9-]{0,34}[a-zA-Z0-9])?$
        name: The resource name of the memo. Format: memos/{memo}, where memo is the
            user-defined UID.
        creator: The name of the creator. Format: users/{user}
        create_time: The creation timestamp. If not set on creation, the server will set it to the
            current time.
        update_time: The last update timestamp. If not set on creation, the server will set it to the
            current time.
        tags: Output only. The tags extracted from the content.
        pinned: Whether the memo is pinned.
        attachments: Optional. The attachments of the memo.
        relations: Optional. The relations of the memo.
        reactions: Output only. The reactions to the memo.
        property: Output only. The computed properties of the memo.
        parent: Output only. The context memo of this COMMENT relation, if any. Its identity is
            returned even when the caller cannot read the parent. Fetch the parent
            independently; this field does not grant read access. Format: memos/{memo}
        snippet: Output only. The snippet of the memo content. Plain text only.
        location: Optional. The location of the memo.
        space: Optional. The space in which this memo is placed. Format: spaces/{space}. Every
            memo, including a comment, owns its placement independently.
    """

    if not isinstance(create_time, NotGiven) and create_time is not None:
        validate_date_time("createTime", create_time)

    if not isinstance(update_time, NotGiven) and update_time is not None:
        validate_date_time("updateTime", update_time)

    _resp = sdk_request_sync(
        "POST",
        "/api/v1/memos",
        params=serialize_query([("memoId", memo_id, "form", True)]),
        json=omit_unset(
            {
                "state": (
                    NOT_GIVEN
                    if state is NOT_GIVEN
                    else to_wire(state, 'Literal["STATE_UNSPECIFIED", "NORMAL", "ARCHIVED"] | str')
                ),
                "content": (NOT_GIVEN if content is NOT_GIVEN else to_wire(content, "str")),
                "visibility": (
                    NOT_GIVEN
                    if visibility is NOT_GIVEN
                    else to_wire(
                        visibility,
                        'Literal["VISIBILITY_UNSPECIFIED", "PRIVATE", "PROTECTED", "PUBLIC", "SPACE"] | str',
                    )
                ),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "creator": (NOT_GIVEN if creator is NOT_GIVEN else to_wire(creator, "str")),
                "createTime": (
                    NOT_GIVEN
                    if create_time is NOT_GIVEN
                    else to_wire(create_time, "datetime.datetime")
                ),
                "updateTime": (
                    NOT_GIVEN
                    if update_time is NOT_GIVEN
                    else to_wire(update_time, "datetime.datetime")
                ),
                "tags": (NOT_GIVEN if tags is NOT_GIVEN else to_wire(tags, "list[str]")),
                "pinned": (NOT_GIVEN if pinned is NOT_GIVEN else to_wire(pinned, "bool")),
                "attachments": (
                    NOT_GIVEN if attachments is NOT_GIVEN else to_wire(attachments, "Attachment")
                ),
                "relations": (
                    NOT_GIVEN if relations is NOT_GIVEN else to_wire(relations, "MemoRelation")
                ),
                "reactions": (
                    NOT_GIVEN if reactions is NOT_GIVEN else to_wire(reactions, "Reaction")
                ),
                "property": (
                    NOT_GIVEN if property is NOT_GIVEN else to_wire(property, "Memo_Property")
                ),
                "parent": (NOT_GIVEN if parent is NOT_GIVEN else to_wire(parent, "str")),
                "snippet": (NOT_GIVEN if snippet is NOT_GIVEN else to_wire(snippet, "str")),
                "location": (NOT_GIVEN if location is NOT_GIVEN else to_wire(location, "Location")),
                "space": (NOT_GIVEN if space is NOT_GIVEN else to_wire(space, "str")),
            }
        ),
        operation_id="memo_service_create_memo",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_validate_response_enums(_resp.data, "Memo"), Memo)


MemoServiceGetLinkMetadataError: TypeAlias = Status


async def memo_service_get_link_metadata(
    _client_config: ClientConfig,
    url: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> LinkMetadata:
    """Retrieves metadata for a link. Provide the link's `url` to get its title,
    description, and image URL.

    GetLinkMetadata gets metadata for a link.

    Args:
        url: Required. The link URL.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v1/memos/-/linkMetadata",
        params=serialize_query([("url", url, "form", True)]),
        operation_id="memo_service_get_link_metadata",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "LinkMetadata"), LinkMetadata
    )


def memo_service_get_link_metadata_sync(
    _client_config: ClientConfig,
    url: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> LinkMetadata:
    """Retrieves metadata for a link. Provide the link's `url` to get its title,
    description, and image URL.

    GetLinkMetadata gets metadata for a link.

    Args:
        url: Required. The link URL.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v1/memos/-/linkMetadata",
        params=serialize_query([("url", url, "form", True)]),
        operation_id="memo_service_get_link_metadata",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "LinkMetadata"), LinkMetadata
    )


MemoServiceBatchGetLinkMetadataError: TypeAlias = Status


async def memo_service_batch_get_link_metadata(
    _client_config: ClientConfig,
    urls: list[str],
    *,
    request_options: RequestOptions | None = None,
) -> BatchGetLinkMetadataResponse:
    """Retrieves metadata for multiple links in one request. Supply the link URLs in
    `urls`; the response preserves the input order.

    BatchGetLinkMetadata gets metadata for links.

    Args:
        urls: Required. The link URLs.
    """

    _resp = await sdk_request(
        "POST",
        "/api/v1/memos/-/linkMetadata:batchGet",
        json=omit_unset(
            {
                "urls": (NOT_GIVEN if urls is NOT_GIVEN else to_wire(urls, "list[str]")),
            }
        ),
        operation_id="memo_service_batch_get_link_metadata",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "BatchGetLinkMetadataResponse"),
        BatchGetLinkMetadataResponse,
    )


def memo_service_batch_get_link_metadata_sync(
    _client_config: ClientConfig,
    urls: list[str],
    *,
    request_options: RequestOptions | None = None,
) -> BatchGetLinkMetadataResponse:
    """Retrieves metadata for multiple links in one request. Supply the link URLs in
    `urls`; the response preserves the input order.

    BatchGetLinkMetadata gets metadata for links.

    Args:
        urls: Required. The link URLs.
    """

    _resp = sdk_request_sync(
        "POST",
        "/api/v1/memos/-/linkMetadata:batchGet",
        json=omit_unset(
            {
                "urls": (NOT_GIVEN if urls is NOT_GIVEN else to_wire(urls, "list[str]")),
            }
        ),
        operation_id="memo_service_batch_get_link_metadata",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "BatchGetLinkMetadataResponse"),
        BatchGetLinkMetadataResponse,
    )


__all__ = [
    "MemoServiceBatchGetLinkMetadataError",
    "MemoServiceCreateMemoError",
    "MemoServiceGetLinkMetadataError",
    "MemoServiceListMemosError",
    "memo_service_batch_get_link_metadata",
    "memo_service_batch_get_link_metadata_sync",
    "memo_service_create_memo",
    "memo_service_create_memo_sync",
    "memo_service_get_link_metadata",
    "memo_service_get_link_metadata_sync",
    "memo_service_list_memos",
    "memo_service_list_memos_sync",
]
