# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, model_validator

from memos_unofficial_sdk.client import NOT_GIVEN, NotGiven

from ..validation import validate_required


class TranscribeRequest(BaseModel):
    """Typed representation of the `TranscribeRequest` API schema."""

    audio: TranscriptionAudio
    """Required. Audio input."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["audio"])
        return value


class TranscribeResponse(BaseModel):
    """Typed representation of the `TranscribeResponse` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    text: str | NotGiven = NOT_GIVEN
    """The transcribed text."""


class TranscriptionAudio(BaseModel):
    """Typed representation of the `TranscriptionAudio` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    content: str | NotGiven = NOT_GIVEN
    """Inline audio bytes."""
    uri: str | NotGiven = NOT_GIVEN
    """URI for audio content. Reserved for future use."""
    filename: str | NotGiven = NOT_GIVEN
    """Optional. The uploaded filename."""
    content_type: str | NotGiven = Field(NOT_GIVEN, alias="contentType")
    """Optional. The MIME type of the input audio."""
