# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, model_validator

from memos_unofficial_sdk.client import NOT_GIVEN, NotGiven
from memos_unofficial_sdk.types.shared import Attachment

from ..validation import validate_required


class BatchDeleteAttachmentsRequest(BaseModel):
    """Typed representation of the `BatchDeleteAttachmentsRequest` API schema."""

    names: list[str]
    """Required array value serialized in the `names` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["names"])
        return value


class ListAttachmentsResponse(BaseModel):
    """Typed representation of the `ListAttachmentsResponse` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    attachments: list[Attachment] | NotGiven = NOT_GIVEN
    """The list of attachments."""
    next_page_token: str | NotGiven = Field(NOT_GIVEN, alias="nextPageToken")
    """
    A token that can be sent as `page_token` to retrieve the next page.
     If this field is omitted, there are no subsequent pages.
    """


class UploadAttachmentRequest(BaseModel):
    """Typed representation of the `UploadAttachmentRequest` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    write_offset: str = Field(alias="writeOffset")
    """
    Required. Zero-based byte offset at which data is written. Must equal the
     committed size, except when retrying the most recently accepted chunk
     with identical bytes and offset, which is accepted without writing again.
    """
    spec: UploadAttachmentSpec | NotGiven = NOT_GIVEN
    """Starts a new upload. The same call may also carry data and finish_write."""
    upload_id: str | NotGiven = Field(NOT_GIVEN, alias="uploadId")
    """Continues the upload identified by a previous response."""
    data: str | NotGiven = NOT_GIVEN
    """
    Optional. File bytes, at most max_chunk_size long. With no data and
     finish_write false, the call reports progress without writing, and
     write_offset is ignored.
    """
    finish_write: bool | NotGiven = Field(NOT_GIVEN, alias="finishWrite")
    """
    Optional. Finalize the upload after writing data. The committed size must
     then equal total_size. Any later call for the same upload_id returns the
     created attachment.
    """

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["writeOffset"], {"writeOffset": "write_offset"})
        return value


class UploadAttachmentResponse(BaseModel):
    """Typed representation of the `UploadAttachmentResponse` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    upload_id: str | NotGiven = Field(NOT_GIVEN, alias="uploadId")
    """Opaque ID for subsequent calls. This is not a resource name."""
    committed_size: str | NotGiven = Field(NOT_GIVEN, alias="committedSize")
    """Number of file bytes committed so far."""
    attachment: Attachment | NotGiven = NOT_GIVEN
    """Set once the upload has been finalized."""
    max_chunk_size: int | NotGiven = Field(NOT_GIVEN, alias="maxChunkSize")
    """Maximum number of data bytes accepted in one call."""


class UploadAttachmentSpec(BaseModel):
    """Typed representation of the `UploadAttachmentSpec` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    attachment: Attachment
    """
    Required. Metadata for the attachment to create. content must be empty;
     file bytes are sent in data.
    """
    attachment_id: str | NotGiven = Field(NOT_GIVEN, alias="attachmentId")
    """
    Optional. The attachment ID to use for this attachment.
     If empty, a unique ID will be generated.
     Format: ^[a-zA-Z0-9]([a-zA-Z0-9-]{0,34}[a-zA-Z0-9])?$
    """
    total_size: str | NotGiven = Field(NOT_GIVEN, alias="totalSize")
    """
    Optional. Total size of the file in bytes before media processing.
     Zero represents an empty file.
    """

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["attachment"])
        return value
