# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from memos_unofficial_sdk.client import NOT_GIVEN, NotGiven
from memos_unofficial_sdk.types.shared import User

from ..validation import validate_date_time, validate_required


class GetCurrentUserResponse(BaseModel):
    """Typed representation of the `GetCurrentUserResponse` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    user: User | NotGiven = NOT_GIVEN
    """The authenticated user's information."""


class RefreshTokenRequest(BaseModel):
    """Typed representation of the `RefreshTokenRequest` API schema."""


class RefreshTokenResponse(BaseModel):
    """Typed representation of the `RefreshTokenResponse` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    access_token: str | NotGiven = Field(NOT_GIVEN, alias="accessToken")
    """The new short-lived access token."""
    expires_at: datetime.datetime | NotGiven = Field(NOT_GIVEN, alias="expiresAt")
    """When the access token expires."""

    @field_validator("expires_at", mode="before")
    @classmethod
    def _validate_expires_at(cls, value):
        validate_date_time("expiresAt", value)
        return value


class SignInRequest(BaseModel):
    """Typed representation of the `SignInRequest` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    password_credentials: SignInRequest_PasswordCredentials | NotGiven = Field(
        NOT_GIVEN, alias="passwordCredentials"
    )
    """Username and password authentication."""
    sso_credentials: SignInRequest_SSOCredentials | NotGiven = Field(
        NOT_GIVEN, alias="ssoCredentials"
    )
    """SSO provider authentication."""


class SignInRequest_PasswordCredentials(BaseModel):
    """Nested message for password-based authentication credentials."""

    username: str
    """The username to sign in with."""
    password: str
    """The password to sign in with."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["username", "password"])
        return value


class SignInRequest_SSOCredentials(BaseModel):
    """Nested message for SSO authentication credentials."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    idp_name: str = Field(alias="idpName")
    """
    The resource name of the SSO provider.
     Format: identity-providers/{idp}
    """
    code: str
    """The authorization code from the SSO provider."""
    redirect_uri: str = Field(alias="redirectUri")
    """The redirect URI used in the SSO flow."""
    code_verifier: str | NotGiven = Field(NOT_GIVEN, alias="codeVerifier")
    """
    The PKCE code verifier for enhanced security (RFC 7636).
     Optional - enables PKCE flow protection against authorization code interception.
    """

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(
            value,
            ["idpName", "code", "redirectUri"],
            {"idpName": "idp_name", "redirectUri": "redirect_uri"},
        )
        return value


class SignInResponse(BaseModel):
    """Typed representation of the `SignInResponse` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    user: User | NotGiven = NOT_GIVEN
    """The authenticated user's information."""
    access_token: str | NotGiven = Field(NOT_GIVEN, alias="accessToken")
    """
    The short-lived access token for API requests.
     Store in memory only, not in localStorage.
    """
    access_token_expires_at: datetime.datetime | NotGiven = Field(
        NOT_GIVEN, alias="accessTokenExpiresAt"
    )
    """
    When the access token expires.
     Client should call RefreshToken before this time.
    """

    @field_validator("access_token_expires_at", mode="before")
    @classmethod
    def _validate_access_token_expires_at(cls, value):
        validate_date_time("accessTokenExpiresAt", value)
        return value
