# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from memos_unofficial_sdk.client import NOT_GIVEN, NotGiven
from memos_unofficial_sdk.types.shared import Color, User

from ..validation import validate_date_time, validate_required


class BatchGetInstanceSettingsRequest(BaseModel):
    """Request message for BatchGetInstanceSettings method."""

    names: list[str]
    """
    The resource names of the instance settings.
     Format: instance/settings/{setting}
    """

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["names"])
        return value


class BatchGetInstanceSettingsResponse(BaseModel):
    """Response message for BatchGetInstanceSettings method."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    settings: list[InstanceSetting] | NotGiven = NOT_GIVEN
    """The instance settings in the same order as the input names."""


class GeneralSetting_CustomProfile(BaseModel):
    """Custom profile configuration for instance branding."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    title: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `title` wire field."""
    description: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `description` wire field."""
    logo_url: str | NotGiven = Field(NOT_GIVEN, alias="logoUrl")
    """Optional `string` value serialized in the `logoUrl` wire field."""


class InstanceProfile(BaseModel):
    """Instance profile message containing basic instance information."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    version: str | NotGiven = NOT_GIVEN
    """Version is the current version of instance."""
    demo: bool | NotGiven = NOT_GIVEN
    """Demo indicates if the instance is in demo mode."""
    instance_url: str | NotGiven = Field(NOT_GIVEN, alias="instanceUrl")
    """Instance URL is the URL of the instance."""
    admin: User | NotGiven = NOT_GIVEN
    """
    The first administrator who set up this instance, for display purposes.
     May be null on an instance that has lost all admins; use needs_setup to
     determine whether initial setup is actually required.
    """
    commit: str | NotGiven = NOT_GIVEN
    """Commit is the current build commit of instance."""
    needs_setup: bool | NotGiven = Field(NOT_GIVEN, alias="needsSetup")
    """
    NeedsSetup is true when the instance has no users yet and requires initial
     setup (creating the first admin account). Unlike a null admin, this stays
     false once any user exists, so an instance that has lost its admins is not
     mistaken for a fresh install.
    """
    access_mode: (
        Literal[
            "INSTANCE_ACCESS_MODE_UNSPECIFIED",
            "INSTANCE_ACCESS_MODE_PRIVATE",
            "INSTANCE_ACCESS_MODE_PUBLIC",
        ]
        | str
        | NotGiven
    ) = Field(NOT_GIVEN, alias="accessMode")
    """Access mode controls whether unauthenticated users may access instance content."""
    challenge: InstanceProfile_Challenge | NotGiven = NOT_GIVEN
    """
    A proof-of-humanity challenge the deployment requires on signup and
     password sign-in. Absent when none is configured, which is the case on
     every self-hosted instance.
    """


class InstanceProfile_Challenge(BaseModel):
    """
    A proof-of-humanity challenge the deployment requires on signup and
     password sign-in. Absent when none is configured, which is the case on
     every self-hosted instance.
    """

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    provider: str | NotGiven = NOT_GIVEN
    """The challenge provider, which selects the widget the web app renders."""
    site_key: str | NotGiven = Field(NOT_GIVEN, alias="siteKey")
    """The provider's public site key for the widget."""


class InstanceSetting(BaseModel):
    """An instance setting resource."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    name: str | NotGiven = NOT_GIVEN
    """
    The name of the instance setting.
     Format: instance/settings/{setting}
    """
    general_setting: InstanceSetting_GeneralSetting | NotGiven = Field(
        NOT_GIVEN, alias="generalSetting"
    )
    """General instance settings configuration."""
    storage_setting: InstanceSetting_StorageSetting | NotGiven = Field(
        NOT_GIVEN, alias="storageSetting"
    )
    """Storage configuration settings for instance attachments."""
    memo_related_setting: InstanceSetting_MemoRelatedSetting | NotGiven = Field(
        NOT_GIVEN, alias="memoRelatedSetting"
    )
    """Memo-related instance settings and policies."""
    tags_setting: InstanceSetting_TagsSetting | NotGiven = Field(NOT_GIVEN, alias="tagsSetting")
    """
    Tag metadata configuration.
     Active tag metadata is stored in per-user tag settings.
     This message remains for backward compatibility with existing clients and migrations.
    """
    notification_setting: InstanceSetting_NotificationSetting | NotGiven = Field(
        NOT_GIVEN, alias="notificationSetting"
    )
    """Notification transport configuration."""
    ai_setting: InstanceSetting_AISetting | NotGiven = Field(NOT_GIVEN, alias="aiSetting")
    """AI provider configuration settings."""
    access_setting: InstanceSetting_AccessSetting | NotGiven = Field(
        NOT_GIVEN, alias="accessSetting"
    )
    """Access policy configuration for the instance."""


class InstanceSetting_AIProviderConfig(BaseModel):
    """AIProviderConfig represents one callable AI provider connection."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    id: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `id` wire field."""
    title: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `title` wire field."""
    type: Literal["AI_PROVIDER_TYPE_UNSPECIFIED", "OPENAI", "GEMINI"] | str | NotGiven = NOT_GIVEN
    """Optional enumerated value serialized in the `type` wire field."""
    endpoint: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `endpoint` wire field."""
    api_key: str | NotGiven = Field(NOT_GIVEN, alias="apiKey")
    """api_key is write-only and is never returned by GetInstanceSetting."""
    api_key_set: bool | NotGiven = Field(NOT_GIVEN, alias="apiKeySet")
    """api_key_set indicates whether an API key is stored for this provider."""
    api_key_hint: str | NotGiven = Field(NOT_GIVEN, alias="apiKeyHint")
    """api_key_hint is a masked hint for the stored API key."""


class InstanceSetting_AISetting(BaseModel):
    """AI provider configuration settings."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    providers: list[InstanceSetting_AIProviderConfig] | NotGiven = NOT_GIVEN
    """providers is the list of AI provider configurations available instance-wide."""
    transcription: InstanceSetting_TranscriptionConfig | NotGiven = NOT_GIVEN
    """
    transcription is the speech-to-text feature configuration.
     When unset or transcription.provider_id is empty, transcription is disabled.
    """


class InstanceSetting_AccessSetting(BaseModel):
    """Access policy configuration for the instance."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    access_mode: (
        Literal[
            "INSTANCE_ACCESS_MODE_UNSPECIFIED",
            "INSTANCE_ACCESS_MODE_PRIVATE",
            "INSTANCE_ACCESS_MODE_PUBLIC",
        ]
        | str
        | NotGiven
    ) = Field(NOT_GIVEN, alias="accessMode")
    """Optional enumerated value serialized in the `accessMode` wire field."""


class InstanceSetting_GeneralSetting(BaseModel):
    """General instance settings configuration."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    disallow_user_registration: bool | NotGiven = Field(NOT_GIVEN, alias="disallowUserRegistration")
    """disallow_user_registration disallows user registration."""
    disallow_password_auth: bool | NotGiven = Field(NOT_GIVEN, alias="disallowPasswordAuth")
    """disallow_password_auth disallows password authentication."""
    additional_script: str | NotGiven = Field(NOT_GIVEN, alias="additionalScript")
    """additional_script is the additional script."""
    additional_style: str | NotGiven = Field(NOT_GIVEN, alias="additionalStyle")
    """additional_style is the additional style."""
    custom_profile: GeneralSetting_CustomProfile | NotGiven = Field(
        NOT_GIVEN, alias="customProfile"
    )
    """custom_profile is the custom profile."""
    week_start_day_offset: int | NotGiven = Field(NOT_GIVEN, alias="weekStartDayOffset")
    """
    week_start_day_offset is the week start day offset from Sunday.
     0: Sunday, 1: Monday, 2: Tuesday, 3: Wednesday, 4: Thursday, 5: Friday, 6: Saturday
     Default is Sunday.
    """
    disallow_change_username: bool | NotGiven = Field(NOT_GIVEN, alias="disallowChangeUsername")
    """disallow_change_username disallows changing username."""
    disallow_change_nickname: bool | NotGiven = Field(NOT_GIVEN, alias="disallowChangeNickname")
    """disallow_change_nickname disallows changing nickname."""


class InstanceSetting_MemoRelatedSetting(BaseModel):
    """Memo-related instance settings and policies."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    content_length_limit: int | NotGiven = Field(NOT_GIVEN, alias="contentLengthLimit")
    """content_length_limit is the limit of content length. Unit is byte."""
    enable_double_click_edit: bool | NotGiven = Field(NOT_GIVEN, alias="enableDoubleClickEdit")
    """enable_double_click_edit enables editing on double click."""
    reactions: list[str] | NotGiven = NOT_GIVEN
    """reactions is the list of reactions."""


class InstanceSetting_NotificationSetting(BaseModel):
    """Notification transport configuration."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    email: NotificationSetting_EmailSetting | NotGiven = NOT_GIVEN
    """Email delivery configuration for notifications."""


class InstanceSetting_Storage(BaseModel):
    """Storage is a configured attachment storage instance."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    id: str | NotGiven = NOT_GIVEN
    """id is the stable identifier referenced by attachments."""
    name: str | NotGiven = NOT_GIVEN
    """name is the human-readable storage name."""
    type: Literal["STORAGE_TYPE_UNSPECIFIED", "DATABASE", "LOCAL", "S3"] | str | NotGiven = (
        NOT_GIVEN
    )
    """Optional enumerated value serialized in the `type` wire field."""
    s3_config: Storage_S3Config | NotGiven = Field(NOT_GIVEN, alias="s3Config")
    """
    S3 configuration for an S3-compatible object store.
     Reference: https://developers.cloudflare.com/r2/examples/aws/aws-sdk-go/
    """


class InstanceSetting_StorageSetting(BaseModel):
    """Storage configuration settings for instance attachments."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    storage_type: (
        Literal["STORAGE_TYPE_UNSPECIFIED", "DATABASE", "LOCAL", "S3"] | str | NotGiven
    ) = Field(NOT_GIVEN, alias="storageType")
    """Legacy compatibility field. New clients use default_storage_id."""
    filepath_template: str | NotGiven = Field(NOT_GIVEN, alias="filepathTemplate")
    """
    The template of file path.
     e.g. assets/{timestamp}_{filename}
    """
    upload_size_limit_mb: str | NotGiven = Field(NOT_GIVEN, alias="uploadSizeLimitMb")
    """The max upload size in megabytes."""
    s3_config: StorageSetting_S3Config | NotGiven = Field(NOT_GIVEN, alias="s3Config")
    """Legacy compatibility field. New clients use storages."""
    storages: list[InstanceSetting_Storage] | NotGiven = NOT_GIVEN
    """Configured storage instances, including inactive instances referenced by attachments."""
    default_storage_id: str | NotGiven = Field(NOT_GIVEN, alias="defaultStorageId")
    """Storage used for new attachments."""


class InstanceSetting_TagMetadata(BaseModel):
    """Metadata for a tag."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    background_color: Color | NotGiven = Field(NOT_GIVEN, alias="backgroundColor")
    """
    Optional background color for the tag label.
     When unset, the default tag color is used.
    """
    blur_content: bool | NotGiven = Field(NOT_GIVEN, alias="blurContent")
    """Whether memos with this tag should have their content blurred."""


class InstanceSetting_TagsSetting(BaseModel):
    """
    Tag metadata configuration.
     Active tag metadata is stored in per-user tag settings.
     This message remains for backward compatibility with existing clients and migrations.
    """

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    tags: dict[str, InstanceSetting_TagMetadata] | NotGiven = NOT_GIVEN
    """
    Map of tag name pattern to tag metadata.
     Each key is treated as an anchored regular expression (^pattern$),
     so a single entry like "project/.*" matches all tags under that prefix.
     Exact tag names are also valid (they are trivially valid regex patterns).
    """


class InstanceSetting_TranscriptionConfig(BaseModel):
    """TranscriptionConfig configures the speech-to-text feature."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    provider_id: str | NotGiven = Field(NOT_GIVEN, alias="providerId")
    """
    provider_id references an entry in AISetting.providers[].id.
     Empty string means transcription is disabled.
    """
    model: str | NotGiven = NOT_GIVEN
    """
    model is the provider-specific model identifier.
     Empty string falls back to the engine default
     (whisper-1 for OPENAI providers, gemini-2.5-flash for GEMINI providers).
    """
    language: str | NotGiven = NOT_GIVEN
    """
    language is the default ISO 639-1 language hint sent to the provider.
     Empty string lets the provider auto-detect.
    """
    prompt: str | NotGiven = NOT_GIVEN
    """prompt is a default spelling/vocabulary hint passed to the provider."""


class InstanceStats(BaseModel):
    """Resource usage statistics for the instance."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    database: InstanceStats_DatabaseStats | NotGiven = NOT_GIVEN
    """Database size statistics."""
    local_storage_bytes: str | NotGiven = Field(NOT_GIVEN, alias="localStorageBytes")
    """Recursive size of the data directory in bytes. -1 if unavailable."""
    generated_time: datetime.datetime | NotGiven = Field(NOT_GIVEN, alias="generatedTime")
    """Server-side timestamp when the snapshot was generated."""

    @field_validator("generated_time", mode="before")
    @classmethod
    def _validate_generated_time(cls, value):
        validate_date_time("generatedTime", value)
        return value


class InstanceStats_DatabaseStats(BaseModel):
    """Database size statistics."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    driver: str | NotGiven = NOT_GIVEN
    """driver is one of "sqlite", "mysql", "postgres"."""
    size_bytes: str | NotGiven = Field(NOT_GIVEN, alias="sizeBytes")
    """size_bytes is the database size in bytes; -1 if unavailable."""


class NotificationSetting_EmailSetting(BaseModel):
    """Email delivery configuration for notifications."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    enabled: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `enabled` wire field."""
    smtp_host: str | NotGiven = Field(NOT_GIVEN, alias="smtpHost")
    """Optional `string` value serialized in the `smtpHost` wire field."""
    smtp_port: int | NotGiven = Field(NOT_GIVEN, alias="smtpPort")
    """Optional `int32`-formatted value serialized in the `smtpPort` wire field."""
    smtp_username: str | NotGiven = Field(NOT_GIVEN, alias="smtpUsername")
    """Optional `string` value serialized in the `smtpUsername` wire field."""
    smtp_password: str | NotGiven = Field(NOT_GIVEN, alias="smtpPassword")
    """Optional `string` value serialized in the `smtpPassword` wire field."""
    from_email: str | NotGiven = Field(NOT_GIVEN, alias="fromEmail")
    """Optional `string` value serialized in the `fromEmail` wire field."""
    from_name: str | NotGiven = Field(NOT_GIVEN, alias="fromName")
    """Optional `string` value serialized in the `fromName` wire field."""
    reply_to: str | NotGiven = Field(NOT_GIVEN, alias="replyTo")
    """Optional `string` value serialized in the `replyTo` wire field."""
    use_tls: bool | NotGiven = Field(NOT_GIVEN, alias="useTls")
    """Optional `boolean` value serialized in the `useTls` wire field."""
    use_ssl: bool | NotGiven = Field(NOT_GIVEN, alias="useSsl")
    """Optional `boolean` value serialized in the `useSsl` wire field."""


class StorageSetting_S3Config(BaseModel):
    """
    Legacy S3 configuration retained for compatibility with existing clients.
     Reference: https://developers.cloudflare.com/r2/examples/aws/aws-sdk-go/
    """

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    access_key_id: str | NotGiven = Field(NOT_GIVEN, alias="accessKeyId")
    """Optional `string` value serialized in the `accessKeyId` wire field."""
    access_key_secret: str | NotGiven = Field(NOT_GIVEN, alias="accessKeySecret")
    """Optional `string` value serialized in the `accessKeySecret` wire field."""
    endpoint: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `endpoint` wire field."""
    region: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `region` wire field."""
    bucket: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `bucket` wire field."""
    use_path_style: bool | NotGiven = Field(NOT_GIVEN, alias="usePathStyle")
    """Optional `boolean` value serialized in the `usePathStyle` wire field."""
    insecure_skip_tls_verify: bool | NotGiven = Field(NOT_GIVEN, alias="insecureSkipTlsVerify")
    """
    insecure_skip_tls_verify disables TLS certificate verification when connecting
     to the S3 endpoint. Only enable this for trusted endpoints that use a self-signed
     certificate; it removes protection against man-in-the-middle attacks.
    """


class Storage_S3Config(BaseModel):
    """
    S3 configuration for an S3-compatible object store.
     Reference: https://developers.cloudflare.com/r2/examples/aws/aws-sdk-go/
    """

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    access_key_id: str | NotGiven = Field(NOT_GIVEN, alias="accessKeyId")
    """Optional `string` value serialized in the `accessKeyId` wire field."""
    access_key_secret: str | NotGiven = Field(NOT_GIVEN, alias="accessKeySecret")
    """Optional `string` value serialized in the `accessKeySecret` wire field."""
    endpoint: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `endpoint` wire field."""
    region: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `region` wire field."""
    bucket: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `bucket` wire field."""
    use_path_style: bool | NotGiven = Field(NOT_GIVEN, alias="usePathStyle")
    """Optional `boolean` value serialized in the `usePathStyle` wire field."""
    insecure_skip_tls_verify: bool | NotGiven = Field(NOT_GIVEN, alias="insecureSkipTlsVerify")
    """
    insecure_skip_tls_verify disables TLS certificate verification when connecting
     to the S3 endpoint. Only enable this for trusted endpoints that use a self-signed
     certificate; it removes protection against man-in-the-middle attacks.
    """


class TestInstanceEmailSettingRequest(BaseModel):
    """Request message for TestInstanceEmailSetting method."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    email: NotificationSetting_EmailSetting | NotGiven = NOT_GIVEN
    """Optional. SMTP email settings to test. If omitted, the stored notification email setting is used."""
    recipient_email: str | NotGiven = Field(NOT_GIVEN, alias="recipientEmail")
    """Optional. Recipient email address. If omitted, the current user's email address is used."""
