# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from memos_unofficial_sdk.client import NOT_GIVEN, NotGiven
from memos_unofficial_sdk.types.shared import Attachment

from ..validation import validate_date_time, validate_required


class BatchGetLinkMetadataRequest(BaseModel):
    """Typed representation of the `BatchGetLinkMetadataRequest` API schema."""

    urls: list[str]
    """Required. The link URLs."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["urls"])
        return value


class BatchGetLinkMetadataResponse(BaseModel):
    """Typed representation of the `BatchGetLinkMetadataResponse` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    link_metadata: list[LinkMetadata] | NotGiven = Field(NOT_GIVEN, alias="linkMetadata")
    """The link metadata list, in the same order as the input URLs."""


class LinkMetadata(BaseModel):
    """Typed representation of the `LinkMetadata` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    url: str | NotGiven = NOT_GIVEN
    """The original link URL."""
    title: str | NotGiven = NOT_GIVEN
    """The link title."""
    description: str | NotGiven = NOT_GIVEN
    """The link description."""
    image: str | NotGiven = NOT_GIVEN
    """The link image URL."""


class ListMemoAttachmentsResponse(BaseModel):
    """Typed representation of the `ListMemoAttachmentsResponse` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    attachments: list[Attachment] | NotGiven = NOT_GIVEN
    """The list of attachments."""
    next_page_token: str | NotGiven = Field(NOT_GIVEN, alias="nextPageToken")
    """A token for the next page of results."""


class ListMemoCommentsResponse(BaseModel):
    """Typed representation of the `ListMemoCommentsResponse` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    memos: list[Memo] | NotGiven = NOT_GIVEN
    """The list of comment memos."""
    next_page_token: str | NotGiven = Field(NOT_GIVEN, alias="nextPageToken")
    """A token for the next page of results."""


class ListMemoReactionsResponse(BaseModel):
    """Typed representation of the `ListMemoReactionsResponse` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    reactions: list[Reaction] | NotGiven = NOT_GIVEN
    """The list of reactions."""
    next_page_token: str | NotGiven = Field(NOT_GIVEN, alias="nextPageToken")
    """A token for the next page of results."""


class ListMemoRelationsResponse(BaseModel):
    """Typed representation of the `ListMemoRelationsResponse` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    relations: list[MemoRelation] | NotGiven = NOT_GIVEN
    """The list of relations."""
    next_page_token: str | NotGiven = Field(NOT_GIVEN, alias="nextPageToken")
    """A token for the next page of results."""


class ListMemoSharesResponse(BaseModel):
    """Typed representation of the `ListMemoSharesResponse` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    memo_shares: list[MemoShare] | NotGiven = Field(NOT_GIVEN, alias="memoShares")
    """The list of share links."""


class ListMemosResponse(BaseModel):
    """Typed representation of the `ListMemosResponse` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    memos: list[Memo] | NotGiven = NOT_GIVEN
    """The list of memos."""
    next_page_token: str | NotGiven = Field(NOT_GIVEN, alias="nextPageToken")
    """
    A token that can be sent as `page_token` to retrieve the next page.
     If this field is omitted, there are no subsequent pages.
    """


class Location(BaseModel):
    """Typed representation of the `Location` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    placeholder: str | NotGiven = NOT_GIVEN
    """A placeholder text for the location."""
    latitude: float | NotGiven = NOT_GIVEN
    """The latitude of the location."""
    longitude: float | NotGiven = NOT_GIVEN
    """The longitude of the location."""


class Memo(BaseModel):
    """Typed representation of the `Memo` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    state: Literal["STATE_UNSPECIFIED", "NORMAL", "ARCHIVED"] | str
    """The state of the memo."""
    content: str
    """Required. The content of the memo in Markdown format."""
    visibility: Literal["VISIBILITY_UNSPECIFIED", "PRIVATE", "PROTECTED", "PUBLIC", "SPACE"] | str
    """
    The visibility of the memo.
     One of PRIVATE (creator only), PROTECTED (signed-in users), PUBLIC
     (anonymous-eligible), or SPACE (active space members). Defaults to
     PRIVATE on creation when unspecified.
    """
    name: str | NotGiven = NOT_GIVEN
    """
    The resource name of the memo.
     Format: memos/{memo}, where memo is the user-defined UID.
    """
    creator: str | NotGiven = NOT_GIVEN
    """
    The name of the creator.
     Format: users/{user}
    """
    create_time: datetime.datetime | NotGiven = Field(NOT_GIVEN, alias="createTime")
    """
    The creation timestamp.
     If not set on creation, the server will set it to the current time.
    """
    update_time: datetime.datetime | NotGiven = Field(NOT_GIVEN, alias="updateTime")
    """
    The last update timestamp.
     If not set on creation, the server will set it to the current time.
    """
    tags: list[str] | NotGiven = NOT_GIVEN
    """Output only. The tags extracted from the content."""
    pinned: bool | NotGiven = NOT_GIVEN
    """Whether the memo is pinned."""
    attachments: list[Attachment] | NotGiven = NOT_GIVEN
    """Optional. The attachments of the memo."""
    relations: list[MemoRelation] | NotGiven = NOT_GIVEN
    """Optional. The relations of the memo."""
    reactions: list[Reaction] | NotGiven = NOT_GIVEN
    """Output only. The reactions to the memo."""
    property: Memo_Property | NotGiven = NOT_GIVEN
    """Output only. The computed properties of the memo."""
    parent: str | NotGiven = NOT_GIVEN
    """
    Output only. The context memo of this COMMENT relation, if any.
     Its identity is returned even when the caller cannot read the parent.
     Fetch the parent independently; this field does not grant read access.
     Format: memos/{memo}
    """
    snippet: str | NotGiven = NOT_GIVEN
    """Output only. The snippet of the memo content. Plain text only."""
    location: Location | NotGiven = NOT_GIVEN
    """Optional. The location of the memo."""
    space: str | NotGiven = NOT_GIVEN
    """
    Optional. The space in which this memo is placed. Format: spaces/{space}.
     Every memo, including a comment, owns its placement independently.
    """

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["state", "content", "visibility"])
        return value

    @field_validator("create_time", mode="before")
    @classmethod
    def _validate_create_time(cls, value):
        validate_date_time("createTime", value)
        return value

    @field_validator("update_time", mode="before")
    @classmethod
    def _validate_update_time(cls, value):
        validate_date_time("updateTime", value)
        return value


class MemoRelation(BaseModel):
    """Typed representation of the `MemoRelation` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    memo: MemoRelation_Memo
    """The memo in the relation."""
    related_memo: MemoRelation_Memo = Field(alias="relatedMemo")
    """The related memo."""
    type: Literal["TYPE_UNSPECIFIED", "REFERENCE", "COMMENT"] | str
    """Required enumerated value serialized in the `type` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["memo", "relatedMemo", "type"], {"relatedMemo": "related_memo"})
        return value


class MemoRelation_Memo(BaseModel):
    """Memo reference in relations."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    name: str
    """
    The resource name of the memo.
     Format: memos/{memo}
    """
    snippet: str | NotGiven = NOT_GIVEN
    """Output only. The snippet of the memo content. Plain text only."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["name"])
        return value


class MemoShare(BaseModel):
    """MemoShare is an access grant that permits read-only access to a memo via an opaque bearer token."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    name: str | NotGiven = NOT_GIVEN
    """
    The resource name of the share. Format: memos/{memo}/shares/{share}
     The {share} segment is the opaque token used in the share URL.
    """
    create_time: datetime.datetime | NotGiven = Field(NOT_GIVEN, alias="createTime")
    """Output only. When this share link was created."""
    expire_time: datetime.datetime | NotGiven = Field(NOT_GIVEN, alias="expireTime")
    """
    Optional. When set, the share link stops working after this time.
     If unset, the link never expires.
    """

    @field_validator("create_time", mode="before")
    @classmethod
    def _validate_create_time(cls, value):
        validate_date_time("createTime", value)
        return value

    @field_validator("expire_time", mode="before")
    @classmethod
    def _validate_expire_time(cls, value):
        validate_date_time("expireTime", value)
        return value


class Memo_Property(BaseModel):
    """Computed properties of a memo."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    has_link: bool | NotGiven = Field(NOT_GIVEN, alias="hasLink")
    """Optional `boolean` value serialized in the `hasLink` wire field."""
    has_task_list: bool | NotGiven = Field(NOT_GIVEN, alias="hasTaskList")
    """Optional `boolean` value serialized in the `hasTaskList` wire field."""
    has_code: bool | NotGiven = Field(NOT_GIVEN, alias="hasCode")
    """Optional `boolean` value serialized in the `hasCode` wire field."""
    has_incomplete_tasks: bool | NotGiven = Field(NOT_GIVEN, alias="hasIncompleteTasks")
    """Optional `boolean` value serialized in the `hasIncompleteTasks` wire field."""
    title: str | NotGiven = NOT_GIVEN
    """The title extracted from the first H1 heading, if present."""


class Reaction(BaseModel):
    """Reaction is a reaction attached to a memo."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    reaction_type: str = Field(alias="reactionType")
    """Required. The type of reaction (e.g., "👍", "❤️", "😄")."""
    name: str | NotGiven = NOT_GIVEN
    """
    The resource name of the reaction.
     Format: memos/{memo}/reactions/{reaction}
    """
    creator: str | NotGiven = NOT_GIVEN
    """
    The resource name of the creator.
     Format: users/{user}
    """
    create_time: datetime.datetime | NotGiven = Field(NOT_GIVEN, alias="createTime")
    """Output only. The creation timestamp."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["reactionType"], {"reactionType": "reaction_type"})
        return value

    @field_validator("create_time", mode="before")
    @classmethod
    def _validate_create_time(cls, value):
        validate_date_time("createTime", value)
        return value


class SetMemoAttachmentsRequest(BaseModel):
    """Typed representation of the `SetMemoAttachmentsRequest` API schema."""

    name: str
    """
    Required. The resource name of the memo.
     Format: memos/{memo}
    """
    attachments: list[Attachment]
    """Required. The attachments to set for the memo."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["name", "attachments"])
        return value


class SetMemoRelationsRequest(BaseModel):
    """Typed representation of the `SetMemoRelationsRequest` API schema."""

    name: str
    """
    Required. The resource name of the memo.
     Format: memos/{memo}
    """
    relations: list[MemoRelation]
    """Required. The REFERENCE relations to set for the memo. COMMENT is invalid."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["name", "relations"])
        return value


class UpsertMemoReactionRequest(BaseModel):
    """Typed representation of the `UpsertMemoReactionRequest` API schema."""

    name: str
    """
    Required. The resource name of the memo.
     Format: memos/{memo}
    """
    reaction: Reaction
    """Required. The reaction to upsert."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["name", "reaction"])
        return value
