# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from memos_unofficial_sdk.client import NOT_GIVEN, NotGiven

from ..validation import validate_date_time, validate_required


class Attachment(BaseModel):
    """Typed representation of the `Attachment` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    filename: str
    """The filename of the attachment."""
    type: str
    """The MIME type of the attachment."""
    name: str | NotGiven = NOT_GIVEN
    """
    The name of the attachment.
     Format: attachments/{attachment}
    """
    create_time: datetime.datetime | NotGiven = Field(NOT_GIVEN, alias="createTime")
    """Output only. The creation timestamp."""
    content: str | NotGiven = NOT_GIVEN
    """Input only. The content of the attachment."""
    external_link: str | NotGiven = Field(NOT_GIVEN, alias="externalLink")
    """Optional. The external link of the attachment."""
    size: str | NotGiven = NOT_GIVEN
    """Output only. The size of the attachment in bytes."""
    memo: str | NotGiven = NOT_GIVEN
    """
    Optional. The related memo. Refer to `Memo.name`.
     Format: memos/{memo}
    """
    motion_media: MotionMedia | NotGiven = Field(NOT_GIVEN, alias="motionMedia")
    """Optional. Motion media metadata."""
    media_metadata: MediaMetadata | NotGiven = Field(NOT_GIVEN, alias="mediaMetadata")
    """Optional. Immutable normalized media metadata explicitly supplied by the client at creation time."""
    creator: str | NotGiven = NOT_GIVEN
    """
    Output only. The user who uploaded this attachment, which may differ from
     the creator of the linked memo. Format: users/{user}.
    """

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["filename", "type"])
        return value

    @field_validator("create_time", mode="before")
    @classmethod
    def _validate_create_time(cls, value):
        validate_date_time("createTime", value)
        return value


class Color(BaseModel):
    """
    Represents a color in the RGBA color space. This representation is designed
     for simplicity of conversion to/from color representations in various
     languages over compactness. For example, the fields of this representation
     can be trivially provided to the constructor of `java.awt.Color` in Java; it
     can also be trivially provided to UIColor's `+colorWithRed:green:blue:alpha`
     method in iOS; and, with just a little work, it can be easily formatted into
     a CSS `rgba()` string in JavaScript.

     This reference page doesn't carry information about the absolute color
     space
     that should be used to interpret the RGB value (e.g. sRGB, Adobe RGB,
     DCI-P3, BT.2020, etc.). By default, applications should assume the sRGB color
     space.

     When color equality needs to be decided, implementations, unless
     documented otherwise, treat two colors as equal if all their red,
     green, blue, and alpha values each differ by at most 1e-5.

     Example (Java):

          import com.google.type.Color;

          // ...
          public static java.awt.Color fromProto(Color protocolor) {
            float alpha = protocolor.hasAlpha()
                ? protocolor.getAlpha().getValue()
                : 1.0;

            return new java.awt.Color(
                protocolor.getRed(),
                protocolor.getGreen(),
                protocolor.getBlue(),
                alpha);
          }

          public static Color toProto(java.awt.Color color) {
            float red = (float) color.getRed();
            float green = (float) color.getGreen();
            float blue = (float) color.getBlue();
            float denominator = 255.0;
            Color.Builder resultBuilder =
                Color
                    .newBuilder()
                    .setRed(red / denominator)
                    .setGreen(green / denominator)
                    .setBlue(blue / denominator);
            int alpha = color.getAlpha();
            if (alpha != 255) {
              result.setAlpha(
                  FloatValue
                      .newBuilder()
                      .setValue(((float) alpha) / denominator)
                      .build());
            }
            return resultBuilder.build();
          }
          // ...

     Example (iOS / Obj-C):

          // ...
          static UIColor* fromProto(Color* protocolor) {
             float red = [protocolor red];
             float green = [protocolor green];
             float blue = [protocolor blue];
             FloatValue* alpha_wrapper = [protocolor alpha];
             float alpha = 1.0;
             if (alpha_wrapper != nil) {
               alpha = [alpha_wrapper value];
             }
             return [UIColor colorWithRed:red green:green blue:blue alpha:alpha];
          }

          static Color* toProto(UIColor* color) {
              CGFloat red, green, blue, alpha;
              if (![color getRed:&red green:&green blue:&blue alpha:&alpha]) {
                return nil;
              }
              Color* result = [[Color alloc] init];
              [result setRed:red];
              [result setGreen:green];
              [result setBlue:blue];
              if (alpha <= 0.9999) {
                [result setAlpha:floatWrapperWithValue(alpha)];
              }
              [result autorelease];
              return result;
         }
         // ...

      Example (JavaScript):

         // ...

         var protoToCssColor = function(rgb_color) {
            var redFrac = rgb_color.red || 0.0;
            var greenFrac = rgb_color.green || 0.0;
            var blueFrac = rgb_color.blue || 0.0;
            var red = Math.floor(redFrac * 255);
            var green = Math.floor(greenFrac * 255);
            var blue = Math.floor(blueFrac * 255);

            if (!('alpha' in rgb_color)) {
               return rgbToCssColor(red, green, blue);
            }

            var alphaFrac = rgb_color.alpha.value || 0.0;
            var rgbParams = [red, green, blue].join(',');
            return ['rgba(', rgbParams, ',', alphaFrac, ')'].join('');
         };

         var rgbToCssColor = function(red, green, blue) {
           var rgbNumber = new Number((red << 16) | (green << 8) | blue);
           var hexString = rgbNumber.toString(16);
           var missingZeros = 6 - hexString.length;
           var resultBuilder = ['#'];
           for (var i = 0; i < missingZeros; i++) {
              resultBuilder.push('0');
           }
           resultBuilder.push(hexString);
           return resultBuilder.join('');
         };

         // ...
    """

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    red: float | NotGiven = NOT_GIVEN
    """The amount of red in the color as a value in the interval [0, 1]."""
    green: float | NotGiven = NOT_GIVEN
    """The amount of green in the color as a value in the interval [0, 1]."""
    blue: float | NotGiven = NOT_GIVEN
    """The amount of blue in the color as a value in the interval [0, 1]."""
    alpha: float | NotGiven = NOT_GIVEN
    """
    The fraction of this color that should be applied to the pixel. That is,
     the final pixel color is defined by the equation:

       `pixel color = alpha * (this color) + (1.0 - alpha) * (background color)`

     This means that a value of 1.0 corresponds to a solid color, whereas
     a value of 0.0 corresponds to a completely transparent color. This
     uses a wrapper message rather than a simple float scalar so that it is
     possible to distinguish between a default value and the value being unset.
     If omitted, this color object is rendered as a solid color
     (as if the alpha value had been explicitly given a value of 1.0).
    """


class GoogleProtobufAny(BaseModel):
    """Contains an arbitrary serialized message along with a @type that describes the type of the serialized message."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    type: str | NotGiven = Field(NOT_GIVEN, alias="@type")
    """The type of the serialized message."""


class MediaCaptureTime(BaseModel):
    """Typed representation of the `MediaCaptureTime` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    local_date_time: str | NotGiven = Field(NOT_GIVEN, alias="localDateTime")
    """Optional `string` value serialized in the `localDateTime` wire field."""
    utc_offset: str | NotGiven = Field(NOT_GIVEN, alias="utcOffset")
    """Optional `string` value serialized in the `utcOffset` wire field."""


class MediaLocation(BaseModel):
    """Typed representation of the `MediaLocation` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    latitude: float | NotGiven = NOT_GIVEN
    """Optional `double`-formatted value serialized in the `latitude` wire field."""
    longitude: float | NotGiven = NOT_GIVEN
    """Optional `double`-formatted value serialized in the `longitude` wire field."""
    altitude_meters: float | NotGiven = Field(NOT_GIVEN, alias="altitudeMeters")
    """Optional `double`-formatted value serialized in the `altitudeMeters` wire field."""


class MediaMetadata(BaseModel):
    """Typed representation of the `MediaMetadata` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    width: int | NotGiven = NOT_GIVEN
    """Optional `int32`-formatted value serialized in the `width` wire field."""
    height: int | NotGiven = NOT_GIVEN
    """Optional `int32`-formatted value serialized in the `height` wire field."""
    photo: PhotoMetadata | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `photo` wire field."""
    video: VideoMetadata | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `video` wire field."""


class MotionMedia(BaseModel):
    """Typed representation of the `MotionMedia` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    family: (
        Literal["MOTION_MEDIA_FAMILY_UNSPECIFIED", "APPLE_LIVE_PHOTO", "ANDROID_MOTION_PHOTO"]
        | str
        | NotGiven
    ) = NOT_GIVEN
    """Optional enumerated value serialized in the `family` wire field."""
    role: (
        Literal["MOTION_MEDIA_ROLE_UNSPECIFIED", "STILL", "VIDEO", "CONTAINER"] | str | NotGiven
    ) = NOT_GIVEN
    """Optional enumerated value serialized in the `role` wire field."""
    group_id: str | NotGiven = Field(NOT_GIVEN, alias="groupId")
    """Optional `string` value serialized in the `groupId` wire field."""
    presentation_timestamp_us: str | NotGiven = Field(NOT_GIVEN, alias="presentationTimestampUs")
    """Optional `string` value serialized in the `presentationTimestampUs` wire field."""
    has_embedded_video: bool | NotGiven = Field(NOT_GIVEN, alias="hasEmbeddedVideo")
    """Optional `boolean` value serialized in the `hasEmbeddedVideo` wire field."""


class PhotoMetadata(BaseModel):
    """Typed representation of the `PhotoMetadata` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    capture_time: MediaCaptureTime | NotGiven = Field(NOT_GIVEN, alias="captureTime")
    """Optional object value serialized in the `captureTime` wire field."""
    location: MediaLocation | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `location` wire field."""
    source_exif_orientation: int | NotGiven = Field(NOT_GIVEN, alias="sourceExifOrientation")
    """Optional `int32`-formatted value serialized in the `sourceExifOrientation` wire field."""
    camera_make: str | NotGiven = Field(NOT_GIVEN, alias="cameraMake")
    """Optional `string` value serialized in the `cameraMake` wire field."""
    camera_model: str | NotGiven = Field(NOT_GIVEN, alias="cameraModel")
    """Optional `string` value serialized in the `cameraModel` wire field."""
    lens_model: str | NotGiven = Field(NOT_GIVEN, alias="lensModel")
    """Optional `string` value serialized in the `lensModel` wire field."""
    f_number: float | NotGiven = Field(NOT_GIVEN, alias="fNumber")
    """Optional `double`-formatted value serialized in the `fNumber` wire field."""
    exposure_time_seconds: float | NotGiven = Field(NOT_GIVEN, alias="exposureTimeSeconds")
    """Optional `double`-formatted value serialized in the `exposureTimeSeconds` wire field."""
    iso: int | NotGiven = NOT_GIVEN
    """Optional `int32`-formatted value serialized in the `iso` wire field."""
    focal_length_mm: float | NotGiven = Field(NOT_GIVEN, alias="focalLengthMm")
    """Optional `double`-formatted value serialized in the `focalLengthMm` wire field."""


class Space(BaseModel):
    """Space is a collaboration boundary for placed memos."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    title: str
    """Required. The human-readable title."""
    name: str | NotGiven = NOT_GIVEN
    """The resource name of the space. Format: spaces/{space}."""
    description: str | NotGiven = NOT_GIVEN
    """Optional. A description of the space."""
    current_user_role: Literal["ROLE_UNSPECIFIED", "ADMIN", "USER"] | str | NotGiven = Field(
        NOT_GIVEN, alias="currentUserRole"
    )
    """
    Output only. The authenticated user's membership role in this space.
     ROLE_UNSPECIFIED when this Space is exposed as metadata-only.
    """
    member_count: int | NotGiven = Field(NOT_GIVEN, alias="memberCount")
    """
    Output only. The number of accepted members in this space. Pending
     invitations are excluded. Zero when this Space is exposed as metadata-only.
    """
    icon: Space_Icon | NotGiven = NOT_GIVEN
    """
    Optional. Display icon. Omit when updating with the "icon" mask to reset
     to the default Space mark.
    """

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["title"])
        return value


class Space_Icon(BaseModel):
    """Typed representation of the `Space_Icon` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    emoji: str | NotGiven = NOT_GIVEN
    """A Unicode emoji sequence."""
    lucide: str | NotGiven = NOT_GIVEN
    """A canonical Lucide icon name, such as "leaf"."""


class Status(BaseModel):
    """The `Status` type defines a logical error model that is suitable for different programming environments, including REST APIs and RPC APIs. It is used by [gRPC](https://github.com/grpc). Each `Status` message contains three pieces of data: error code, error message, and error details. You can find out more about this error model and how to work with it in the [API Design Guide](https://cloud.google.com/apis/design/errors)."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    code: int | NotGiven = NOT_GIVEN
    """The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code]."""
    message: str | NotGiven = NOT_GIVEN
    """A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client."""
    details: list[GoogleProtobufAny] | NotGiven = NOT_GIVEN
    """A list of messages that carry the error details.  There is a common set of message types for APIs to use."""


class User(BaseModel):
    """Typed representation of the `User` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    role: Literal["ROLE_UNSPECIFIED", "ADMIN", "USER"] | str
    """The role of the user."""
    username: str
    """Required. The unique username for login."""
    state: Literal["STATE_UNSPECIFIED", "NORMAL", "ARCHIVED"] | str
    """The state of the user."""
    name: str | NotGiven = NOT_GIVEN
    """
    The resource name of the user.
     Format: users/{user}
    """
    email: str | NotGiven = NOT_GIVEN
    """
    Optional. The email address of the user. Stored trimmed and lowercased;
     empty means no address. An address belongs to at most one user on the
     instance, so writes that would reuse one fail with ALREADY_EXISTS.
    """
    display_name: str | NotGiven = Field(NOT_GIVEN, alias="displayName")
    """Optional. The display name of the user."""
    avatar_url: str | NotGiven = Field(NOT_GIVEN, alias="avatarUrl")
    """Optional. The avatar URL of the user."""
    description: str | NotGiven = NOT_GIVEN
    """Optional. The description of the user."""
    password: str | NotGiven = NOT_GIVEN
    """Input only. The password for the user."""
    create_time: datetime.datetime | NotGiven = Field(NOT_GIVEN, alias="createTime")
    """Output only. The creation timestamp."""
    update_time: datetime.datetime | NotGiven = Field(NOT_GIVEN, alias="updateTime")
    """Output only. The last update timestamp."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["role", "username", "state"])
        return value

    @field_validator("create_time", mode="before")
    @classmethod
    def _validate_create_time(cls, value):
        validate_date_time("createTime", value)
        return value

    @field_validator("update_time", mode="before")
    @classmethod
    def _validate_update_time(cls, value):
        validate_date_time("updateTime", value)
        return value


class VideoMetadata(BaseModel):
    """Typed representation of the `VideoMetadata` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    duration_seconds: float | NotGiven = Field(NOT_GIVEN, alias="durationSeconds")
    """Optional `double`-formatted value serialized in the `durationSeconds` wire field."""
