# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

from memos_unofficial_sdk.client import NOT_GIVEN, NotGiven
from memos_unofficial_sdk.types.shared import Space

from ..validation import validate_required


class AcceptSpaceInvitationRequest(BaseModel):
    """Typed representation of the `AcceptSpaceInvitationRequest` API schema."""

    name: str
    """Required. Format: spaces/{space}/invitations/{username}."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["name"])
        return value


class DeclineSpaceInvitationRequest(BaseModel):
    """Typed representation of the `DeclineSpaceInvitationRequest` API schema."""

    name: str
    """Required. Format: spaces/{space}/invitations/{username}."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["name"])
        return value


class ListSpaceInvitationsResponse(BaseModel):
    """Typed representation of the `ListSpaceInvitationsResponse` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    space_invitations: list[SpaceInvitation] | NotGiven = Field(NOT_GIVEN, alias="spaceInvitations")
    """Optional array value serialized in the `spaceInvitations` wire field."""
    next_page_token: str | NotGiven = Field(NOT_GIVEN, alias="nextPageToken")
    """Optional `string` value serialized in the `nextPageToken` wire field."""


class ListSpaceMembersResponse(BaseModel):
    """Typed representation of the `ListSpaceMembersResponse` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    space_members: list[SpaceMember] | NotGiven = Field(NOT_GIVEN, alias="spaceMembers")
    """Optional array value serialized in the `spaceMembers` wire field."""
    next_page_token: str | NotGiven = Field(NOT_GIVEN, alias="nextPageToken")
    """Optional `string` value serialized in the `nextPageToken` wire field."""


class ListSpacesResponse(BaseModel):
    """Typed representation of the `ListSpacesResponse` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    spaces: list[Space] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `spaces` wire field."""
    next_page_token: str | NotGiven = Field(NOT_GIVEN, alias="nextPageToken")
    """Optional `string` value serialized in the `nextPageToken` wire field."""


class ListUserSpaceInvitationsResponse(BaseModel):
    """Typed representation of the `ListUserSpaceInvitationsResponse` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    space_invitations: list[SpaceInvitation] | NotGiven = Field(NOT_GIVEN, alias="spaceInvitations")
    """Optional array value serialized in the `spaceInvitations` wire field."""
    next_page_token: str | NotGiven = Field(NOT_GIVEN, alias="nextPageToken")
    """Optional `string` value serialized in the `nextPageToken` wire field."""


class SpaceInvitation(BaseModel):
    """SpaceInvitation is a pending invitation for an existing user to join a space."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    invitee: str
    """Required. The invited user. Format: users/{username}."""
    role: Literal["ROLE_UNSPECIFIED", "ADMIN", "USER"] | str
    """Required. The role the user will receive after accepting the invitation."""
    name: str | NotGiven = NOT_GIVEN
    """The resource name. Format: spaces/{space}/invitations/{username}."""
    space: Space | NotGiven = NOT_GIVEN
    """
    Output only. The Space the user is invited to. This lets an invitee
     understand the invitation without granting membership-based GetSpace access.
    """

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["invitee", "role"])
        return value


class SpaceMember(BaseModel):
    """SpaceMember is a user's membership and governance role in a space."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    user: str
    """Required. The member user. Format: users/{username}."""
    role: Literal["ROLE_UNSPECIFIED", "ADMIN", "USER"] | str
    """Required. The member's role within this space."""
    name: str | NotGiven = NOT_GIVEN
    """The resource name. Format: spaces/{space}/members/{username}."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["user", "role"])
        return value
