# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator

from memos_unofficial_sdk.client import NOT_GIVEN, NotGiven
from memos_unofficial_sdk.types.shared import Color, Space, User

from ..validation import validate_date_time


class UserNotification(BaseModel):
    """Typed representation of the `UserNotification` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    name: str | NotGiven = NOT_GIVEN
    """
    The resource name of the notification.
     Format: users/{user}/notifications/{notification}
    """
    sender: str | NotGiven = NOT_GIVEN
    """
    The sender of the notification.
     Format: users/{user}
    """
    sender_user: User | NotGiven = Field(NOT_GIVEN, alias="senderUser")
    """The sender user details."""
    status: Literal["STATUS_UNSPECIFIED", "UNREAD", "ARCHIVED"] | str | NotGiven = NOT_GIVEN
    """The status of the notification."""
    create_time: datetime.datetime | NotGiven = Field(NOT_GIVEN, alias="createTime")
    """The creation timestamp."""
    type: (
        Literal["TYPE_UNSPECIFIED", "MEMO_COMMENT", "MEMO_MENTION", "SPACE_INVITATION"]
        | str
        | NotGiven
    ) = NOT_GIVEN
    """The type of the notification."""
    memo_comment: UserNotification_MemoCommentPayload | NotGiven = Field(
        NOT_GIVEN, alias="memoComment"
    )
    """Optional API value serialized in the `memoComment` wire field."""
    memo_mention: UserNotification_MemoMentionPayload | NotGiven = Field(
        NOT_GIVEN, alias="memoMention"
    )
    """Optional API value serialized in the `memoMention` wire field."""
    space_invitation: UserNotification_SpaceInvitationPayload | NotGiven = Field(
        NOT_GIVEN, alias="spaceInvitation"
    )
    """Optional API value serialized in the `spaceInvitation` wire field."""

    @field_validator("create_time", mode="before")
    @classmethod
    def _validate_create_time(cls, value):
        validate_date_time("createTime", value)
        return value


class UserNotification_MemoCommentPayload(BaseModel):
    """Typed representation of the `UserNotification_MemoCommentPayload` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    memo: str | NotGiven = NOT_GIVEN
    """
    The memo name of comment.
     Format: memos/{memo}
    """
    related_memo: str | NotGiven = Field(NOT_GIVEN, alias="relatedMemo")
    """
    The name of related memo.
     Format: memos/{memo}
    """
    memo_snippet: str | NotGiven = Field(NOT_GIVEN, alias="memoSnippet")
    """Preview text of the comment memo."""
    related_memo_snippet: str | NotGiven = Field(NOT_GIVEN, alias="relatedMemoSnippet")
    """Preview text of the related memo."""


class UserNotification_MemoMentionPayload(BaseModel):
    """Typed representation of the `UserNotification_MemoMentionPayload` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    memo: str | NotGiven = NOT_GIVEN
    """
    The memo that contains the mention.
     Format: memos/{memo}
    """
    related_memo: str | NotGiven = Field(NOT_GIVEN, alias="relatedMemo")
    """
    The related parent memo when the mention was created in a comment.
     Format: memos/{memo}
    """
    memo_snippet: str | NotGiven = Field(NOT_GIVEN, alias="memoSnippet")
    """Preview text of the memo that contains the mention."""
    related_memo_snippet: str | NotGiven = Field(NOT_GIVEN, alias="relatedMemoSnippet")
    """Preview text of the related parent memo."""


class UserNotification_SpaceInvitationPayload(BaseModel):
    """Typed representation of the `UserNotification_SpaceInvitationPayload` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    space_invitation: str | NotGiven = Field(NOT_GIVEN, alias="spaceInvitation")
    """
    The invitation resource.
     Format: spaces/{space}/invitations/{username}
    """
    space: Space | NotGiven = NOT_GIVEN
    """The read-only Space summary carried by the invitation."""
    role: Literal["ROLE_UNSPECIFIED", "ADMIN", "USER"] | str | NotGiven = NOT_GIVEN
    """The role the invitation offers."""
    state: Literal["STATE_UNSPECIFIED", "PENDING", "ACCEPTED"] | str | NotGiven = NOT_GIVEN
    """The current state of the invitation for the receiver."""


class UserSetting(BaseModel):
    """User settings message"""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    name: str | NotGiven = NOT_GIVEN
    """
    The name of the user setting.
     Format: users/{user}/settings/{setting}, {setting} is the key for the setting.
     For example, "users/steven/settings/GENERAL" for general settings.
    """
    general_setting: UserSetting_GeneralSetting | NotGiven = Field(
        NOT_GIVEN, alias="generalSetting"
    )
    """General user settings configuration."""
    webhooks_setting: UserSetting_WebhooksSetting | NotGiven = Field(
        NOT_GIVEN, alias="webhooksSetting"
    )
    """User webhooks configuration."""
    tags_setting: UserSetting_TagsSetting | NotGiven = Field(NOT_GIVEN, alias="tagsSetting")
    """User-specific tag metadata."""


class UserSetting_GeneralSetting(BaseModel):
    """General user settings configuration."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    locale: str | NotGiven = NOT_GIVEN
    """The preferred locale of the user."""
    memo_visibility: str | NotGiven = Field(NOT_GIVEN, alias="memoVisibility")
    """The default visibility of the memo."""
    theme: str | NotGiven = NOT_GIVEN
    """
    The preferred theme of the user.
     This references a CSS file in the web/public/themes/ directory.
     If not set, the default theme will be used.
    """
    save_media_metadata: bool | NotGiven = Field(NOT_GIVEN, alias="saveMediaMetadata")
    """Whether the official client should save metadata from future media uploads."""


class UserSetting_TagMetadata(BaseModel):
    """Tag metadata for user-specific display rules."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    background_color: Color | NotGiven = Field(NOT_GIVEN, alias="backgroundColor")
    """
    Optional background color for the tag label.
     When unset, the default tag color is used.
    """
    blur_content: bool | NotGiven = Field(NOT_GIVEN, alias="blurContent")
    """Whether memos with this tag should have their content blurred."""


class UserSetting_TagsSetting(BaseModel):
    """User-specific tag metadata."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    tags: dict[str, UserSetting_TagMetadata] | NotGiven = NOT_GIVEN
    """
    Map of tag name pattern to tag metadata.
     Each key is treated as an anchored regular expression (^pattern$).
    """


class UserSetting_WebhooksSetting(BaseModel):
    """User webhooks configuration."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    webhooks: list[UserWebhook] | NotGiven = NOT_GIVEN
    """List of user webhooks."""


class UserStats(BaseModel):
    """User statistics messages"""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    name: str | NotGiven = NOT_GIVEN
    """
    The resource name of the user statistics singleton.
     Format: users/{user}/stats
    """
    memo_type_stats: UserStats_MemoTypeStats | NotGiven = Field(NOT_GIVEN, alias="memoTypeStats")
    """The stats of memo types."""
    tag_count: dict[str, int] | NotGiven = Field(NOT_GIVEN, alias="tagCount")
    """The count of tags."""
    memo_created_timestamps: list[datetime.datetime] | NotGiven = Field(
        NOT_GIVEN, alias="memoCreatedTimestamps"
    )
    """The creation timestamps of the user's memos."""
    memo_updated_timestamps: list[datetime.datetime] | NotGiven = Field(
        NOT_GIVEN, alias="memoUpdatedTimestamps"
    )
    """
    The latest update timestamps of the user's memos (one per memo,
     mirrors memo_created_timestamps). Used by the activity heatmap when
     the client's view is set to update_time basis.
    """
    pinned_memos: list[str] | NotGiven = Field(NOT_GIVEN, alias="pinnedMemos")
    """The pinned memos of the user."""
    total_memo_count: int | NotGiven = Field(NOT_GIVEN, alias="totalMemoCount")
    """Total memo count."""
    attachment_storage_bytes: str | NotGiven = Field(NOT_GIVEN, alias="attachmentStorageBytes")
    """
    Total persisted attachment size in bytes, including unlinked uploads and
     attachments in all spaces. Excludes temporary uploads and derived files.
     Returned only by GetUserStats for the authenticated user's own stats,
     independently of the request's memo filter.
    """


class UserStats_MemoTypeStats(BaseModel):
    """Memo type statistics."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    link_count: int | NotGiven = Field(NOT_GIVEN, alias="linkCount")
    """Optional `int32`-formatted value serialized in the `linkCount` wire field."""
    code_count: int | NotGiven = Field(NOT_GIVEN, alias="codeCount")
    """Optional `int32`-formatted value serialized in the `codeCount` wire field."""
    todo_count: int | NotGiven = Field(NOT_GIVEN, alias="todoCount")
    """Optional `int32`-formatted value serialized in the `todoCount` wire field."""
    undo_count: int | NotGiven = Field(NOT_GIVEN, alias="undoCount")
    """Optional `int32`-formatted value serialized in the `undoCount` wire field."""


class UserWebhook(BaseModel):
    """UserWebhook represents a webhook owned by a user."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    name: str | NotGiven = NOT_GIVEN
    """
    The name of the webhook.
     Format: users/{user}/webhooks/{webhook}
    """
    url: str | NotGiven = NOT_GIVEN
    """The URL to send the webhook to."""
    display_name: str | NotGiven = Field(NOT_GIVEN, alias="displayName")
    """Optional. Human-readable name for the webhook."""
    create_time: datetime.datetime | NotGiven = Field(NOT_GIVEN, alias="createTime")
    """The creation time of the webhook."""
    update_time: datetime.datetime | NotGiven = Field(NOT_GIVEN, alias="updateTime")
    """The last update time of the webhook."""
    signing_secret: str | NotGiven = Field(NOT_GIVEN, alias="signingSecret")
    """
    Optional. Signing secret used to HMAC-SHA256 sign the webhook request body.
     This field is input-only; it is never returned in responses.
    """
    signing_secret_set: bool | NotGiven = Field(NOT_GIVEN, alias="signingSecretSet")
    """Whether a signing secret is configured for this webhook."""

    @field_validator("create_time", mode="before")
    @classmethod
    def _validate_create_time(cls, value):
        validate_date_time("createTime", value)
        return value

    @field_validator("update_time", mode="before")
    @classmethod
    def _validate_update_time(cls, value):
        validate_date_time("updateTime", value)
        return value
