# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

import importlib

from .user_service_part001 import (
    BatchGetUsersRequest,
    BatchGetUsersResponse,
    CreateLinkedIdentityRequest,
    CreatePersonalAccessTokenRequest,
    CreatePersonalAccessTokenResponse,
    GetUserWebhookSigningSecretResponse,
    ImportMemosRequest,
    ImportMemosResponse,
    ImportMemosSpec,
    LinkedIdentity,
    ListAllUserStatsResponse,
    ListLinkedIdentitiesResponse,
    ListMemoViewsResponse,
    ListPersonalAccessTokensResponse,
    ListUserNotificationsResponse,
    ListUserSettingsResponse,
    ListUsersResponse,
    ListUserWebhooksResponse,
    MemoImportIssue,
    MemoImportPlan,
    MemoImportReport,
    MemoView,
    MemoView_Icon,
    PersonalAccessToken,
)
from .user_service_part002 import (
    UserNotification,
    UserNotification_MemoCommentPayload,
    UserNotification_MemoMentionPayload,
    UserNotification_SpaceInvitationPayload,
    UserSetting,
    UserSetting_GeneralSetting,
    UserSetting_TagMetadata,
    UserSetting_TagsSetting,
    UserSetting_WebhooksSetting,
    UserStats,
    UserStats_MemoTypeStats,
    UserWebhook,
)

__all__ = [
    "BatchGetUsersRequest",
    "BatchGetUsersResponse",
    "CreateLinkedIdentityRequest",
    "CreatePersonalAccessTokenRequest",
    "CreatePersonalAccessTokenResponse",
    "GetUserWebhookSigningSecretResponse",
    "ImportMemosRequest",
    "ImportMemosResponse",
    "ImportMemosSpec",
    "LinkedIdentity",
    "ListAllUserStatsResponse",
    "ListLinkedIdentitiesResponse",
    "ListMemoViewsResponse",
    "ListPersonalAccessTokensResponse",
    "ListUserNotificationsResponse",
    "ListUserSettingsResponse",
    "ListUserWebhooksResponse",
    "ListUsersResponse",
    "MemoImportIssue",
    "MemoImportPlan",
    "MemoImportReport",
    "MemoView",
    "MemoView_Icon",
    "PersonalAccessToken",
    "UserNotification",
    "UserNotification_MemoCommentPayload",
    "UserNotification_MemoMentionPayload",
    "UserNotification_SpaceInvitationPayload",
    "UserSetting",
    "UserSetting_GeneralSetting",
    "UserSetting_TagMetadata",
    "UserSetting_TagsSetting",
    "UserSetting_WebhooksSetting",
    "UserStats",
    "UserStats_MemoTypeStats",
    "UserWebhook",
]

# Forward references deferred to TYPE_CHECKING in the parts above are
# resolvable now that every part is loaded.
_user_service_part001 = importlib.import_module(".user_service_part001", __package__)

_deferred_user_service_part001: tuple[tuple[str, object], ...] = (
    ("UserNotification", UserNotification),
    ("UserSetting", UserSetting),
    ("UserStats", UserStats),
    ("UserWebhook", UserWebhook),
)
for _name, _value in _deferred_user_service_part001:
    setattr(_user_service_part001, _name, _value)

BatchGetUsersRequest.model_rebuild()
BatchGetUsersResponse.model_rebuild()
CreateLinkedIdentityRequest.model_rebuild()
CreatePersonalAccessTokenRequest.model_rebuild()
CreatePersonalAccessTokenResponse.model_rebuild()
GetUserWebhookSigningSecretResponse.model_rebuild()
ImportMemosRequest.model_rebuild()
ImportMemosResponse.model_rebuild()
ImportMemosSpec.model_rebuild()
LinkedIdentity.model_rebuild()
ListAllUserStatsResponse.model_rebuild()
ListLinkedIdentitiesResponse.model_rebuild()
ListMemoViewsResponse.model_rebuild()
ListPersonalAccessTokensResponse.model_rebuild()
ListUserNotificationsResponse.model_rebuild()
ListUserSettingsResponse.model_rebuild()
ListUserWebhooksResponse.model_rebuild()
ListUsersResponse.model_rebuild()
MemoImportIssue.model_rebuild()
MemoImportPlan.model_rebuild()
MemoImportReport.model_rebuild()
MemoView.model_rebuild()
MemoView_Icon.model_rebuild()
PersonalAccessToken.model_rebuild()
