# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime
from typing import TYPE_CHECKING, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from memos_unofficial_sdk.client import NOT_GIVEN, NotGiven
from memos_unofficial_sdk.types.shared import User

from ..validation import validate_date_time, validate_required

if TYPE_CHECKING:
    from memos_unofficial_sdk.types.user_service_part002 import (
        UserNotification,
        UserSetting,
        UserStats,
        UserWebhook,
    )


class BatchGetUsersRequest(BaseModel):
    """Typed representation of the `BatchGetUsersRequest` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    usernames: list[str] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `usernames` wire field."""


class BatchGetUsersResponse(BaseModel):
    """Typed representation of the `BatchGetUsersResponse` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    users: list[User] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `users` wire field."""


class CreateLinkedIdentityRequest(BaseModel):
    """Typed representation of the `CreateLinkedIdentityRequest` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    parent: str
    """
    Required. The parent user who owns the linked identity.
     Format: users/{user}
    """
    idp_name: str = Field(alias="idpName")
    """
    Required. The identity provider to link.
     Format: identity-providers/{idp}
    """
    code: str
    """Required. The authorization code from the identity provider."""
    redirect_uri: str = Field(alias="redirectUri")
    """Required. The redirect URI used in the OAuth flow."""
    code_verifier: str | NotGiven = Field(NOT_GIVEN, alias="codeVerifier")
    """Optional. The PKCE code verifier used in the OAuth flow."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(
            value,
            ["parent", "idpName", "code", "redirectUri"],
            {"idpName": "idp_name", "redirectUri": "redirect_uri"},
        )
        return value


class CreatePersonalAccessTokenRequest(BaseModel):
    """Typed representation of the `CreatePersonalAccessTokenRequest` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    parent: str
    """
    Required. The parent resource where this token will be created.
     Format: users/{user}
    """
    description: str | NotGiven = NOT_GIVEN
    """Optional. Description of the personal access token."""
    expires_in_days: int | NotGiven = Field(NOT_GIVEN, alias="expiresInDays")
    """Optional. Expiration duration in days (0 = never expires)."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["parent"])
        return value


class CreatePersonalAccessTokenResponse(BaseModel):
    """Typed representation of the `CreatePersonalAccessTokenResponse` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    personal_access_token: PersonalAccessToken | NotGiven = Field(
        NOT_GIVEN, alias="personalAccessToken"
    )
    """The personal access token metadata."""
    token: str | NotGiven = NOT_GIVEN
    """
    The actual token value - only returned on creation.
     This is the only time the token value will be visible.
    """


class GetUserWebhookSigningSecretResponse(BaseModel):
    """Typed representation of the `GetUserWebhookSigningSecretResponse` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    signing_secret: str | NotGiven = Field(NOT_GIVEN, alias="signingSecret")
    """The signing secret, in the Standard Webhooks "whsec_<base64>" form."""


class ImportMemosRequest(BaseModel):
    """Typed representation of the `ImportMemosRequest` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    name: str
    """
    Required. The user who receives the memos. Must be the caller.
     Format: users/{user}
    """
    write_offset: str = Field(alias="writeOffset")
    """
    Required. Zero-based byte offset at which data is written. Must equal the
     committed size, except when retrying the most recently accepted chunk
     with identical bytes and offset, which is accepted without writing again.
    """
    spec: ImportMemosSpec | NotGiven = NOT_GIVEN
    """Starts a new upload. The same call may also carry data and finish_write."""
    upload_id: str | NotGiven = Field(NOT_GIVEN, alias="uploadId")
    """Continues the upload identified by a previous response."""
    data: str | NotGiven = NOT_GIVEN
    """
    Optional. Archive bytes, at most max_chunk_size long. With no data and
     finish_write false, the call reports progress without writing, and
     write_offset is ignored.
    """
    finish_write: bool | NotGiven = Field(NOT_GIVEN, alias="finishWrite")
    """
    Optional. Finish the upload after writing data. The committed size must
     then equal total_size. The archive is validated and, unless
     validate_only is set, imported. Any later call for an imported upload
     returns the same report.
    """
    validate_only: bool | NotGiven = Field(NOT_GIVEN, alias="validateOnly")
    """
    Optional. On a finishing call, validate the archive and return the plan
     without importing. The upload stays staged so a later finishing call can
     import it.
    """
    conflict_policy: (
        Literal["CONFLICT_POLICY_UNSPECIFIED", "SKIP", "REPLACE", "DUPLICATE"] | str | NotGiven
    ) = Field(NOT_GIVEN, alias="conflictPolicy")
    """Optional. Read on the finishing call that imports. Unspecified means SKIP."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["name", "writeOffset"], {"writeOffset": "write_offset"})
        return value


class ImportMemosResponse(BaseModel):
    """Typed representation of the `ImportMemosResponse` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    upload_id: str | NotGiven = Field(NOT_GIVEN, alias="uploadId")
    """Opaque ID for subsequent calls. This is not a resource name."""
    committed_size: str | NotGiven = Field(NOT_GIVEN, alias="committedSize")
    """Number of archive bytes committed so far."""
    max_chunk_size: int | NotGiven = Field(NOT_GIVEN, alias="maxChunkSize")
    """Maximum number of data bytes accepted in one call."""
    plan: MemoImportPlan | NotGiven = NOT_GIVEN
    """What the import would do. Set by a finishing call with validate_only."""
    report: MemoImportReport | NotGiven = NOT_GIVEN
    """What the import did. Set by a finishing call that imported."""


class ImportMemosSpec(BaseModel):
    """Typed representation of the `ImportMemosSpec` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    total_size: str | NotGiven = Field(NOT_GIVEN, alias="totalSize")
    """Optional. Total size of the archive in bytes."""


class LinkedIdentity(BaseModel):
    """LinkedIdentity represents an SSO identity linked to a user account."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    name: str | NotGiven = NOT_GIVEN
    """
    The resource name of the linked identity.
     Format: users/{user}/linkedIdentities/{linked_identity}
    """
    idp_name: str | NotGiven = Field(NOT_GIVEN, alias="idpName")
    """
    The resource name of the identity provider.
     Format: identity-providers/{idp}
    """
    extern_uid: str | NotGiven = Field(NOT_GIVEN, alias="externUid")
    """The external user identifier from the identity provider."""


class ListAllUserStatsResponse(BaseModel):
    """Typed representation of the `ListAllUserStatsResponse` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    stats: list[UserStats] | NotGiven = NOT_GIVEN
    """The list of user statistics."""


class ListLinkedIdentitiesResponse(BaseModel):
    """Typed representation of the `ListLinkedIdentitiesResponse` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    linked_identities: list[LinkedIdentity] | NotGiven = Field(NOT_GIVEN, alias="linkedIdentities")
    """The list of linked identities."""


class ListMemoViewsResponse(BaseModel):
    """Typed representation of the `ListMemoViewsResponse` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    memo_views: list[MemoView] | NotGiven = Field(NOT_GIVEN, alias="memoViews")
    """The list of memo views."""


class ListPersonalAccessTokensResponse(BaseModel):
    """Typed representation of the `ListPersonalAccessTokensResponse` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    personal_access_tokens: list[PersonalAccessToken] | NotGiven = Field(
        NOT_GIVEN, alias="personalAccessTokens"
    )
    """The list of personal access tokens."""
    next_page_token: str | NotGiven = Field(NOT_GIVEN, alias="nextPageToken")
    """A token for the next page of results."""


class ListUserNotificationsResponse(BaseModel):
    """Typed representation of the `ListUserNotificationsResponse` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    notifications: list[UserNotification] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `notifications` wire field."""
    next_page_token: str | NotGiven = Field(NOT_GIVEN, alias="nextPageToken")
    """Optional `string` value serialized in the `nextPageToken` wire field."""


class ListUserSettingsResponse(BaseModel):
    """Response message for ListUserSettings method."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    settings: list[UserSetting] | NotGiven = NOT_GIVEN
    """The list of user settings."""
    next_page_token: str | NotGiven = Field(NOT_GIVEN, alias="nextPageToken")
    """
    A token that can be sent as `page_token` to retrieve the next page.
     If this field is omitted, there are no subsequent pages.
    """


class ListUserWebhooksResponse(BaseModel):
    """Typed representation of the `ListUserWebhooksResponse` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    webhooks: list[UserWebhook] | NotGiven = NOT_GIVEN
    """The list of webhooks."""


class ListUsersResponse(BaseModel):
    """Typed representation of the `ListUsersResponse` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    users: list[User] | NotGiven = NOT_GIVEN
    """The list of users."""
    next_page_token: str | NotGiven = Field(NOT_GIVEN, alias="nextPageToken")
    """
    A token that can be sent as `page_token` to retrieve the next page.
     If this field is omitted, there are no subsequent pages.
    """


class MemoImportIssue(BaseModel):
    """
    MemoImportIssue is one warning or failure of an import, tied to the memo
     UID from the archive when there is one.
    """

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    memo: str | NotGiven = NOT_GIVEN
    """The archive memo UID the issue concerns, if any."""
    message: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `message` wire field."""


class MemoImportPlan(BaseModel):
    """MemoImportPlan describes what importing a staged archive would do."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    export_time: datetime.datetime | NotGiven = Field(NOT_GIVEN, alias="exportTime")
    """When the archive was written."""
    exporter: str | NotGiven = NOT_GIVEN
    """Username of the user who exported the archive."""
    generator: str | NotGiven = NOT_GIVEN
    """The software that wrote the archive."""
    memos: int | NotGiven = NOT_GIVEN
    """Number of memo records in the archive."""
    attachments: int | NotGiven = NOT_GIVEN
    """Number of attachment files in the archive."""
    new: int | NotGiven = NOT_GIVEN
    """Memos whose UID nobody on the instance holds."""
    existing: int | NotGiven = NOT_GIVEN
    """Memos the user already holds; the conflict policy applies to them."""
    renamed: int | NotGiven = NOT_GIVEN
    """Memos whose UID another account holds; they are imported under fresh UIDs."""
    warnings: list[MemoImportIssue] | NotGiven = NOT_GIVEN
    """Deviations the archive reader corrected while validating."""

    @field_validator("export_time", mode="before")
    @classmethod
    def _validate_export_time(cls, value):
        validate_date_time("exportTime", value)
        return value


class MemoImportReport(BaseModel):
    """MemoImportReport is the outcome of an import."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    created: int | NotGiven = NOT_GIVEN
    """Optional `int32`-formatted value serialized in the `created` wire field."""
    updated: int | NotGiven = NOT_GIVEN
    """Optional `int32`-formatted value serialized in the `updated` wire field."""
    skipped: int | NotGiven = NOT_GIVEN
    """Optional `int32`-formatted value serialized in the `skipped` wire field."""
    failed: int | NotGiven = NOT_GIVEN
    """Optional `int32`-formatted value serialized in the `failed` wire field."""
    warnings: list[MemoImportIssue] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `warnings` wire field."""
    failures: list[MemoImportIssue] | NotGiven = NOT_GIVEN
    """One entry per failed memo, with the reason."""


class MemoView(BaseModel):
    """Saved memo view messages"""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    title: str
    """The title of the memo view."""
    filter: str
    """
    The CEL filter expression for the memo view, using the same grammar as the
     ListMemos `filter` argument. Reuse it by passing this value to ListMemos.
    """
    name: str | NotGiven = NOT_GIVEN
    """
    The resource name of the memo view.
     Format: users/{user}/views/{view}
    """
    icon: MemoView_Icon | NotGiven = NOT_GIVEN
    """
    Optional. Display icon. Omit when updating with the "icon" mask to reset
     to the default view icon.
    """

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["title", "filter"])
        return value


class MemoView_Icon(BaseModel):
    """Typed representation of the `MemoView_Icon` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    emoji: str | NotGiven = NOT_GIVEN
    """A Unicode emoji sequence."""
    lucide: str | NotGiven = NOT_GIVEN
    """A canonical Lucide icon name, such as "leaf"."""


class PersonalAccessToken(BaseModel):
    """
    PersonalAccessToken represents a long-lived token for API/script access.
     PATs are distinct from short-lived JWT access tokens used for session authentication.
    """

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    name: str | NotGiven = NOT_GIVEN
    """
    The resource name of the personal access token.
     Format: users/{user}/personalAccessTokens/{personal_access_token}
    """
    description: str | NotGiven = NOT_GIVEN
    """The description of the token."""
    created_at: datetime.datetime | NotGiven = Field(NOT_GIVEN, alias="createdAt")
    """Output only. The creation timestamp."""
    expires_at: datetime.datetime | NotGiven = Field(NOT_GIVEN, alias="expiresAt")
    """Optional. The expiration timestamp."""
    last_used_at: datetime.datetime | NotGiven = Field(NOT_GIVEN, alias="lastUsedAt")
    """Output only. The last used timestamp."""

    @field_validator("created_at", mode="before")
    @classmethod
    def _validate_created_at(cls, value):
        validate_date_time("createdAt", value)
        return value

    @field_validator("expires_at", mode="before")
    @classmethod
    def _validate_expires_at(cls, value):
        validate_date_time("expiresAt", value)
        return value

    @field_validator("last_used_at", mode="before")
    @classmethod
    def _validate_last_used_at(cls, value):
        validate_date_time("lastUsedAt", value)
        return value
