# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

WIRE_SCHEMAS_PART_3: dict[str, tuple[Any, dict[str, tuple[str, str | None]]]] = {
    "TranscriptionAudio": (
        None,
        {
            "content": ("content", None),
            "uri": ("uri", None),
            "filename": ("filename", None),
            "content_type": ("contentType", None),
        },
    ),
    "UploadAttachmentRequest": (
        None,
        {
            "spec": ("spec", "UploadAttachmentSpec"),
            "upload_id": ("uploadId", None),
            "write_offset": ("writeOffset", None),
            "data": ("data", None),
            "finish_write": ("finishWrite", None),
        },
    ),
    "UploadAttachmentResponse": (
        None,
        {
            "upload_id": ("uploadId", None),
            "committed_size": ("committedSize", None),
            "attachment": ("attachment", "Attachment"),
            "max_chunk_size": ("maxChunkSize", None),
        },
    ),
    "UploadAttachmentSpec": (
        None,
        {
            "attachment": ("attachment", "Attachment"),
            "attachment_id": ("attachmentId", None),
            "total_size": ("totalSize", None),
        },
    ),
    "UpsertMemoReactionRequest": (
        None,
        {
            "name": ("name", None),
            "reaction": ("reaction", "Reaction"),
        },
    ),
    "User": (
        None,
        {
            "name": ("name", None),
            "role": ("role", None),
            "username": ("username", None),
            "email": ("email", None),
            "display_name": ("displayName", None),
            "avatar_url": ("avatarUrl", None),
            "description": ("description", None),
            "password": ("password", None),
            "state": ("state", None),
            "create_time": ("createTime", None),
            "update_time": ("updateTime", None),
        },
    ),
    "UserNotification": (
        None,
        {
            "name": ("name", None),
            "sender": ("sender", None),
            "sender_user": ("senderUser", "User"),
            "status": ("status", None),
            "create_time": ("createTime", None),
            "type": ("type", None),
            "memo_comment": ("memoComment", "UserNotification_MemoCommentPayload"),
            "memo_mention": ("memoMention", "UserNotification_MemoMentionPayload"),
            "space_invitation": ("spaceInvitation", "UserNotification_SpaceInvitationPayload"),
        },
    ),
    "UserNotification_MemoCommentPayload": (
        None,
        {
            "memo": ("memo", None),
            "related_memo": ("relatedMemo", None),
            "memo_snippet": ("memoSnippet", None),
            "related_memo_snippet": ("relatedMemoSnippet", None),
        },
    ),
    "UserNotification_MemoMentionPayload": (
        None,
        {
            "memo": ("memo", None),
            "related_memo": ("relatedMemo", None),
            "memo_snippet": ("memoSnippet", None),
            "related_memo_snippet": ("relatedMemoSnippet", None),
        },
    ),
    "UserNotification_SpaceInvitationPayload": (
        None,
        {
            "space_invitation": ("spaceInvitation", None),
            "space": ("space", "Space"),
            "role": ("role", None),
            "state": ("state", None),
        },
    ),
    "UserSetting": (
        None,
        {
            "name": ("name", None),
            "general_setting": ("generalSetting", "UserSetting_GeneralSetting"),
            "webhooks_setting": ("webhooksSetting", "UserSetting_WebhooksSetting"),
            "tags_setting": ("tagsSetting", "UserSetting_TagsSetting"),
        },
    ),
    "UserSetting_GeneralSetting": (
        None,
        {
            "locale": ("locale", None),
            "memo_visibility": ("memoVisibility", None),
            "theme": ("theme", None),
            "save_media_metadata": ("saveMediaMetadata", None),
        },
    ),
    "UserSetting_TagMetadata": (
        None,
        {
            "background_color": ("backgroundColor", "Color"),
            "blur_content": ("blurContent", None),
        },
    ),
    "UserSetting_TagsSetting": (
        None,
        {
            "tags": ("tags", "map:UserSetting_TagMetadata"),
        },
    ),
    "UserSetting_WebhooksSetting": (
        None,
        {
            "webhooks": ("webhooks", "UserWebhook"),
        },
    ),
    "UserStats": (
        None,
        {
            "name": ("name", None),
            "memo_type_stats": ("memoTypeStats", "UserStats_MemoTypeStats"),
            "tag_count": ("tagCount", None),
            "memo_created_timestamps": ("memoCreatedTimestamps", None),
            "memo_updated_timestamps": ("memoUpdatedTimestamps", None),
            "pinned_memos": ("pinnedMemos", None),
            "total_memo_count": ("totalMemoCount", None),
            "attachment_storage_bytes": ("attachmentStorageBytes", None),
        },
    ),
    "UserStats_MemoTypeStats": (
        None,
        {
            "link_count": ("linkCount", None),
            "code_count": ("codeCount", None),
            "todo_count": ("todoCount", None),
            "undo_count": ("undoCount", None),
        },
    ),
    "UserWebhook": (
        None,
        {
            "name": ("name", None),
            "url": ("url", None),
            "display_name": ("displayName", None),
            "create_time": ("createTime", None),
            "update_time": ("updateTime", None),
            "signing_secret": ("signingSecret", None),
            "signing_secret_set": ("signingSecretSet", None),
        },
    ),
    "VideoMetadata": (
        None,
        {
            "duration_seconds": ("durationSeconds", None),
        },
    ),
}
