# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

WIRE_SCHEMAS_PART_2: dict[str, tuple[Any, dict[str, tuple[str, str | None]]]] = {
    "ListMemoSharesResponse": (
        None,
        {
            "memo_shares": ("memoShares", "MemoShare"),
        },
    ),
    "ListMemoViewsResponse": (
        None,
        {
            "memo_views": ("memoViews", "MemoView"),
        },
    ),
    "ListMemosResponse": (
        None,
        {
            "memos": ("memos", "Memo"),
            "next_page_token": ("nextPageToken", None),
        },
    ),
    "ListPersonalAccessTokensResponse": (
        None,
        {
            "personal_access_tokens": ("personalAccessTokens", "PersonalAccessToken"),
            "next_page_token": ("nextPageToken", None),
        },
    ),
    "ListSpaceInvitationsResponse": (
        None,
        {
            "space_invitations": ("spaceInvitations", "SpaceInvitation"),
            "next_page_token": ("nextPageToken", None),
        },
    ),
    "ListSpaceMembersResponse": (
        None,
        {
            "space_members": ("spaceMembers", "SpaceMember"),
            "next_page_token": ("nextPageToken", None),
        },
    ),
    "ListSpacesResponse": (
        None,
        {
            "spaces": ("spaces", "Space"),
            "next_page_token": ("nextPageToken", None),
        },
    ),
    "ListUserNotificationsResponse": (
        None,
        {
            "notifications": ("notifications", "UserNotification"),
            "next_page_token": ("nextPageToken", None),
        },
    ),
    "ListUserSettingsResponse": (
        None,
        {
            "settings": ("settings", "UserSetting"),
            "next_page_token": ("nextPageToken", None),
        },
    ),
    "ListUserSpaceInvitationsResponse": (
        None,
        {
            "space_invitations": ("spaceInvitations", "SpaceInvitation"),
            "next_page_token": ("nextPageToken", None),
        },
    ),
    "ListUserWebhooksResponse": (
        None,
        {
            "webhooks": ("webhooks", "UserWebhook"),
        },
    ),
    "ListUsersResponse": (
        None,
        {
            "users": ("users", "User"),
            "next_page_token": ("nextPageToken", None),
        },
    ),
    "Location": (
        None,
        {
            "placeholder": ("placeholder", None),
            "latitude": ("latitude", None),
            "longitude": ("longitude", None),
        },
    ),
    "MediaCaptureTime": (
        None,
        {
            "local_date_time": ("localDateTime", None),
            "utc_offset": ("utcOffset", None),
        },
    ),
    "MediaLocation": (
        None,
        {
            "latitude": ("latitude", None),
            "longitude": ("longitude", None),
            "altitude_meters": ("altitudeMeters", None),
        },
    ),
    "MediaMetadata": (
        None,
        {
            "width": ("width", None),
            "height": ("height", None),
            "photo": ("photo", "PhotoMetadata"),
            "video": ("video", "VideoMetadata"),
        },
    ),
    "Memo": (
        None,
        {
            "name": ("name", None),
            "state": ("state", None),
            "creator": ("creator", None),
            "create_time": ("createTime", None),
            "update_time": ("updateTime", None),
            "content": ("content", None),
            "visibility": ("visibility", None),
            "tags": ("tags", None),
            "pinned": ("pinned", None),
            "attachments": ("attachments", "Attachment"),
            "relations": ("relations", "MemoRelation"),
            "reactions": ("reactions", "Reaction"),
            "property": ("property", "Memo_Property"),
            "parent": ("parent", None),
            "snippet": ("snippet", None),
            "location": ("location", "Location"),
            "space": ("space", None),
        },
    ),
    "MemoImportIssue": (
        None,
        {
            "memo": ("memo", None),
            "message": ("message", None),
        },
    ),
    "MemoImportPlan": (
        None,
        {
            "export_time": ("exportTime", None),
            "exporter": ("exporter", None),
            "generator": ("generator", None),
            "memos": ("memos", None),
            "attachments": ("attachments", None),
            "new": ("new", None),
            "existing": ("existing", None),
            "renamed": ("renamed", None),
            "warnings": ("warnings", "MemoImportIssue"),
        },
    ),
    "MemoImportReport": (
        None,
        {
            "created": ("created", None),
            "updated": ("updated", None),
            "skipped": ("skipped", None),
            "failed": ("failed", None),
            "warnings": ("warnings", "MemoImportIssue"),
            "failures": ("failures", "MemoImportIssue"),
        },
    ),
    "MemoRelation": (
        None,
        {
            "memo": ("memo", "MemoRelation_Memo"),
            "related_memo": ("relatedMemo", "MemoRelation_Memo"),
            "type": ("type", None),
        },
    ),
    "MemoRelation_Memo": (
        None,
        {
            "name": ("name", None),
            "snippet": ("snippet", None),
        },
    ),
    "MemoShare": (
        None,
        {
            "name": ("name", None),
            "create_time": ("createTime", None),
            "expire_time": ("expireTime", None),
        },
    ),
    "MemoView": (
        None,
        {
            "name": ("name", None),
            "title": ("title", None),
            "filter": ("filter", None),
            "icon": ("icon", "MemoView_Icon"),
        },
    ),
    "MemoView_Icon": (
        None,
        {
            "emoji": ("emoji", None),
            "lucide": ("lucide", None),
        },
    ),
    "Memo_Property": (
        None,
        {
            "has_link": ("hasLink", None),
            "has_task_list": ("hasTaskList", None),
            "has_code": ("hasCode", None),
            "has_incomplete_tasks": ("hasIncompleteTasks", None),
            "title": ("title", None),
        },
    ),
    "MotionMedia": (
        None,
        {
            "family": ("family", None),
            "role": ("role", None),
            "group_id": ("groupId", None),
            "presentation_timestamp_us": ("presentationTimestampUs", None),
            "has_embedded_video": ("hasEmbeddedVideo", None),
        },
    ),
    "NotificationSetting_EmailSetting": (
        None,
        {
            "enabled": ("enabled", None),
            "smtp_host": ("smtpHost", None),
            "smtp_port": ("smtpPort", None),
            "smtp_username": ("smtpUsername", None),
            "smtp_password": ("smtpPassword", None),
            "from_email": ("fromEmail", None),
            "from_name": ("fromName", None),
            "reply_to": ("replyTo", None),
            "use_tls": ("useTls", None),
            "use_ssl": ("useSsl", None),
        },
    ),
    "OAuth2Config": (
        None,
        {
            "client_id": ("clientId", None),
            "client_secret": ("clientSecret", None),
            "auth_url": ("authUrl", None),
            "token_url": ("tokenUrl", None),
            "user_info_url": ("userInfoUrl", None),
            "scopes": ("scopes", None),
            "field_mapping": ("fieldMapping", "FieldMapping"),
        },
    ),
    "PersonalAccessToken": (
        None,
        {
            "name": ("name", None),
            "description": ("description", None),
            "created_at": ("createdAt", None),
            "expires_at": ("expiresAt", None),
            "last_used_at": ("lastUsedAt", None),
        },
    ),
    "PhotoMetadata": (
        None,
        {
            "capture_time": ("captureTime", "MediaCaptureTime"),
            "location": ("location", "MediaLocation"),
            "source_exif_orientation": ("sourceExifOrientation", None),
            "camera_make": ("cameraMake", None),
            "camera_model": ("cameraModel", None),
            "lens_model": ("lensModel", None),
            "f_number": ("fNumber", None),
            "exposure_time_seconds": ("exposureTimeSeconds", None),
            "iso": ("iso", None),
            "focal_length_mm": ("focalLengthMm", None),
        },
    ),
    "Reaction": (
        None,
        {
            "name": ("name", None),
            "creator": ("creator", None),
            "reaction_type": ("reactionType", None),
            "create_time": ("createTime", None),
        },
    ),
    "RefreshTokenRequest": (None, {}),
    "RefreshTokenResponse": (
        None,
        {
            "access_token": ("accessToken", None),
            "expires_at": ("expiresAt", None),
        },
    ),
    "SetMemoAttachmentsRequest": (
        None,
        {
            "name": ("name", None),
            "attachments": ("attachments", "Attachment"),
        },
    ),
    "SetMemoRelationsRequest": (
        None,
        {
            "name": ("name", None),
            "relations": ("relations", "MemoRelation"),
        },
    ),
    "SignInRequest": (
        None,
        {
            "password_credentials": ("passwordCredentials", "SignInRequest_PasswordCredentials"),
            "sso_credentials": ("ssoCredentials", "SignInRequest_SSOCredentials"),
        },
    ),
    "SignInRequest_PasswordCredentials": (
        None,
        {
            "username": ("username", None),
            "password": ("password", None),
        },
    ),
    "SignInRequest_SSOCredentials": (
        None,
        {
            "idp_name": ("idpName", None),
            "code": ("code", None),
            "redirect_uri": ("redirectUri", None),
            "code_verifier": ("codeVerifier", None),
        },
    ),
    "SignInResponse": (
        None,
        {
            "user": ("user", "User"),
            "access_token": ("accessToken", None),
            "access_token_expires_at": ("accessTokenExpiresAt", None),
        },
    ),
    "Space": (
        None,
        {
            "name": ("name", None),
            "title": ("title", None),
            "description": ("description", None),
            "current_user_role": ("currentUserRole", None),
            "member_count": ("memberCount", None),
            "icon": ("icon", "Space_Icon"),
        },
    ),
    "SpaceInvitation": (
        None,
        {
            "name": ("name", None),
            "invitee": ("invitee", None),
            "role": ("role", None),
            "space": ("space", "Space"),
        },
    ),
    "SpaceMember": (
        None,
        {
            "name": ("name", None),
            "user": ("user", None),
            "role": ("role", None),
        },
    ),
    "Space_Icon": (
        None,
        {
            "emoji": ("emoji", None),
            "lucide": ("lucide", None),
        },
    ),
    "Status": (
        None,
        {
            "code": ("code", None),
            "message": ("message", None),
            "details": ("details", "GoogleProtobufAny"),
        },
    ),
    "StorageSetting_S3Config": (
        None,
        {
            "access_key_id": ("accessKeyId", None),
            "access_key_secret": ("accessKeySecret", None),
            "endpoint": ("endpoint", None),
            "region": ("region", None),
            "bucket": ("bucket", None),
            "use_path_style": ("usePathStyle", None),
            "insecure_skip_tls_verify": ("insecureSkipTlsVerify", None),
        },
    ),
    "Storage_S3Config": (
        None,
        {
            "access_key_id": ("accessKeyId", None),
            "access_key_secret": ("accessKeySecret", None),
            "endpoint": ("endpoint", None),
            "region": ("region", None),
            "bucket": ("bucket", None),
            "use_path_style": ("usePathStyle", None),
            "insecure_skip_tls_verify": ("insecureSkipTlsVerify", None),
        },
    ),
    "TestInstanceEmailSettingRequest": (
        None,
        {
            "email": ("email", "NotificationSetting_EmailSetting"),
            "recipient_email": ("recipientEmail", None),
        },
    ),
    "TranscribeRequest": (
        None,
        {
            "audio": ("audio", "TranscriptionAudio"),
        },
    ),
    "TranscribeResponse": (
        None,
        {
            "text": ("text", None),
        },
    ),
}
