# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any, Literal, TypeAlias

from pydantic import TypeAdapter

import memos_unofficial_sdk.types as _response_types
from memos_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    encode_path_segment,
    omit_unset,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from memos_unofficial_sdk.types import (
    ListSpaceMembersResponse,
    Space,
    SpaceInvitation,
    SpaceMember,
    Status,
)
from memos_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


SpaceServiceCreateSpaceInvitationError: TypeAlias = Status


async def space_service_create_space_invitation(
    _client_config: ClientConfig,
    space: str,
    invitee: str,
    role: Literal["ROLE_UNSPECIFIED", "ADMIN", "USER"] | str,
    name: str | NotGiven = NOT_GIVEN,
    space_2: Space | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> SpaceInvitation:
    """Creates an invitation for an existing active user to join a space. Provide the
    invitee's user resource name in `invitee` and choose the role they will receive
    after accepting.

    CreateSpaceInvitation invites an existing active user to a space.

    Args:
        space: The space id.
        invitee: Required. The invited user. Format: users/{username}.
        role: Required. The role the user will receive after accepting the invitation.
        name: The resource name. Format: spaces/{space}/invitations/{username}.
        space_2: Output only. The Space the user is invited to. This lets an invitee understand
            the invitation without granting membership-based GetSpace access.
    """

    _resp = await sdk_request(
        "POST",
        f"/api/v1/spaces/{encode_path_segment(space)}/invitations",
        json=omit_unset(
            {
                "invitee": (NOT_GIVEN if invitee is NOT_GIVEN else to_wire(invitee, "str")),
                "role": (
                    NOT_GIVEN
                    if role is NOT_GIVEN
                    else to_wire(role, 'Literal["ROLE_UNSPECIFIED", "ADMIN", "USER"] | str')
                ),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "space": (NOT_GIVEN if space_2 is NOT_GIVEN else to_wire(space_2, "Space")),
            }
        ),
        operation_id="space_service_create_space_invitation",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "SpaceInvitation"), SpaceInvitation
    )


def space_service_create_space_invitation_sync(
    _client_config: ClientConfig,
    space: str,
    invitee: str,
    role: Literal["ROLE_UNSPECIFIED", "ADMIN", "USER"] | str,
    name: str | NotGiven = NOT_GIVEN,
    space_2: Space | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> SpaceInvitation:
    """Creates an invitation for an existing active user to join a space. Provide the
    invitee's user resource name in `invitee` and choose the role they will receive
    after accepting.

    CreateSpaceInvitation invites an existing active user to a space.

    Args:
        space: The space id.
        invitee: Required. The invited user. Format: users/{username}.
        role: Required. The role the user will receive after accepting the invitation.
        name: The resource name. Format: spaces/{space}/invitations/{username}.
        space_2: Output only. The Space the user is invited to. This lets an invitee understand
            the invitation without granting membership-based GetSpace access.
    """

    _resp = sdk_request_sync(
        "POST",
        f"/api/v1/spaces/{encode_path_segment(space)}/invitations",
        json=omit_unset(
            {
                "invitee": (NOT_GIVEN if invitee is NOT_GIVEN else to_wire(invitee, "str")),
                "role": (
                    NOT_GIVEN
                    if role is NOT_GIVEN
                    else to_wire(role, 'Literal["ROLE_UNSPECIFIED", "ADMIN", "USER"] | str')
                ),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "space": (NOT_GIVEN if space_2 is NOT_GIVEN else to_wire(space_2, "Space")),
            }
        ),
        operation_id="space_service_create_space_invitation",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "SpaceInvitation"), SpaceInvitation
    )


SpaceServiceGetSpaceInvitationError: TypeAlias = Status


async def space_service_get_space_invitation(
    _client_config: ClientConfig,
    space: str,
    invitation: str,
    *,
    request_options: RequestOptions | None = None,
) -> SpaceInvitation:
    """Retrieves a pending invitation to join a space. Use `space` and `invitation` to
    identify the invitation whose details you need, including its invitee and assigned
    role.

    GetSpaceInvitation gets one pending invitation.

    Args:
        space: The space id.
        invitation: The invitation id.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v1/spaces/{encode_path_segment(space)}/invitations/{encode_path_segment(invitation)}",
        operation_id="space_service_get_space_invitation",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "SpaceInvitation"), SpaceInvitation
    )


def space_service_get_space_invitation_sync(
    _client_config: ClientConfig,
    space: str,
    invitation: str,
    *,
    request_options: RequestOptions | None = None,
) -> SpaceInvitation:
    """Retrieves a pending invitation to join a space. Use `space` and `invitation` to
    identify the invitation whose details you need, including its invitee and assigned
    role.

    GetSpaceInvitation gets one pending invitation.

    Args:
        space: The space id.
        invitation: The invitation id.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v1/spaces/{encode_path_segment(space)}/invitations/{encode_path_segment(invitation)}",
        operation_id="space_service_get_space_invitation",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "SpaceInvitation"), SpaceInvitation
    )


SpaceServiceDeleteSpaceInvitationError: TypeAlias = Status


async def space_service_delete_space_invitation(
    _client_config: ClientConfig,
    space: str,
    invitation: str,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Deletes a pending invitation to join a space, revoking the invitation. Identify the
    space and invitation so you remove the intended invitation.

    DeleteSpaceInvitation revokes a pending invitation.

    Args:
        space: The space id.
        invitation: The invitation id.
    """

    _resp = await sdk_request(
        "DELETE",
        f"/api/v1/spaces/{encode_path_segment(space)}/invitations/{encode_path_segment(invitation)}",
        operation_id="space_service_delete_space_invitation",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


def space_service_delete_space_invitation_sync(
    _client_config: ClientConfig,
    space: str,
    invitation: str,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Deletes a pending invitation to join a space, revoking the invitation. Identify the
    space and invitation so you remove the intended invitation.

    DeleteSpaceInvitation revokes a pending invitation.

    Args:
        space: The space id.
        invitation: The invitation id.
    """

    _resp = sdk_request_sync(
        "DELETE",
        f"/api/v1/spaces/{encode_path_segment(space)}/invitations/{encode_path_segment(invitation)}",
        operation_id="space_service_delete_space_invitation",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


SpaceServiceAcceptSpaceInvitationError: TypeAlias = Status


async def space_service_accept_space_invitation(
    _client_config: ClientConfig,
    space: str,
    invitation: str,
    name: str,
    *,
    request_options: RequestOptions | None = None,
) -> SpaceMember:
    """Accepts a pending invitation to join a space and creates a membership for the
    invitee. Supply the invitation resource name in `name`; the returned membership
    includes the user's role in the space.

    AcceptSpaceInvitation accepts a pending invitation and creates a membership.

    Args:
        space: The space id.
        invitation: The invitation id.
        name: Required. Format: spaces/{space}/invitations/{username}.
    """

    _resp = await sdk_request(
        "POST",
        f"/api/v1/spaces/{encode_path_segment(space)}/invitations/{encode_path_segment(invitation)}:accept",
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
            }
        ),
        operation_id="space_service_accept_space_invitation",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "SpaceMember"), SpaceMember
    )


def space_service_accept_space_invitation_sync(
    _client_config: ClientConfig,
    space: str,
    invitation: str,
    name: str,
    *,
    request_options: RequestOptions | None = None,
) -> SpaceMember:
    """Accepts a pending invitation to join a space and creates a membership for the
    invitee. Supply the invitation resource name in `name`; the returned membership
    includes the user's role in the space.

    AcceptSpaceInvitation accepts a pending invitation and creates a membership.

    Args:
        space: The space id.
        invitation: The invitation id.
        name: Required. Format: spaces/{space}/invitations/{username}.
    """

    _resp = sdk_request_sync(
        "POST",
        f"/api/v1/spaces/{encode_path_segment(space)}/invitations/{encode_path_segment(invitation)}:accept",
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
            }
        ),
        operation_id="space_service_accept_space_invitation",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "SpaceMember"), SpaceMember
    )


SpaceServiceDeclineSpaceInvitationError: TypeAlias = Status


async def space_service_decline_space_invitation(
    _client_config: ClientConfig,
    space: str,
    invitation: str,
    name: str,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Declines a pending invitation to join a space. Supply the invitation resource name
    in `name` to identify the invitation being declined.

    DeclineSpaceInvitation declines a pending invitation.

    Args:
        space: The space id.
        invitation: The invitation id.
        name: Required. Format: spaces/{space}/invitations/{username}.
    """

    _resp = await sdk_request(
        "POST",
        f"/api/v1/spaces/{encode_path_segment(space)}/invitations/{encode_path_segment(invitation)}:decline",
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
            }
        ),
        operation_id="space_service_decline_space_invitation",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


def space_service_decline_space_invitation_sync(
    _client_config: ClientConfig,
    space: str,
    invitation: str,
    name: str,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Declines a pending invitation to join a space. Supply the invitation resource name
    in `name` to identify the invitation being declined.

    DeclineSpaceInvitation declines a pending invitation.

    Args:
        space: The space id.
        invitation: The invitation id.
        name: Required. Format: spaces/{space}/invitations/{username}.
    """

    _resp = sdk_request_sync(
        "POST",
        f"/api/v1/spaces/{encode_path_segment(space)}/invitations/{encode_path_segment(invitation)}:decline",
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
            }
        ),
        operation_id="space_service_decline_space_invitation",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


SpaceServiceListSpaceMembersError: TypeAlias = Status


async def space_service_list_space_members(
    _client_config: ClientConfig,
    space: str,
    page_size: int | NotGiven = NOT_GIVEN,
    page_token: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ListSpaceMembersResponse:
    """Lists the members of a space. Use `pageSize` to limit the number of members returned
    and `pageToken` to continue from a previous response.

    ListSpaceMembers lists the members of a space.

    Args:
        space: The space id.
        page_size: Optional. The maximum number of members to return.
        page_token: Optional. A token from a previous ListSpaceMembers response.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v1/spaces/{encode_path_segment(space)}/members",
        params=serialize_query(
            [("pageSize", page_size, "form", True), ("pageToken", page_token, "form", True)]
        ),
        operation_id="space_service_list_space_members",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListSpaceMembersResponse"), ListSpaceMembersResponse
    )


def space_service_list_space_members_sync(
    _client_config: ClientConfig,
    space: str,
    page_size: int | NotGiven = NOT_GIVEN,
    page_token: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ListSpaceMembersResponse:
    """Lists the members of a space. Use `pageSize` to limit the number of members returned
    and `pageToken` to continue from a previous response.

    ListSpaceMembers lists the members of a space.

    Args:
        space: The space id.
        page_size: Optional. The maximum number of members to return.
        page_token: Optional. A token from a previous ListSpaceMembers response.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v1/spaces/{encode_path_segment(space)}/members",
        params=serialize_query(
            [("pageSize", page_size, "form", True), ("pageToken", page_token, "form", True)]
        ),
        operation_id="space_service_list_space_members",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListSpaceMembersResponse"), ListSpaceMembersResponse
    )


SpaceServiceGetSpaceMemberError: TypeAlias = Status


async def space_service_get_space_member(
    _client_config: ClientConfig,
    space: str,
    member: str,
    *,
    request_options: RequestOptions | None = None,
) -> SpaceMember:
    """Retrieves one membership in a space. Use `space` and `member` to identify the space
    membership whose user and role you need.

    GetSpaceMember gets one membership in a space.

    Args:
        space: The space id.
        member: The member id.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v1/spaces/{encode_path_segment(space)}/members/{encode_path_segment(member)}",
        operation_id="space_service_get_space_member",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "SpaceMember"), SpaceMember
    )


def space_service_get_space_member_sync(
    _client_config: ClientConfig,
    space: str,
    member: str,
    *,
    request_options: RequestOptions | None = None,
) -> SpaceMember:
    """Retrieves one membership in a space. Use `space` and `member` to identify the space
    membership whose user and role you need.

    GetSpaceMember gets one membership in a space.

    Args:
        space: The space id.
        member: The member id.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v1/spaces/{encode_path_segment(space)}/members/{encode_path_segment(member)}",
        operation_id="space_service_get_space_member",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "SpaceMember"), SpaceMember
    )


__all__ = [
    "SpaceServiceAcceptSpaceInvitationError",
    "SpaceServiceCreateSpaceInvitationError",
    "SpaceServiceDeclineSpaceInvitationError",
    "SpaceServiceDeleteSpaceInvitationError",
    "SpaceServiceGetSpaceInvitationError",
    "SpaceServiceGetSpaceMemberError",
    "SpaceServiceListSpaceMembersError",
    "space_service_accept_space_invitation",
    "space_service_accept_space_invitation_sync",
    "space_service_create_space_invitation",
    "space_service_create_space_invitation_sync",
    "space_service_decline_space_invitation",
    "space_service_decline_space_invitation_sync",
    "space_service_delete_space_invitation",
    "space_service_delete_space_invitation_sync",
    "space_service_get_space_invitation",
    "space_service_get_space_invitation_sync",
    "space_service_get_space_member",
    "space_service_get_space_member_sync",
    "space_service_list_space_members",
    "space_service_list_space_members_sync",
]
