# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any, Literal, TypeAlias

from pydantic import TypeAdapter

import memos_unofficial_sdk.types as _response_types
from memos_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    encode_path_segment,
    omit_unset,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from memos_unofficial_sdk.types import ListUserSpaceInvitationsResponse, SpaceMember, Status
from memos_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


SpaceServiceDeleteSpaceMemberError: TypeAlias = Status


async def space_service_delete_space_member(
    _client_config: ClientConfig,
    space: str,
    member: str,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Deletes a membership from a space, removing the member. A member can delete their
    own membership to leave the space.

    DeleteSpaceMember removes a member. A member may delete their own membership to
    leave the space.

    Args:
        space: The space id.
        member: The member id.
    """

    _resp = await sdk_request(
        "DELETE",
        f"/api/v1/spaces/{encode_path_segment(space)}/members/{encode_path_segment(member)}",
        operation_id="space_service_delete_space_member",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


def space_service_delete_space_member_sync(
    _client_config: ClientConfig,
    space: str,
    member: str,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Deletes a membership from a space, removing the member. A member can delete their
    own membership to leave the space.

    DeleteSpaceMember removes a member. A member may delete their own membership to
    leave the space.

    Args:
        space: The space id.
        member: The member id.
    """

    _resp = sdk_request_sync(
        "DELETE",
        f"/api/v1/spaces/{encode_path_segment(space)}/members/{encode_path_segment(member)}",
        operation_id="space_service_delete_space_member",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


SpaceServiceUpdateSpaceMemberError: TypeAlias = Status


async def space_service_update_space_member(
    _client_config: ClientConfig,
    space: str,
    member: str,
    user: str,
    role: Literal["ROLE_UNSPECIFIED", "ADMIN", "USER"] | str,
    update_mask: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> SpaceMember:
    """Updates a member's role in a space. Supply the member resource in the body and use
    `updateMask` to select the supported `role` field for the update.

    UpdateSpaceMember changes a member's space role.

    Args:
        space: The space id.
        member: The member id.
        user: Required. The member user. Format: users/{username}.
        role: Required. The member's role within this space.
        update_mask: Required. Only role is supported.
        name: The resource name. Format: spaces/{space}/members/{username}.
    """

    _resp = await sdk_request(
        "PATCH",
        f"/api/v1/spaces/{encode_path_segment(space)}/members/{encode_path_segment(member)}",
        params=serialize_query([("updateMask", update_mask, "form", True)]),
        json=omit_unset(
            {
                "user": (NOT_GIVEN if user is NOT_GIVEN else to_wire(user, "str")),
                "role": (
                    NOT_GIVEN
                    if role is NOT_GIVEN
                    else to_wire(role, 'Literal["ROLE_UNSPECIFIED", "ADMIN", "USER"] | str')
                ),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
            }
        ),
        operation_id="space_service_update_space_member",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "SpaceMember"), SpaceMember
    )


def space_service_update_space_member_sync(
    _client_config: ClientConfig,
    space: str,
    member: str,
    user: str,
    role: Literal["ROLE_UNSPECIFIED", "ADMIN", "USER"] | str,
    update_mask: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> SpaceMember:
    """Updates a member's role in a space. Supply the member resource in the body and use
    `updateMask` to select the supported `role` field for the update.

    UpdateSpaceMember changes a member's space role.

    Args:
        space: The space id.
        member: The member id.
        user: Required. The member user. Format: users/{username}.
        role: Required. The member's role within this space.
        update_mask: Required. Only role is supported.
        name: The resource name. Format: spaces/{space}/members/{username}.
    """

    _resp = sdk_request_sync(
        "PATCH",
        f"/api/v1/spaces/{encode_path_segment(space)}/members/{encode_path_segment(member)}",
        params=serialize_query([("updateMask", update_mask, "form", True)]),
        json=omit_unset(
            {
                "user": (NOT_GIVEN if user is NOT_GIVEN else to_wire(user, "str")),
                "role": (
                    NOT_GIVEN
                    if role is NOT_GIVEN
                    else to_wire(role, 'Literal["ROLE_UNSPECIFIED", "ADMIN", "USER"] | str')
                ),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
            }
        ),
        operation_id="space_service_update_space_member",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "SpaceMember"), SpaceMember
    )


SpaceServiceListUserSpaceInvitationsError: TypeAlias = Status


async def space_service_list_user_space_invitations(
    _client_config: ClientConfig,
    user: str,
    page_size: int | NotGiven = NOT_GIVEN,
    page_token: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ListUserSpaceInvitationsResponse:
    """Lists pending space invitations for a user. Use `pageSize` to set the maximum number
    of invitations to return and `pageToken` to continue through the results. The
    invitations are for joining spaces.

    ListUserSpaceInvitations lists the authenticated user's pending space invitations.

    Args:
        user: The user id.
        page_size: Optional. The maximum number of invitations to return.
        page_token: Optional. A token from a previous ListUserSpaceInvitations response.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v1/users/{encode_path_segment(user)}/spaceInvitations",
        params=serialize_query(
            [("pageSize", page_size, "form", True), ("pageToken", page_token, "form", True)]
        ),
        operation_id="space_service_list_user_space_invitations",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListUserSpaceInvitationsResponse"),
        ListUserSpaceInvitationsResponse,
    )


def space_service_list_user_space_invitations_sync(
    _client_config: ClientConfig,
    user: str,
    page_size: int | NotGiven = NOT_GIVEN,
    page_token: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ListUserSpaceInvitationsResponse:
    """Lists pending space invitations for a user. Use `pageSize` to set the maximum number
    of invitations to return and `pageToken` to continue through the results. The
    invitations are for joining spaces.

    ListUserSpaceInvitations lists the authenticated user's pending space invitations.

    Args:
        user: The user id.
        page_size: Optional. The maximum number of invitations to return.
        page_token: Optional. A token from a previous ListUserSpaceInvitations response.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v1/users/{encode_path_segment(user)}/spaceInvitations",
        params=serialize_query(
            [("pageSize", page_size, "form", True), ("pageToken", page_token, "form", True)]
        ),
        operation_id="space_service_list_user_space_invitations",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListUserSpaceInvitationsResponse"),
        ListUserSpaceInvitationsResponse,
    )


__all__ = [
    "SpaceServiceDeleteSpaceMemberError",
    "SpaceServiceListUserSpaceInvitationsError",
    "SpaceServiceUpdateSpaceMemberError",
    "space_service_delete_space_member",
    "space_service_delete_space_member_sync",
    "space_service_list_user_space_invitations",
    "space_service_list_user_space_invitations_sync",
    "space_service_update_space_member",
    "space_service_update_space_member_sync",
]
