# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime
from typing import Any, Literal, TypeAlias

from pydantic import TypeAdapter

import memos_unofficial_sdk.types as _response_types
from memos_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    encode_path_segment,
    omit_unset,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from memos_unofficial_sdk.types import (
    CreatePersonalAccessTokenResponse,
    ListPersonalAccessTokensResponse,
    ListUserSettingsResponse,
    Status,
    User,
    UserNotification,
    UserNotification_MemoCommentPayload,
    UserNotification_MemoMentionPayload,
    UserNotification_SpaceInvitationPayload,
)
from memos_unofficial_sdk.validation import validate_date_time
from memos_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


UserServiceDeleteUserNotificationError: TypeAlias = Status


async def user_service_delete_user_notification(
    _client_config: ClientConfig,
    user: str,
    notification: str,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Deletes a notification from a user's notification list. Supply the user and
    notification identifiers for the notification you want to delete.

    DeleteUserNotification deletes a notification.

    Args:
        user: The user id.
        notification: The notification id.
    """

    _resp = await sdk_request(
        "DELETE",
        f"/api/v1/users/{encode_path_segment(user)}/notifications/{encode_path_segment(notification)}",
        operation_id="user_service_delete_user_notification",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


def user_service_delete_user_notification_sync(
    _client_config: ClientConfig,
    user: str,
    notification: str,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Deletes a notification from a user's notification list. Supply the user and
    notification identifiers for the notification you want to delete.

    DeleteUserNotification deletes a notification.

    Args:
        user: The user id.
        notification: The notification id.
    """

    _resp = sdk_request_sync(
        "DELETE",
        f"/api/v1/users/{encode_path_segment(user)}/notifications/{encode_path_segment(notification)}",
        operation_id="user_service_delete_user_notification",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


UserServiceUpdateUserNotificationError: TypeAlias = Status


async def user_service_update_user_notification(
    _client_config: ClientConfig,
    user: str,
    notification: str,
    update_mask: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    sender: str | NotGiven = NOT_GIVEN,
    sender_user: User | NotGiven = NOT_GIVEN,
    status: Literal["STATUS_UNSPECIFIED", "UNREAD", "ARCHIVED"] | str | NotGiven = NOT_GIVEN,
    create_time: datetime.datetime | NotGiven = NOT_GIVEN,
    type: Literal["TYPE_UNSPECIFIED", "MEMO_COMMENT", "MEMO_MENTION", "SPACE_INVITATION"]
    | str
    | NotGiven = NOT_GIVEN,
    memo_comment: UserNotification_MemoCommentPayload | NotGiven = NOT_GIVEN,
    memo_mention: UserNotification_MemoMentionPayload | NotGiven = NOT_GIVEN,
    space_invitation: UserNotification_SpaceInvitationPayload | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UserNotification:
    """Updates a user's notification. Use `updateMask` to select the fields to change; the
    request body schema exposes `status` as an editable field, while the other defined
    fields are read-only.

    UpdateUserNotification updates a notification.

    Args:
        user: The user id.
        notification: The notification id.
        name: The resource name of the notification. Format:
            users/{user}/notifications/{notification}
        sender: The sender of the notification. Format: users/{user}
        sender_user: The sender user details.
        status: The status of the notification.
        create_time: The creation timestamp.
        type: The type of the notification.
        memo_comment: Optional API value serialized in the `memoComment` wire field.
        memo_mention: Optional API value serialized in the `memoMention` wire field.
        space_invitation: Optional API value serialized in the `spaceInvitation` wire field.
    """

    if not isinstance(create_time, NotGiven) and create_time is not None:
        validate_date_time("createTime", create_time)

    _resp = await sdk_request(
        "PATCH",
        f"/api/v1/users/{encode_path_segment(user)}/notifications/{encode_path_segment(notification)}",
        params=serialize_query([("updateMask", update_mask, "form", True)]),
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "sender": (NOT_GIVEN if sender is NOT_GIVEN else to_wire(sender, "str")),
                "senderUser": (
                    NOT_GIVEN if sender_user is NOT_GIVEN else to_wire(sender_user, "User")
                ),
                "status": (
                    NOT_GIVEN
                    if status is NOT_GIVEN
                    else to_wire(
                        status, 'Literal["STATUS_UNSPECIFIED", "UNREAD", "ARCHIVED"] | str'
                    )
                ),
                "createTime": (
                    NOT_GIVEN
                    if create_time is NOT_GIVEN
                    else to_wire(create_time, "datetime.datetime")
                ),
                "type": (
                    NOT_GIVEN
                    if type is NOT_GIVEN
                    else to_wire(
                        type,
                        'Literal["TYPE_UNSPECIFIED", "MEMO_COMMENT", "MEMO_MENTION", "SPACE_INVITATION"] | str',
                    )
                ),
                "memoComment": (
                    NOT_GIVEN
                    if memo_comment is NOT_GIVEN
                    else to_wire(memo_comment, "UserNotification_MemoCommentPayload")
                ),
                "memoMention": (
                    NOT_GIVEN
                    if memo_mention is NOT_GIVEN
                    else to_wire(memo_mention, "UserNotification_MemoMentionPayload")
                ),
                "spaceInvitation": (
                    NOT_GIVEN
                    if space_invitation is NOT_GIVEN
                    else to_wire(space_invitation, "UserNotification_SpaceInvitationPayload")
                ),
            }
        ),
        operation_id="user_service_update_user_notification",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UserNotification"), UserNotification
    )


def user_service_update_user_notification_sync(
    _client_config: ClientConfig,
    user: str,
    notification: str,
    update_mask: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    sender: str | NotGiven = NOT_GIVEN,
    sender_user: User | NotGiven = NOT_GIVEN,
    status: Literal["STATUS_UNSPECIFIED", "UNREAD", "ARCHIVED"] | str | NotGiven = NOT_GIVEN,
    create_time: datetime.datetime | NotGiven = NOT_GIVEN,
    type: Literal["TYPE_UNSPECIFIED", "MEMO_COMMENT", "MEMO_MENTION", "SPACE_INVITATION"]
    | str
    | NotGiven = NOT_GIVEN,
    memo_comment: UserNotification_MemoCommentPayload | NotGiven = NOT_GIVEN,
    memo_mention: UserNotification_MemoMentionPayload | NotGiven = NOT_GIVEN,
    space_invitation: UserNotification_SpaceInvitationPayload | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UserNotification:
    """Updates a user's notification. Use `updateMask` to select the fields to change; the
    request body schema exposes `status` as an editable field, while the other defined
    fields are read-only.

    UpdateUserNotification updates a notification.

    Args:
        user: The user id.
        notification: The notification id.
        name: The resource name of the notification. Format:
            users/{user}/notifications/{notification}
        sender: The sender of the notification. Format: users/{user}
        sender_user: The sender user details.
        status: The status of the notification.
        create_time: The creation timestamp.
        type: The type of the notification.
        memo_comment: Optional API value serialized in the `memoComment` wire field.
        memo_mention: Optional API value serialized in the `memoMention` wire field.
        space_invitation: Optional API value serialized in the `spaceInvitation` wire field.
    """

    if not isinstance(create_time, NotGiven) and create_time is not None:
        validate_date_time("createTime", create_time)

    _resp = sdk_request_sync(
        "PATCH",
        f"/api/v1/users/{encode_path_segment(user)}/notifications/{encode_path_segment(notification)}",
        params=serialize_query([("updateMask", update_mask, "form", True)]),
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "sender": (NOT_GIVEN if sender is NOT_GIVEN else to_wire(sender, "str")),
                "senderUser": (
                    NOT_GIVEN if sender_user is NOT_GIVEN else to_wire(sender_user, "User")
                ),
                "status": (
                    NOT_GIVEN
                    if status is NOT_GIVEN
                    else to_wire(
                        status, 'Literal["STATUS_UNSPECIFIED", "UNREAD", "ARCHIVED"] | str'
                    )
                ),
                "createTime": (
                    NOT_GIVEN
                    if create_time is NOT_GIVEN
                    else to_wire(create_time, "datetime.datetime")
                ),
                "type": (
                    NOT_GIVEN
                    if type is NOT_GIVEN
                    else to_wire(
                        type,
                        'Literal["TYPE_UNSPECIFIED", "MEMO_COMMENT", "MEMO_MENTION", "SPACE_INVITATION"] | str',
                    )
                ),
                "memoComment": (
                    NOT_GIVEN
                    if memo_comment is NOT_GIVEN
                    else to_wire(memo_comment, "UserNotification_MemoCommentPayload")
                ),
                "memoMention": (
                    NOT_GIVEN
                    if memo_mention is NOT_GIVEN
                    else to_wire(memo_mention, "UserNotification_MemoMentionPayload")
                ),
                "spaceInvitation": (
                    NOT_GIVEN
                    if space_invitation is NOT_GIVEN
                    else to_wire(space_invitation, "UserNotification_SpaceInvitationPayload")
                ),
            }
        ),
        operation_id="user_service_update_user_notification",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UserNotification"), UserNotification
    )


UserServiceListPersonalAccessTokensError: TypeAlias = Status


async def user_service_list_personal_access_tokens(
    _client_config: ClientConfig,
    user: str,
    page_size: int | NotGiven = NOT_GIVEN,
    page_token: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ListPersonalAccessTokensResponse:
    """Lists long-lived personal access tokens (PATs) for a user. Use `pageSize` and
    `pageToken` to retrieve results in pages; PATs provide API and script access and are
    distinct from short-lived JWTs used for session authentication.

    ListPersonalAccessTokens returns a list of Personal Access Tokens (PATs) for a user.
    PATs are long-lived tokens for API/script access, distinct from short-lived JWT
    access tokens.

    Args:
        user: The user id.
        page_size: Optional. The maximum number of tokens to return.
        page_token: Optional. A page token for pagination.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v1/users/{encode_path_segment(user)}/personalAccessTokens",
        params=serialize_query(
            [("pageSize", page_size, "form", True), ("pageToken", page_token, "form", True)]
        ),
        operation_id="user_service_list_personal_access_tokens",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListPersonalAccessTokensResponse"),
        ListPersonalAccessTokensResponse,
    )


def user_service_list_personal_access_tokens_sync(
    _client_config: ClientConfig,
    user: str,
    page_size: int | NotGiven = NOT_GIVEN,
    page_token: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ListPersonalAccessTokensResponse:
    """Lists long-lived personal access tokens (PATs) for a user. Use `pageSize` and
    `pageToken` to retrieve results in pages; PATs provide API and script access and are
    distinct from short-lived JWTs used for session authentication.

    ListPersonalAccessTokens returns a list of Personal Access Tokens (PATs) for a user.
    PATs are long-lived tokens for API/script access, distinct from short-lived JWT
    access tokens.

    Args:
        user: The user id.
        page_size: Optional. The maximum number of tokens to return.
        page_token: Optional. A page token for pagination.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v1/users/{encode_path_segment(user)}/personalAccessTokens",
        params=serialize_query(
            [("pageSize", page_size, "form", True), ("pageToken", page_token, "form", True)]
        ),
        operation_id="user_service_list_personal_access_tokens",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListPersonalAccessTokensResponse"),
        ListPersonalAccessTokensResponse,
    )


UserServiceCreatePersonalAccessTokenError: TypeAlias = Status


async def user_service_create_personal_access_token(
    _client_config: ClientConfig,
    user: str,
    parent: str,
    description: str | NotGiven = NOT_GIVEN,
    expires_in_days: int | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> CreatePersonalAccessTokenResponse:
    """Creates a long-lived personal access token for a user. Supply the required `parent`
    resource name in the format `users/{user}`; you can optionally provide a
    `description` and an `expiresInDays` value. The token value is returned only when
    you create the token, so store it securely at that time.

    CreatePersonalAccessToken creates a new Personal Access Token for a user. The token
    value is only returned once upon creation.

    Args:
        user: The user id.
        parent: Required. The parent resource where this token will be created. Format:
            users/{user}
        description: Optional. Description of the personal access token.
        expires_in_days: Optional. Expiration duration in days (0 = never expires).
    """

    _resp = await sdk_request(
        "POST",
        f"/api/v1/users/{encode_path_segment(user)}/personalAccessTokens",
        json=omit_unset(
            {
                "parent": (NOT_GIVEN if parent is NOT_GIVEN else to_wire(parent, "str")),
                "description": (
                    NOT_GIVEN if description is NOT_GIVEN else to_wire(description, "str")
                ),
                "expiresInDays": (
                    NOT_GIVEN if expires_in_days is NOT_GIVEN else to_wire(expires_in_days, "int")
                ),
            }
        ),
        operation_id="user_service_create_personal_access_token",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "CreatePersonalAccessTokenResponse"),
        CreatePersonalAccessTokenResponse,
    )


def user_service_create_personal_access_token_sync(
    _client_config: ClientConfig,
    user: str,
    parent: str,
    description: str | NotGiven = NOT_GIVEN,
    expires_in_days: int | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> CreatePersonalAccessTokenResponse:
    """Creates a long-lived personal access token for a user. Supply the required `parent`
    resource name in the format `users/{user}`; you can optionally provide a
    `description` and an `expiresInDays` value. The token value is returned only when
    you create the token, so store it securely at that time.

    CreatePersonalAccessToken creates a new Personal Access Token for a user. The token
    value is only returned once upon creation.

    Args:
        user: The user id.
        parent: Required. The parent resource where this token will be created. Format:
            users/{user}
        description: Optional. Description of the personal access token.
        expires_in_days: Optional. Expiration duration in days (0 = never expires).
    """

    _resp = sdk_request_sync(
        "POST",
        f"/api/v1/users/{encode_path_segment(user)}/personalAccessTokens",
        json=omit_unset(
            {
                "parent": (NOT_GIVEN if parent is NOT_GIVEN else to_wire(parent, "str")),
                "description": (
                    NOT_GIVEN if description is NOT_GIVEN else to_wire(description, "str")
                ),
                "expiresInDays": (
                    NOT_GIVEN if expires_in_days is NOT_GIVEN else to_wire(expires_in_days, "int")
                ),
            }
        ),
        operation_id="user_service_create_personal_access_token",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "CreatePersonalAccessTokenResponse"),
        CreatePersonalAccessTokenResponse,
    )


UserServiceDeletePersonalAccessTokenError: TypeAlias = Status


async def user_service_delete_personal_access_token(
    _client_config: ClientConfig,
    user: str,
    personal_access_token: str,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Deletes a personal access token. Provide the user and token identifiers to specify
    which PAT to delete. The token is a long-lived credential for API or script access.

    DeletePersonalAccessToken deletes a Personal Access Token.

    Args:
        user: The user id.
        personal_access_token: The personalAccessToken id.
    """

    _resp = await sdk_request(
        "DELETE",
        f"/api/v1/users/{encode_path_segment(user)}/personalAccessTokens/{encode_path_segment(personal_access_token)}",
        operation_id="user_service_delete_personal_access_token",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


def user_service_delete_personal_access_token_sync(
    _client_config: ClientConfig,
    user: str,
    personal_access_token: str,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Deletes a personal access token. Provide the user and token identifiers to specify
    which PAT to delete. The token is a long-lived credential for API or script access.

    DeletePersonalAccessToken deletes a Personal Access Token.

    Args:
        user: The user id.
        personal_access_token: The personalAccessToken id.
    """

    _resp = sdk_request_sync(
        "DELETE",
        f"/api/v1/users/{encode_path_segment(user)}/personalAccessTokens/{encode_path_segment(personal_access_token)}",
        operation_id="user_service_delete_personal_access_token",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


UserServiceListUserSettingsError: TypeAlias = Status


async def user_service_list_user_settings(
    _client_config: ClientConfig,
    user: str,
    page_size: int | NotGiven = NOT_GIVEN,
    page_token: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ListUserSettingsResponse:
    """Lists settings for a user. Use `pageSize` to limit the number of settings returned
    and `pageToken` to continue from a previous page. The service returns at most 50
    settings by default and coerces `pageSize` values above 1000 to 1000.

    ListUserSettings returns a list of user settings.

    Args:
        user: The user id.
        page_size: Optional. The maximum number of settings to return. The service may return fewer
            than this value. If unspecified, at most 50 settings will be returned. The
            maximum value is 1000; values above 1000 will be coerced to 1000.
        page_token: Optional. A page token, received from a previous `ListUserSettings` call.
            Provide this to retrieve the subsequent page.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v1/users/{encode_path_segment(user)}/settings",
        params=serialize_query(
            [("pageSize", page_size, "form", True), ("pageToken", page_token, "form", True)]
        ),
        operation_id="user_service_list_user_settings",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListUserSettingsResponse"), ListUserSettingsResponse
    )


def user_service_list_user_settings_sync(
    _client_config: ClientConfig,
    user: str,
    page_size: int | NotGiven = NOT_GIVEN,
    page_token: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ListUserSettingsResponse:
    """Lists settings for a user. Use `pageSize` to limit the number of settings returned
    and `pageToken` to continue from a previous page. The service returns at most 50
    settings by default and coerces `pageSize` values above 1000 to 1000.

    ListUserSettings returns a list of user settings.

    Args:
        user: The user id.
        page_size: Optional. The maximum number of settings to return. The service may return fewer
            than this value. If unspecified, at most 50 settings will be returned. The
            maximum value is 1000; values above 1000 will be coerced to 1000.
        page_token: Optional. A page token, received from a previous `ListUserSettings` call.
            Provide this to retrieve the subsequent page.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v1/users/{encode_path_segment(user)}/settings",
        params=serialize_query(
            [("pageSize", page_size, "form", True), ("pageToken", page_token, "form", True)]
        ),
        operation_id="user_service_list_user_settings",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListUserSettingsResponse"), ListUserSettingsResponse
    )


__all__ = [
    "UserServiceCreatePersonalAccessTokenError",
    "UserServiceDeletePersonalAccessTokenError",
    "UserServiceDeleteUserNotificationError",
    "UserServiceListPersonalAccessTokensError",
    "UserServiceListUserSettingsError",
    "UserServiceUpdateUserNotificationError",
    "user_service_create_personal_access_token",
    "user_service_create_personal_access_token_sync",
    "user_service_delete_personal_access_token",
    "user_service_delete_personal_access_token_sync",
    "user_service_delete_user_notification",
    "user_service_delete_user_notification_sync",
    "user_service_list_personal_access_tokens",
    "user_service_list_personal_access_tokens_sync",
    "user_service_list_user_settings",
    "user_service_list_user_settings_sync",
    "user_service_update_user_notification",
    "user_service_update_user_notification_sync",
]
