# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any, TypeAlias

from pydantic import TypeAdapter

import memos_unofficial_sdk.types as _response_types
from memos_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    encode_path_segment,
    omit_unset,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from memos_unofficial_sdk.types import (
    ListMemoViewsResponse,
    MemoView,
    MemoView_Icon,
    Status,
    UserSetting,
    UserSetting_GeneralSetting,
    UserSetting_TagsSetting,
    UserSetting_WebhooksSetting,
)
from memos_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


UserServiceGetUserSettingError: TypeAlias = Status


async def user_service_get_user_setting(
    _client_config: ClientConfig,
    user: str,
    setting: str,
    *,
    request_options: RequestOptions | None = None,
) -> UserSetting:
    """Retrieves a specific setting for a user. Provide the user ID and setting key to
    identify the setting resource. The setting key appears in the resource name as
    `users/{user}/settings/{setting}`.

    GetUserSetting returns the user setting.

    Args:
        user: The user id.
        setting: The setting id.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v1/users/{encode_path_segment(user)}/settings/{encode_path_segment(setting)}",
        operation_id="user_service_get_user_setting",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UserSetting"), UserSetting
    )


def user_service_get_user_setting_sync(
    _client_config: ClientConfig,
    user: str,
    setting: str,
    *,
    request_options: RequestOptions | None = None,
) -> UserSetting:
    """Retrieves a specific setting for a user. Provide the user ID and setting key to
    identify the setting resource. The setting key appears in the resource name as
    `users/{user}/settings/{setting}`.

    GetUserSetting returns the user setting.

    Args:
        user: The user id.
        setting: The setting id.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v1/users/{encode_path_segment(user)}/settings/{encode_path_segment(setting)}",
        operation_id="user_service_get_user_setting",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UserSetting"), UserSetting
    )


UserServiceUpdateUserSettingError: TypeAlias = Status


async def user_service_update_user_setting(
    _client_config: ClientConfig,
    user: str,
    setting: str,
    update_mask: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    general_setting: UserSetting_GeneralSetting | NotGiven = NOT_GIVEN,
    webhooks_setting: UserSetting_WebhooksSetting | NotGiven = NOT_GIVEN,
    tags_setting: UserSetting_TagsSetting | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UserSetting:
    """Updates a user's setting. Supply the setting fields to change and use `updateMask`
    to specify which fields to update. The setting resource name follows the format
    `users/{user}/settings/{setting}`.

    UpdateUserSetting updates the user setting.

    Args:
        user: The user id.
        setting: The setting id.
        update_mask: Required. The list of fields to update.
        name: The name of the user setting. Format: users/{user}/settings/{setting}, {setting}
            is the key for the setting. For example, "users/steven/settings/GENERAL" for
            general settings.
        general_setting: General user settings configuration.
        webhooks_setting: User webhooks configuration.
        tags_setting: User-specific tag metadata.
    """

    _resp = await sdk_request(
        "PATCH",
        f"/api/v1/users/{encode_path_segment(user)}/settings/{encode_path_segment(setting)}",
        params=serialize_query([("updateMask", update_mask, "form", True)]),
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "generalSetting": (
                    NOT_GIVEN
                    if general_setting is NOT_GIVEN
                    else to_wire(general_setting, "UserSetting_GeneralSetting")
                ),
                "webhooksSetting": (
                    NOT_GIVEN
                    if webhooks_setting is NOT_GIVEN
                    else to_wire(webhooks_setting, "UserSetting_WebhooksSetting")
                ),
                "tagsSetting": (
                    NOT_GIVEN
                    if tags_setting is NOT_GIVEN
                    else to_wire(tags_setting, "UserSetting_TagsSetting")
                ),
            }
        ),
        operation_id="user_service_update_user_setting",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UserSetting"), UserSetting
    )


def user_service_update_user_setting_sync(
    _client_config: ClientConfig,
    user: str,
    setting: str,
    update_mask: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    general_setting: UserSetting_GeneralSetting | NotGiven = NOT_GIVEN,
    webhooks_setting: UserSetting_WebhooksSetting | NotGiven = NOT_GIVEN,
    tags_setting: UserSetting_TagsSetting | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UserSetting:
    """Updates a user's setting. Supply the setting fields to change and use `updateMask`
    to specify which fields to update. The setting resource name follows the format
    `users/{user}/settings/{setting}`.

    UpdateUserSetting updates the user setting.

    Args:
        user: The user id.
        setting: The setting id.
        update_mask: Required. The list of fields to update.
        name: The name of the user setting. Format: users/{user}/settings/{setting}, {setting}
            is the key for the setting. For example, "users/steven/settings/GENERAL" for
            general settings.
        general_setting: General user settings configuration.
        webhooks_setting: User webhooks configuration.
        tags_setting: User-specific tag metadata.
    """

    _resp = sdk_request_sync(
        "PATCH",
        f"/api/v1/users/{encode_path_segment(user)}/settings/{encode_path_segment(setting)}",
        params=serialize_query([("updateMask", update_mask, "form", True)]),
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "generalSetting": (
                    NOT_GIVEN
                    if general_setting is NOT_GIVEN
                    else to_wire(general_setting, "UserSetting_GeneralSetting")
                ),
                "webhooksSetting": (
                    NOT_GIVEN
                    if webhooks_setting is NOT_GIVEN
                    else to_wire(webhooks_setting, "UserSetting_WebhooksSetting")
                ),
                "tagsSetting": (
                    NOT_GIVEN
                    if tags_setting is NOT_GIVEN
                    else to_wire(tags_setting, "UserSetting_TagsSetting")
                ),
            }
        ),
        operation_id="user_service_update_user_setting",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UserSetting"), UserSetting
    )


UserServiceListMemoViewsError: TypeAlias = Status


async def user_service_list_memo_views(
    _client_config: ClientConfig,
    user: str,
    *,
    request_options: RequestOptions | None = None,
) -> ListMemoViewsResponse:
    """Lists a user's saved memo views, each of which stores a reusable CEL filter. Use a
    view's `filter` value as the `filter` argument when listing memos. The list contains
    the saved views for the specified user.

    ListMemoViews returns a user's memo views. Each view is a named, reusable CEL filter
    (see MemoView.filter); pass its filter string directly to the ListMemos `filter`
    argument.

    Args:
        user: The user id.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v1/users/{encode_path_segment(user)}/views",
        operation_id="user_service_list_memo_views",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListMemoViewsResponse"), ListMemoViewsResponse
    )


def user_service_list_memo_views_sync(
    _client_config: ClientConfig,
    user: str,
    *,
    request_options: RequestOptions | None = None,
) -> ListMemoViewsResponse:
    """Lists a user's saved memo views, each of which stores a reusable CEL filter. Use a
    view's `filter` value as the `filter` argument when listing memos. The list contains
    the saved views for the specified user.

    ListMemoViews returns a user's memo views. Each view is a named, reusable CEL filter
    (see MemoView.filter); pass its filter string directly to the ListMemos `filter`
    argument.

    Args:
        user: The user id.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v1/users/{encode_path_segment(user)}/views",
        operation_id="user_service_list_memo_views",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListMemoViewsResponse"), ListMemoViewsResponse
    )


UserServiceCreateMemoViewError: TypeAlias = Status


async def user_service_create_memo_view(
    _client_config: ClientConfig,
    user: str,
    title: str,
    filter: str,
    validate_only: bool | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    icon: MemoView_Icon | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> MemoView:
    """Creates a saved memo view for a user. Provide the required `title` and CEL `filter`
    expression; you can optionally provide a display `icon`. Set `validateOnly` to
    validate the request without creating the view.

    CreateMemoView creates a new memo view for a user.

    Args:
        user: The user id.
        title: The title of the memo view.
        filter: The CEL filter expression for the memo view, using the same grammar as the
            ListMemos `filter` argument. Reuse it by passing this value to ListMemos.
        validate_only: Optional. If set, validate the request, but do not actually create the memo
            view.
        name: The resource name of the memo view. Format: users/{user}/views/{view}
        icon: Optional. Display icon. Omit when updating with the "icon" mask to reset to the
            default view icon.
    """

    _resp = await sdk_request(
        "POST",
        f"/api/v1/users/{encode_path_segment(user)}/views",
        params=serialize_query([("validateOnly", validate_only, "form", True)]),
        json=omit_unset(
            {
                "title": (NOT_GIVEN if title is NOT_GIVEN else to_wire(title, "str")),
                "filter": (NOT_GIVEN if filter is NOT_GIVEN else to_wire(filter, "str")),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "icon": (NOT_GIVEN if icon is NOT_GIVEN else to_wire(icon, "MemoView_Icon")),
            }
        ),
        operation_id="user_service_create_memo_view",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_validate_response_enums(_resp.data, "MemoView"), MemoView)


def user_service_create_memo_view_sync(
    _client_config: ClientConfig,
    user: str,
    title: str,
    filter: str,
    validate_only: bool | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    icon: MemoView_Icon | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> MemoView:
    """Creates a saved memo view for a user. Provide the required `title` and CEL `filter`
    expression; you can optionally provide a display `icon`. Set `validateOnly` to
    validate the request without creating the view.

    CreateMemoView creates a new memo view for a user.

    Args:
        user: The user id.
        title: The title of the memo view.
        filter: The CEL filter expression for the memo view, using the same grammar as the
            ListMemos `filter` argument. Reuse it by passing this value to ListMemos.
        validate_only: Optional. If set, validate the request, but do not actually create the memo
            view.
        name: The resource name of the memo view. Format: users/{user}/views/{view}
        icon: Optional. Display icon. Omit when updating with the "icon" mask to reset to the
            default view icon.
    """

    _resp = sdk_request_sync(
        "POST",
        f"/api/v1/users/{encode_path_segment(user)}/views",
        params=serialize_query([("validateOnly", validate_only, "form", True)]),
        json=omit_unset(
            {
                "title": (NOT_GIVEN if title is NOT_GIVEN else to_wire(title, "str")),
                "filter": (NOT_GIVEN if filter is NOT_GIVEN else to_wire(filter, "str")),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "icon": (NOT_GIVEN if icon is NOT_GIVEN else to_wire(icon, "MemoView_Icon")),
            }
        ),
        operation_id="user_service_create_memo_view",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_validate_response_enums(_resp.data, "MemoView"), MemoView)


UserServiceGetMemoViewError: TypeAlias = Status


async def user_service_get_memo_view(
    _client_config: ClientConfig,
    user: str,
    view: str,
    *,
    request_options: RequestOptions | None = None,
) -> MemoView:
    """Retrieves a saved memo view by name. Provide the user ID and view ID to identify the
    view. The response includes the saved view's CEL filter, which you can pass to the
    ListMemos `filter` argument.

    GetMemoView gets a memo view by name.

    Args:
        user: The user id.
        view: The view id.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v1/users/{encode_path_segment(user)}/views/{encode_path_segment(view)}",
        operation_id="user_service_get_memo_view",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_validate_response_enums(_resp.data, "MemoView"), MemoView)


def user_service_get_memo_view_sync(
    _client_config: ClientConfig,
    user: str,
    view: str,
    *,
    request_options: RequestOptions | None = None,
) -> MemoView:
    """Retrieves a saved memo view by name. Provide the user ID and view ID to identify the
    view. The response includes the saved view's CEL filter, which you can pass to the
    ListMemos `filter` argument.

    GetMemoView gets a memo view by name.

    Args:
        user: The user id.
        view: The view id.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v1/users/{encode_path_segment(user)}/views/{encode_path_segment(view)}",
        operation_id="user_service_get_memo_view",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_validate_response_enums(_resp.data, "MemoView"), MemoView)


UserServiceDeleteMemoViewError: TypeAlias = Status


async def user_service_delete_memo_view(
    _client_config: ClientConfig,
    user: str,
    view: str,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Deletes a saved memo view for a user. Identify the user and the view to remove with
    the `user` and `view` path parameters.

    DeleteMemoView deletes a memo view for a user.

    Args:
        user: The user id.
        view: The view id.
    """

    _resp = await sdk_request(
        "DELETE",
        f"/api/v1/users/{encode_path_segment(user)}/views/{encode_path_segment(view)}",
        operation_id="user_service_delete_memo_view",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


def user_service_delete_memo_view_sync(
    _client_config: ClientConfig,
    user: str,
    view: str,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Deletes a saved memo view for a user. Identify the user and the view to remove with
    the `user` and `view` path parameters.

    DeleteMemoView deletes a memo view for a user.

    Args:
        user: The user id.
        view: The view id.
    """

    _resp = sdk_request_sync(
        "DELETE",
        f"/api/v1/users/{encode_path_segment(user)}/views/{encode_path_segment(view)}",
        operation_id="user_service_delete_memo_view",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


__all__ = [
    "UserServiceCreateMemoViewError",
    "UserServiceDeleteMemoViewError",
    "UserServiceGetMemoViewError",
    "UserServiceGetUserSettingError",
    "UserServiceListMemoViewsError",
    "UserServiceUpdateUserSettingError",
    "user_service_create_memo_view",
    "user_service_create_memo_view_sync",
    "user_service_delete_memo_view",
    "user_service_delete_memo_view_sync",
    "user_service_get_memo_view",
    "user_service_get_memo_view_sync",
    "user_service_get_user_setting",
    "user_service_get_user_setting_sync",
    "user_service_list_memo_views",
    "user_service_list_memo_views_sync",
    "user_service_update_user_setting",
    "user_service_update_user_setting_sync",
]
