# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime
from typing import Any, Literal, TypeAlias

from pydantic import TypeAdapter

import memos_unofficial_sdk.types as _response_types
from memos_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    encode_path_segment,
    omit_unset,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from memos_unofficial_sdk.types import (
    LinkedIdentity,
    ListLinkedIdentitiesResponse,
    ListUserNotificationsResponse,
    Status,
    User,
)
from memos_unofficial_sdk.validation import validate_date_time
from memos_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


UserServiceUpdateUserError: TypeAlias = Status


async def user_service_update_user(
    _client_config: ClientConfig,
    user: str,
    role: Literal["ROLE_UNSPECIFIED", "ADMIN", "USER"] | str,
    username: str,
    state: Literal["STATE_UNSPECIFIED", "NORMAL", "ARCHIVED"] | str,
    update_mask: str | NotGiven = NOT_GIVEN,
    allow_missing: bool | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    email: str | NotGiven = NOT_GIVEN,
    display_name: str | NotGiven = NOT_GIVEN,
    avatar_url: str | NotGiven = NOT_GIVEN,
    description: str | NotGiven = NOT_GIVEN,
    password: str | NotGiven = NOT_GIVEN,
    create_time: datetime.datetime | NotGiven = NOT_GIVEN,
    update_time: datetime.datetime | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> User:
    """Updates a user's fields using a partial update. Supply the user resource name and an
    `updateMask` to select the fields being updated; the request body schema requires
    `role`, `username`, and `state`.

    UpdateUser updates a user.

    Args:
        user: The user id.
        role: The role of the user.
        username: Required. The unique username for login.
        state: The state of the user.
        update_mask: Required. The list of fields to update.
        allow_missing: Optional. If set to true, allows updating sensitive fields.
        name: The resource name of the user. Format: users/{user}
        email: Optional. The email address of the user. Stored trimmed and lowercased; empty
            means no address. An address belongs to at most one user on the instance, so
            writes that would reuse one fail with ALREADY_EXISTS.
        display_name: Optional. The display name of the user.
        avatar_url: Optional. The avatar URL of the user.
        description: Optional. The description of the user.
        password: Input only. The password for the user.
        create_time: Output only. The creation timestamp.
        update_time: Output only. The last update timestamp.
    """

    if not isinstance(create_time, NotGiven) and create_time is not None:
        validate_date_time("createTime", create_time)

    if not isinstance(update_time, NotGiven) and update_time is not None:
        validate_date_time("updateTime", update_time)

    _resp = await sdk_request(
        "PATCH",
        f"/api/v1/users/{encode_path_segment(user)}",
        params=serialize_query(
            [
                ("updateMask", update_mask, "form", True),
                ("allowMissing", allow_missing, "form", True),
            ]
        ),
        json=omit_unset(
            {
                "role": (
                    NOT_GIVEN
                    if role is NOT_GIVEN
                    else to_wire(role, 'Literal["ROLE_UNSPECIFIED", "ADMIN", "USER"] | str')
                ),
                "username": (NOT_GIVEN if username is NOT_GIVEN else to_wire(username, "str")),
                "state": (
                    NOT_GIVEN
                    if state is NOT_GIVEN
                    else to_wire(state, 'Literal["STATE_UNSPECIFIED", "NORMAL", "ARCHIVED"] | str')
                ),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "email": (NOT_GIVEN if email is NOT_GIVEN else to_wire(email, "str")),
                "displayName": (
                    NOT_GIVEN if display_name is NOT_GIVEN else to_wire(display_name, "str")
                ),
                "avatarUrl": (NOT_GIVEN if avatar_url is NOT_GIVEN else to_wire(avatar_url, "str")),
                "description": (
                    NOT_GIVEN if description is NOT_GIVEN else to_wire(description, "str")
                ),
                "password": (NOT_GIVEN if password is NOT_GIVEN else to_wire(password, "str")),
                "createTime": (
                    NOT_GIVEN
                    if create_time is NOT_GIVEN
                    else to_wire(create_time, "datetime.datetime")
                ),
                "updateTime": (
                    NOT_GIVEN
                    if update_time is NOT_GIVEN
                    else to_wire(update_time, "datetime.datetime")
                ),
            }
        ),
        operation_id="user_service_update_user",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_validate_response_enums(_resp.data, "User"), User)


def user_service_update_user_sync(
    _client_config: ClientConfig,
    user: str,
    role: Literal["ROLE_UNSPECIFIED", "ADMIN", "USER"] | str,
    username: str,
    state: Literal["STATE_UNSPECIFIED", "NORMAL", "ARCHIVED"] | str,
    update_mask: str | NotGiven = NOT_GIVEN,
    allow_missing: bool | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    email: str | NotGiven = NOT_GIVEN,
    display_name: str | NotGiven = NOT_GIVEN,
    avatar_url: str | NotGiven = NOT_GIVEN,
    description: str | NotGiven = NOT_GIVEN,
    password: str | NotGiven = NOT_GIVEN,
    create_time: datetime.datetime | NotGiven = NOT_GIVEN,
    update_time: datetime.datetime | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> User:
    """Updates a user's fields using a partial update. Supply the user resource name and an
    `updateMask` to select the fields being updated; the request body schema requires
    `role`, `username`, and `state`.

    UpdateUser updates a user.

    Args:
        user: The user id.
        role: The role of the user.
        username: Required. The unique username for login.
        state: The state of the user.
        update_mask: Required. The list of fields to update.
        allow_missing: Optional. If set to true, allows updating sensitive fields.
        name: The resource name of the user. Format: users/{user}
        email: Optional. The email address of the user. Stored trimmed and lowercased; empty
            means no address. An address belongs to at most one user on the instance, so
            writes that would reuse one fail with ALREADY_EXISTS.
        display_name: Optional. The display name of the user.
        avatar_url: Optional. The avatar URL of the user.
        description: Optional. The description of the user.
        password: Input only. The password for the user.
        create_time: Output only. The creation timestamp.
        update_time: Output only. The last update timestamp.
    """

    if not isinstance(create_time, NotGiven) and create_time is not None:
        validate_date_time("createTime", create_time)

    if not isinstance(update_time, NotGiven) and update_time is not None:
        validate_date_time("updateTime", update_time)

    _resp = sdk_request_sync(
        "PATCH",
        f"/api/v1/users/{encode_path_segment(user)}",
        params=serialize_query(
            [
                ("updateMask", update_mask, "form", True),
                ("allowMissing", allow_missing, "form", True),
            ]
        ),
        json=omit_unset(
            {
                "role": (
                    NOT_GIVEN
                    if role is NOT_GIVEN
                    else to_wire(role, 'Literal["ROLE_UNSPECIFIED", "ADMIN", "USER"] | str')
                ),
                "username": (NOT_GIVEN if username is NOT_GIVEN else to_wire(username, "str")),
                "state": (
                    NOT_GIVEN
                    if state is NOT_GIVEN
                    else to_wire(state, 'Literal["STATE_UNSPECIFIED", "NORMAL", "ARCHIVED"] | str')
                ),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "email": (NOT_GIVEN if email is NOT_GIVEN else to_wire(email, "str")),
                "displayName": (
                    NOT_GIVEN if display_name is NOT_GIVEN else to_wire(display_name, "str")
                ),
                "avatarUrl": (NOT_GIVEN if avatar_url is NOT_GIVEN else to_wire(avatar_url, "str")),
                "description": (
                    NOT_GIVEN if description is NOT_GIVEN else to_wire(description, "str")
                ),
                "password": (NOT_GIVEN if password is NOT_GIVEN else to_wire(password, "str")),
                "createTime": (
                    NOT_GIVEN
                    if create_time is NOT_GIVEN
                    else to_wire(create_time, "datetime.datetime")
                ),
                "updateTime": (
                    NOT_GIVEN
                    if update_time is NOT_GIVEN
                    else to_wire(update_time, "datetime.datetime")
                ),
            }
        ),
        operation_id="user_service_update_user",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_validate_response_enums(_resp.data, "User"), User)


UserServiceListLinkedIdentitiesError: TypeAlias = Status


async def user_service_list_linked_identities(
    _client_config: ClientConfig,
    user: str,
    *,
    request_options: RequestOptions | None = None,
) -> ListLinkedIdentitiesResponse:
    """Lists the linked SSO identities for a user. Supply the user's identifier to retrieve
    the identities associated with that account.

    ListLinkedIdentities returns a list of linked SSO identities for a user.

    Args:
        user: The user id.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v1/users/{encode_path_segment(user)}/linkedIdentities",
        operation_id="user_service_list_linked_identities",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListLinkedIdentitiesResponse"),
        ListLinkedIdentitiesResponse,
    )


def user_service_list_linked_identities_sync(
    _client_config: ClientConfig,
    user: str,
    *,
    request_options: RequestOptions | None = None,
) -> ListLinkedIdentitiesResponse:
    """Lists the linked SSO identities for a user. Supply the user's identifier to retrieve
    the identities associated with that account.

    ListLinkedIdentities returns a list of linked SSO identities for a user.

    Args:
        user: The user id.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v1/users/{encode_path_segment(user)}/linkedIdentities",
        operation_id="user_service_list_linked_identities",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListLinkedIdentitiesResponse"),
        ListLinkedIdentitiesResponse,
    )


UserServiceCreateLinkedIdentityError: TypeAlias = Status


async def user_service_create_linked_identity(
    _client_config: ClientConfig,
    user: str,
    parent: str,
    idp_name: str,
    code: str,
    redirect_uri: str,
    code_verifier: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> LinkedIdentity:
    """Links an SSO identity to a user through an identity provider's OAuth flow. Provide
    the parent user, identity provider, authorization code, and redirect URI; include
    `codeVerifier` when the flow uses PKCE.

    CreateLinkedIdentity links an SSO identity to the authenticated user.

    Args:
        user: The user id.
        parent: Required. The parent user who owns the linked identity. Format: users/{user}
        idp_name: Required. The identity provider to link. Format: identity-providers/{idp}
        code: Required. The authorization code from the identity provider.
        redirect_uri: Required. The redirect URI used in the OAuth flow.
        code_verifier: Optional. The PKCE code verifier used in the OAuth flow.
    """

    _resp = await sdk_request(
        "POST",
        f"/api/v1/users/{encode_path_segment(user)}/linkedIdentities",
        json=omit_unset(
            {
                "parent": (NOT_GIVEN if parent is NOT_GIVEN else to_wire(parent, "str")),
                "idpName": (NOT_GIVEN if idp_name is NOT_GIVEN else to_wire(idp_name, "str")),
                "code": (NOT_GIVEN if code is NOT_GIVEN else to_wire(code, "str")),
                "redirectUri": (
                    NOT_GIVEN if redirect_uri is NOT_GIVEN else to_wire(redirect_uri, "str")
                ),
                "codeVerifier": (
                    NOT_GIVEN if code_verifier is NOT_GIVEN else to_wire(code_verifier, "str")
                ),
            }
        ),
        operation_id="user_service_create_linked_identity",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "LinkedIdentity"), LinkedIdentity
    )


def user_service_create_linked_identity_sync(
    _client_config: ClientConfig,
    user: str,
    parent: str,
    idp_name: str,
    code: str,
    redirect_uri: str,
    code_verifier: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> LinkedIdentity:
    """Links an SSO identity to a user through an identity provider's OAuth flow. Provide
    the parent user, identity provider, authorization code, and redirect URI; include
    `codeVerifier` when the flow uses PKCE.

    CreateLinkedIdentity links an SSO identity to the authenticated user.

    Args:
        user: The user id.
        parent: Required. The parent user who owns the linked identity. Format: users/{user}
        idp_name: Required. The identity provider to link. Format: identity-providers/{idp}
        code: Required. The authorization code from the identity provider.
        redirect_uri: Required. The redirect URI used in the OAuth flow.
        code_verifier: Optional. The PKCE code verifier used in the OAuth flow.
    """

    _resp = sdk_request_sync(
        "POST",
        f"/api/v1/users/{encode_path_segment(user)}/linkedIdentities",
        json=omit_unset(
            {
                "parent": (NOT_GIVEN if parent is NOT_GIVEN else to_wire(parent, "str")),
                "idpName": (NOT_GIVEN if idp_name is NOT_GIVEN else to_wire(idp_name, "str")),
                "code": (NOT_GIVEN if code is NOT_GIVEN else to_wire(code, "str")),
                "redirectUri": (
                    NOT_GIVEN if redirect_uri is NOT_GIVEN else to_wire(redirect_uri, "str")
                ),
                "codeVerifier": (
                    NOT_GIVEN if code_verifier is NOT_GIVEN else to_wire(code_verifier, "str")
                ),
            }
        ),
        operation_id="user_service_create_linked_identity",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "LinkedIdentity"), LinkedIdentity
    )


UserServiceGetLinkedIdentityError: TypeAlias = Status


async def user_service_get_linked_identity(
    _client_config: ClientConfig,
    user: str,
    linked_identity: str,
    *,
    request_options: RequestOptions | None = None,
) -> LinkedIdentity:
    """Retrieves a linked SSO identity for a user. Supply both resource identifiers to
    retrieve the identity associated with that user account.

    GetLinkedIdentity gets a linked SSO identity for a user.

    Args:
        user: The user id.
        linked_identity: The linkedIdentity id.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v1/users/{encode_path_segment(user)}/linkedIdentities/{encode_path_segment(linked_identity)}",
        operation_id="user_service_get_linked_identity",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "LinkedIdentity"), LinkedIdentity
    )


def user_service_get_linked_identity_sync(
    _client_config: ClientConfig,
    user: str,
    linked_identity: str,
    *,
    request_options: RequestOptions | None = None,
) -> LinkedIdentity:
    """Retrieves a linked SSO identity for a user. Supply both resource identifiers to
    retrieve the identity associated with that user account.

    GetLinkedIdentity gets a linked SSO identity for a user.

    Args:
        user: The user id.
        linked_identity: The linkedIdentity id.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v1/users/{encode_path_segment(user)}/linkedIdentities/{encode_path_segment(linked_identity)}",
        operation_id="user_service_get_linked_identity",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "LinkedIdentity"), LinkedIdentity
    )


UserServiceDeleteLinkedIdentityError: TypeAlias = Status


async def user_service_delete_linked_identity(
    _client_config: ClientConfig,
    user: str,
    linked_identity: str,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Deletes a linked SSO identity from a user account. Supply the user and linked
    identity identifiers for the identity you want to unlink.

    DeleteLinkedIdentity unlinks an SSO identity from a user.

    Args:
        user: The user id.
        linked_identity: The linkedIdentity id.
    """

    _resp = await sdk_request(
        "DELETE",
        f"/api/v1/users/{encode_path_segment(user)}/linkedIdentities/{encode_path_segment(linked_identity)}",
        operation_id="user_service_delete_linked_identity",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


def user_service_delete_linked_identity_sync(
    _client_config: ClientConfig,
    user: str,
    linked_identity: str,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Deletes a linked SSO identity from a user account. Supply the user and linked
    identity identifiers for the identity you want to unlink.

    DeleteLinkedIdentity unlinks an SSO identity from a user.

    Args:
        user: The user id.
        linked_identity: The linkedIdentity id.
    """

    _resp = sdk_request_sync(
        "DELETE",
        f"/api/v1/users/{encode_path_segment(user)}/linkedIdentities/{encode_path_segment(linked_identity)}",
        operation_id="user_service_delete_linked_identity",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


UserServiceListUserNotificationsError: TypeAlias = Status


async def user_service_list_user_notifications(
    _client_config: ClientConfig,
    user: str,
    page_size: int | NotGiven = NOT_GIVEN,
    page_token: str | NotGiven = NOT_GIVEN,
    filter: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ListUserNotificationsResponse:
    """Lists notifications for a user. Use `pageSize` to control the number of results and
    `pageToken` to continue through paginated results; optionally use `filter` to narrow
    the list.

    ListUserNotifications lists notifications for a user.

    Args:
        user: The user id.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v1/users/{encode_path_segment(user)}/notifications",
        params=serialize_query(
            [
                ("pageSize", page_size, "form", True),
                ("pageToken", page_token, "form", True),
                ("filter", filter, "form", True),
            ]
        ),
        operation_id="user_service_list_user_notifications",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListUserNotificationsResponse"),
        ListUserNotificationsResponse,
    )


def user_service_list_user_notifications_sync(
    _client_config: ClientConfig,
    user: str,
    page_size: int | NotGiven = NOT_GIVEN,
    page_token: str | NotGiven = NOT_GIVEN,
    filter: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ListUserNotificationsResponse:
    """Lists notifications for a user. Use `pageSize` to control the number of results and
    `pageToken` to continue through paginated results; optionally use `filter` to narrow
    the list.

    ListUserNotifications lists notifications for a user.

    Args:
        user: The user id.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v1/users/{encode_path_segment(user)}/notifications",
        params=serialize_query(
            [
                ("pageSize", page_size, "form", True),
                ("pageToken", page_token, "form", True),
                ("filter", filter, "form", True),
            ]
        ),
        operation_id="user_service_list_user_notifications",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListUserNotificationsResponse"),
        ListUserNotificationsResponse,
    )


__all__ = [
    "UserServiceCreateLinkedIdentityError",
    "UserServiceDeleteLinkedIdentityError",
    "UserServiceGetLinkedIdentityError",
    "UserServiceListLinkedIdentitiesError",
    "UserServiceListUserNotificationsError",
    "UserServiceUpdateUserError",
    "user_service_create_linked_identity",
    "user_service_create_linked_identity_sync",
    "user_service_delete_linked_identity",
    "user_service_delete_linked_identity_sync",
    "user_service_get_linked_identity",
    "user_service_get_linked_identity_sync",
    "user_service_list_linked_identities",
    "user_service_list_linked_identities_sync",
    "user_service_list_user_notifications",
    "user_service_list_user_notifications_sync",
    "user_service_update_user",
    "user_service_update_user_sync",
]
