# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime
from typing import Any, TypeAlias

from pydantic import TypeAdapter

import memos_unofficial_sdk.types as _response_types
from memos_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    encode_path_segment,
    omit_unset,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from memos_unofficial_sdk.types import (
    ListUserWebhooksResponse,
    MemoView,
    MemoView_Icon,
    Status,
    UserWebhook,
)
from memos_unofficial_sdk.validation import validate_date_time
from memos_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


UserServiceUpdateMemoViewError: TypeAlias = Status


async def user_service_update_memo_view(
    _client_config: ClientConfig,
    user: str,
    view: str,
    title: str,
    filter: str,
    update_mask: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    icon: MemoView_Icon | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> MemoView:
    """Updates a saved memo view for a user. Supply `title` and `filter`; `filter` uses the
    CEL grammar accepted by ListMemos, and `updateMask` limits which fields change.
    Include `icon` in the update mask and omit its value to reset the view icon to the
    default.

    UpdateMemoView updates a memo view for a user.

    Args:
        user: The user id.
        view: The view id.
        title: The title of the memo view.
        filter: The CEL filter expression for the memo view, using the same grammar as the
            ListMemos `filter` argument. Reuse it by passing this value to ListMemos.
        update_mask: Optional. The list of fields to update.
        name: The resource name of the memo view. Format: users/{user}/views/{view}
        icon: Optional. Display icon. Omit when updating with the "icon" mask to reset to the
            default view icon.
    """

    _resp = await sdk_request(
        "PATCH",
        f"/api/v1/users/{encode_path_segment(user)}/views/{encode_path_segment(view)}",
        params=serialize_query([("updateMask", update_mask, "form", True)]),
        json=omit_unset(
            {
                "title": (NOT_GIVEN if title is NOT_GIVEN else to_wire(title, "str")),
                "filter": (NOT_GIVEN if filter is NOT_GIVEN else to_wire(filter, "str")),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "icon": (NOT_GIVEN if icon is NOT_GIVEN else to_wire(icon, "MemoView_Icon")),
            }
        ),
        operation_id="user_service_update_memo_view",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_validate_response_enums(_resp.data, "MemoView"), MemoView)


def user_service_update_memo_view_sync(
    _client_config: ClientConfig,
    user: str,
    view: str,
    title: str,
    filter: str,
    update_mask: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    icon: MemoView_Icon | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> MemoView:
    """Updates a saved memo view for a user. Supply `title` and `filter`; `filter` uses the
    CEL grammar accepted by ListMemos, and `updateMask` limits which fields change.
    Include `icon` in the update mask and omit its value to reset the view icon to the
    default.

    UpdateMemoView updates a memo view for a user.

    Args:
        user: The user id.
        view: The view id.
        title: The title of the memo view.
        filter: The CEL filter expression for the memo view, using the same grammar as the
            ListMemos `filter` argument. Reuse it by passing this value to ListMemos.
        update_mask: Optional. The list of fields to update.
        name: The resource name of the memo view. Format: users/{user}/views/{view}
        icon: Optional. Display icon. Omit when updating with the "icon" mask to reset to the
            default view icon.
    """

    _resp = sdk_request_sync(
        "PATCH",
        f"/api/v1/users/{encode_path_segment(user)}/views/{encode_path_segment(view)}",
        params=serialize_query([("updateMask", update_mask, "form", True)]),
        json=omit_unset(
            {
                "title": (NOT_GIVEN if title is NOT_GIVEN else to_wire(title, "str")),
                "filter": (NOT_GIVEN if filter is NOT_GIVEN else to_wire(filter, "str")),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "icon": (NOT_GIVEN if icon is NOT_GIVEN else to_wire(icon, "MemoView_Icon")),
            }
        ),
        operation_id="user_service_update_memo_view",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_validate_response_enums(_resp.data, "MemoView"), MemoView)


UserServiceListUserWebhooksError: TypeAlias = Status


async def user_service_list_user_webhooks(
    _client_config: ClientConfig,
    user: str,
    *,
    request_options: RequestOptions | None = None,
) -> ListUserWebhooksResponse:
    """Lists the webhooks owned by a user. Use the `user` path parameter to select whose
    webhooks to retrieve; the results include webhook configuration and whether a
    signing secret is set.

    ListUserWebhooks returns a list of webhooks for a user.

    Args:
        user: The user id.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v1/users/{encode_path_segment(user)}/webhooks",
        operation_id="user_service_list_user_webhooks",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListUserWebhooksResponse"), ListUserWebhooksResponse
    )


def user_service_list_user_webhooks_sync(
    _client_config: ClientConfig,
    user: str,
    *,
    request_options: RequestOptions | None = None,
) -> ListUserWebhooksResponse:
    """Lists the webhooks owned by a user. Use the `user` path parameter to select whose
    webhooks to retrieve; the results include webhook configuration and whether a
    signing secret is set.

    ListUserWebhooks returns a list of webhooks for a user.

    Args:
        user: The user id.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v1/users/{encode_path_segment(user)}/webhooks",
        operation_id="user_service_list_user_webhooks",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListUserWebhooksResponse"), ListUserWebhooksResponse
    )


UserServiceCreateUserWebhookError: TypeAlias = Status


async def user_service_create_user_webhook(
    _client_config: ClientConfig,
    user: str,
    name: str | NotGiven = NOT_GIVEN,
    url: str | NotGiven = NOT_GIVEN,
    display_name: str | NotGiven = NOT_GIVEN,
    create_time: datetime.datetime | NotGiven = NOT_GIVEN,
    update_time: datetime.datetime | NotGiven = NOT_GIVEN,
    signing_secret: str | NotGiven = NOT_GIVEN,
    signing_secret_set: bool | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UserWebhook:
    """Creates a webhook for a user. Provide the destination `url` and, if needed, a
    `signingSecret` for HMAC-SHA256 signing; the secret is not included in the response.
    The `name` field uses the `users/{user}/webhooks/{webhook}` resource-name format.

    CreateUserWebhook creates a new webhook for a user.

    Args:
        user: The user id.
        name: The name of the webhook. Format: users/{user}/webhooks/{webhook}
        url: The URL to send the webhook to.
        display_name: Optional. Human-readable name for the webhook.
        create_time: The creation time of the webhook.
        update_time: The last update time of the webhook.
        signing_secret: Optional. Signing secret used to HMAC-SHA256 sign the webhook request body. This
            field is input-only; it is never returned in responses.
        signing_secret_set: Whether a signing secret is configured for this webhook.
    """

    if not isinstance(create_time, NotGiven) and create_time is not None:
        validate_date_time("createTime", create_time)

    if not isinstance(update_time, NotGiven) and update_time is not None:
        validate_date_time("updateTime", update_time)

    _resp = await sdk_request(
        "POST",
        f"/api/v1/users/{encode_path_segment(user)}/webhooks",
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "url": (NOT_GIVEN if url is NOT_GIVEN else to_wire(url, "str")),
                "displayName": (
                    NOT_GIVEN if display_name is NOT_GIVEN else to_wire(display_name, "str")
                ),
                "createTime": (
                    NOT_GIVEN
                    if create_time is NOT_GIVEN
                    else to_wire(create_time, "datetime.datetime")
                ),
                "updateTime": (
                    NOT_GIVEN
                    if update_time is NOT_GIVEN
                    else to_wire(update_time, "datetime.datetime")
                ),
                "signingSecret": (
                    NOT_GIVEN if signing_secret is NOT_GIVEN else to_wire(signing_secret, "str")
                ),
                "signingSecretSet": (
                    NOT_GIVEN
                    if signing_secret_set is NOT_GIVEN
                    else to_wire(signing_secret_set, "bool")
                ),
            }
        ),
        operation_id="user_service_create_user_webhook",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UserWebhook"), UserWebhook
    )


def user_service_create_user_webhook_sync(
    _client_config: ClientConfig,
    user: str,
    name: str | NotGiven = NOT_GIVEN,
    url: str | NotGiven = NOT_GIVEN,
    display_name: str | NotGiven = NOT_GIVEN,
    create_time: datetime.datetime | NotGiven = NOT_GIVEN,
    update_time: datetime.datetime | NotGiven = NOT_GIVEN,
    signing_secret: str | NotGiven = NOT_GIVEN,
    signing_secret_set: bool | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UserWebhook:
    """Creates a webhook for a user. Provide the destination `url` and, if needed, a
    `signingSecret` for HMAC-SHA256 signing; the secret is not included in the response.
    The `name` field uses the `users/{user}/webhooks/{webhook}` resource-name format.

    CreateUserWebhook creates a new webhook for a user.

    Args:
        user: The user id.
        name: The name of the webhook. Format: users/{user}/webhooks/{webhook}
        url: The URL to send the webhook to.
        display_name: Optional. Human-readable name for the webhook.
        create_time: The creation time of the webhook.
        update_time: The last update time of the webhook.
        signing_secret: Optional. Signing secret used to HMAC-SHA256 sign the webhook request body. This
            field is input-only; it is never returned in responses.
        signing_secret_set: Whether a signing secret is configured for this webhook.
    """

    if not isinstance(create_time, NotGiven) and create_time is not None:
        validate_date_time("createTime", create_time)

    if not isinstance(update_time, NotGiven) and update_time is not None:
        validate_date_time("updateTime", update_time)

    _resp = sdk_request_sync(
        "POST",
        f"/api/v1/users/{encode_path_segment(user)}/webhooks",
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "url": (NOT_GIVEN if url is NOT_GIVEN else to_wire(url, "str")),
                "displayName": (
                    NOT_GIVEN if display_name is NOT_GIVEN else to_wire(display_name, "str")
                ),
                "createTime": (
                    NOT_GIVEN
                    if create_time is NOT_GIVEN
                    else to_wire(create_time, "datetime.datetime")
                ),
                "updateTime": (
                    NOT_GIVEN
                    if update_time is NOT_GIVEN
                    else to_wire(update_time, "datetime.datetime")
                ),
                "signingSecret": (
                    NOT_GIVEN if signing_secret is NOT_GIVEN else to_wire(signing_secret, "str")
                ),
                "signingSecretSet": (
                    NOT_GIVEN
                    if signing_secret_set is NOT_GIVEN
                    else to_wire(signing_secret_set, "bool")
                ),
            }
        ),
        operation_id="user_service_create_user_webhook",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UserWebhook"), UserWebhook
    )


UserServiceDeleteUserWebhookError: TypeAlias = Status


async def user_service_delete_user_webhook(
    _client_config: ClientConfig,
    user: str,
    webhook: str,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Deletes a webhook owned by a user. Identify the owner and the webhook to remove with
    the `user` and `webhook` path parameters.

    DeleteUserWebhook deletes a webhook for a user.

    Args:
        user: The user id.
        webhook: The webhook id.
    """

    _resp = await sdk_request(
        "DELETE",
        f"/api/v1/users/{encode_path_segment(user)}/webhooks/{encode_path_segment(webhook)}",
        operation_id="user_service_delete_user_webhook",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


def user_service_delete_user_webhook_sync(
    _client_config: ClientConfig,
    user: str,
    webhook: str,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Deletes a webhook owned by a user. Identify the owner and the webhook to remove with
    the `user` and `webhook` path parameters.

    DeleteUserWebhook deletes a webhook for a user.

    Args:
        user: The user id.
        webhook: The webhook id.
    """

    _resp = sdk_request_sync(
        "DELETE",
        f"/api/v1/users/{encode_path_segment(user)}/webhooks/{encode_path_segment(webhook)}",
        operation_id="user_service_delete_user_webhook",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


UserServiceUpdateUserWebhookError: TypeAlias = Status


async def user_service_update_user_webhook(
    _client_config: ClientConfig,
    user: str,
    webhook: str,
    update_mask: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    url: str | NotGiven = NOT_GIVEN,
    display_name: str | NotGiven = NOT_GIVEN,
    create_time: datetime.datetime | NotGiven = NOT_GIVEN,
    update_time: datetime.datetime | NotGiven = NOT_GIVEN,
    signing_secret: str | NotGiven = NOT_GIVEN,
    signing_secret_set: bool | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UserWebhook:
    """Updates an existing webhook for a user. Use `updateMask` to identify the fields to
    change, and provide a `signingSecret` when you need to set or change the secret used
    to sign webhook requests. The `name` field uses the
    `users/{user}/webhooks/{webhook}` resource-name format.

    UpdateUserWebhook updates an existing webhook for a user.

    Args:
        user: The user id.
        webhook: The webhook id.
        update_mask: The list of fields to update.
        name: The name of the webhook. Format: users/{user}/webhooks/{webhook}
        url: The URL to send the webhook to.
        display_name: Optional. Human-readable name for the webhook.
        create_time: The creation time of the webhook.
        update_time: The last update time of the webhook.
        signing_secret: Optional. Signing secret used to HMAC-SHA256 sign the webhook request body. This
            field is input-only; it is never returned in responses.
        signing_secret_set: Whether a signing secret is configured for this webhook.
    """

    if not isinstance(create_time, NotGiven) and create_time is not None:
        validate_date_time("createTime", create_time)

    if not isinstance(update_time, NotGiven) and update_time is not None:
        validate_date_time("updateTime", update_time)

    _resp = await sdk_request(
        "PATCH",
        f"/api/v1/users/{encode_path_segment(user)}/webhooks/{encode_path_segment(webhook)}",
        params=serialize_query([("updateMask", update_mask, "form", True)]),
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "url": (NOT_GIVEN if url is NOT_GIVEN else to_wire(url, "str")),
                "displayName": (
                    NOT_GIVEN if display_name is NOT_GIVEN else to_wire(display_name, "str")
                ),
                "createTime": (
                    NOT_GIVEN
                    if create_time is NOT_GIVEN
                    else to_wire(create_time, "datetime.datetime")
                ),
                "updateTime": (
                    NOT_GIVEN
                    if update_time is NOT_GIVEN
                    else to_wire(update_time, "datetime.datetime")
                ),
                "signingSecret": (
                    NOT_GIVEN if signing_secret is NOT_GIVEN else to_wire(signing_secret, "str")
                ),
                "signingSecretSet": (
                    NOT_GIVEN
                    if signing_secret_set is NOT_GIVEN
                    else to_wire(signing_secret_set, "bool")
                ),
            }
        ),
        operation_id="user_service_update_user_webhook",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UserWebhook"), UserWebhook
    )


def user_service_update_user_webhook_sync(
    _client_config: ClientConfig,
    user: str,
    webhook: str,
    update_mask: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    url: str | NotGiven = NOT_GIVEN,
    display_name: str | NotGiven = NOT_GIVEN,
    create_time: datetime.datetime | NotGiven = NOT_GIVEN,
    update_time: datetime.datetime | NotGiven = NOT_GIVEN,
    signing_secret: str | NotGiven = NOT_GIVEN,
    signing_secret_set: bool | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UserWebhook:
    """Updates an existing webhook for a user. Use `updateMask` to identify the fields to
    change, and provide a `signingSecret` when you need to set or change the secret used
    to sign webhook requests. The `name` field uses the
    `users/{user}/webhooks/{webhook}` resource-name format.

    UpdateUserWebhook updates an existing webhook for a user.

    Args:
        user: The user id.
        webhook: The webhook id.
        update_mask: The list of fields to update.
        name: The name of the webhook. Format: users/{user}/webhooks/{webhook}
        url: The URL to send the webhook to.
        display_name: Optional. Human-readable name for the webhook.
        create_time: The creation time of the webhook.
        update_time: The last update time of the webhook.
        signing_secret: Optional. Signing secret used to HMAC-SHA256 sign the webhook request body. This
            field is input-only; it is never returned in responses.
        signing_secret_set: Whether a signing secret is configured for this webhook.
    """

    if not isinstance(create_time, NotGiven) and create_time is not None:
        validate_date_time("createTime", create_time)

    if not isinstance(update_time, NotGiven) and update_time is not None:
        validate_date_time("updateTime", update_time)

    _resp = sdk_request_sync(
        "PATCH",
        f"/api/v1/users/{encode_path_segment(user)}/webhooks/{encode_path_segment(webhook)}",
        params=serialize_query([("updateMask", update_mask, "form", True)]),
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "url": (NOT_GIVEN if url is NOT_GIVEN else to_wire(url, "str")),
                "displayName": (
                    NOT_GIVEN if display_name is NOT_GIVEN else to_wire(display_name, "str")
                ),
                "createTime": (
                    NOT_GIVEN
                    if create_time is NOT_GIVEN
                    else to_wire(create_time, "datetime.datetime")
                ),
                "updateTime": (
                    NOT_GIVEN
                    if update_time is NOT_GIVEN
                    else to_wire(update_time, "datetime.datetime")
                ),
                "signingSecret": (
                    NOT_GIVEN if signing_secret is NOT_GIVEN else to_wire(signing_secret, "str")
                ),
                "signingSecretSet": (
                    NOT_GIVEN
                    if signing_secret_set is NOT_GIVEN
                    else to_wire(signing_secret_set, "bool")
                ),
            }
        ),
        operation_id="user_service_update_user_webhook",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UserWebhook"), UserWebhook
    )


__all__ = [
    "UserServiceCreateUserWebhookError",
    "UserServiceDeleteUserWebhookError",
    "UserServiceListUserWebhooksError",
    "UserServiceUpdateMemoViewError",
    "UserServiceUpdateUserWebhookError",
    "user_service_create_user_webhook",
    "user_service_create_user_webhook_sync",
    "user_service_delete_user_webhook",
    "user_service_delete_user_webhook_sync",
    "user_service_list_user_webhooks",
    "user_service_list_user_webhooks_sync",
    "user_service_update_memo_view",
    "user_service_update_memo_view_sync",
    "user_service_update_user_webhook",
    "user_service_update_user_webhook_sync",
]
