# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any, Literal, TypeAlias

from pydantic import TypeAdapter

import memos_unofficial_sdk.types as _response_types
from memos_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    encode_path_segment,
    omit_unset,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from memos_unofficial_sdk.types import (
    BatchGetUsersResponse,
    GetUserWebhookSigningSecretResponse,
    ImportMemosResponse,
    ImportMemosSpec,
    ListAllUserStatsResponse,
    Status,
    UserStats,
)
from memos_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


UserServiceGetUserWebhookSigningSecretError: TypeAlias = Status


async def user_service_get_user_webhook_signing_secret(
    _client_config: ClientConfig,
    user: str,
    webhook: str,
    *,
    request_options: RequestOptions | None = None,
) -> GetUserWebhookSigningSecretResponse:
    """Retrieves the signing secret for a user's webhook through an explicit, owner-gated
    call. Use this operation when you need the secret; it is not included in webhook
    list, create, or update responses.

    GetUserWebhookSigningSecret returns the signing secret for a webhook. The secret is
    returned only through this explicit, owner-gated call; it is never included in
    List/Create/Update responses.

    Args:
        user: The user id.
        webhook: The webhook id.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v1/users/{encode_path_segment(user)}/webhooks/{encode_path_segment(webhook)}:getSigningSecret",
        operation_id="user_service_get_user_webhook_signing_secret",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetUserWebhookSigningSecretResponse"),
        GetUserWebhookSigningSecretResponse,
    )


def user_service_get_user_webhook_signing_secret_sync(
    _client_config: ClientConfig,
    user: str,
    webhook: str,
    *,
    request_options: RequestOptions | None = None,
) -> GetUserWebhookSigningSecretResponse:
    """Retrieves the signing secret for a user's webhook through an explicit, owner-gated
    call. Use this operation when you need the secret; it is not included in webhook
    list, create, or update responses.

    GetUserWebhookSigningSecret returns the signing secret for a webhook. The secret is
    returned only through this explicit, owner-gated call; it is never included in
    List/Create/Update responses.

    Args:
        user: The user id.
        webhook: The webhook id.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v1/users/{encode_path_segment(user)}/webhooks/{encode_path_segment(webhook)}:getSigningSecret",
        operation_id="user_service_get_user_webhook_signing_secret",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetUserWebhookSigningSecretResponse"),
        GetUserWebhookSigningSecretResponse,
    )


UserServiceExportMemosError: TypeAlias = Status


async def user_service_export_memos(
    _client_config: ClientConfig,
    user: str,
    *,
    request_options: RequestOptions | None = None,
) -> Any:
    """Exports the authenticated user's memos as a ZIP archive, including comments,
    archived memos, and attachment files. The `user` path parameter must identify the
    authenticated user; the response body is the archive, and its media type is provided
    as `content_type`.

    ExportMemos writes every memo the user created, with comments, archived memos, and
    attachment files, as a Memos export file (a ZIP file, see
    docs/design/memos-export-format.md). Only the user may export their own memos. The
    body is the archive; content_type is its media type.

    Args:
        user: The user id.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v1/users/{encode_path_segment(user)}:exportMemos",
        operation_id="user_service_export_memos",
        response_decoder="bytes",
        request_options=request_options,
        config=_client_config,
    )
    return _resp.data


def user_service_export_memos_sync(
    _client_config: ClientConfig,
    user: str,
    *,
    request_options: RequestOptions | None = None,
) -> Any:
    """Exports the authenticated user's memos as a ZIP archive, including comments,
    archived memos, and attachment files. The `user` path parameter must identify the
    authenticated user; the response body is the archive, and its media type is provided
    as `content_type`.

    ExportMemos writes every memo the user created, with comments, archived memos, and
    attachment files, as a Memos export file (a ZIP file, see
    docs/design/memos-export-format.md). Only the user may export their own memos. The
    body is the archive; content_type is its media type.

    Args:
        user: The user id.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v1/users/{encode_path_segment(user)}:exportMemos",
        operation_id="user_service_export_memos",
        response_decoder="bytes",
        request_options=request_options,
        config=_client_config,
    )
    return _resp.data


UserServiceGetUserStatsError: TypeAlias = Status


async def user_service_get_user_stats(
    _client_config: ClientConfig,
    user: str,
    filter: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UserStats:
    """Retrieves statistics for a specific user, including memo counts, tag counts, memo
    timestamps, and pinned memos. Use `filter` to select readable non-comment memos
    using a CEL expression compatible with ListMemos.

    GetUserStats returns statistics for a specific user.

    Args:
        user: The user id.
        filter: Optional. CEL expression selecting the readable non-comment memos to include.
            Supports the same fields as ListMemos, including `space`.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v1/users/{encode_path_segment(user)}:getStats",
        params=serialize_query([("filter", filter, "form", True)]),
        operation_id="user_service_get_user_stats",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_validate_response_enums(_resp.data, "UserStats"), UserStats)


def user_service_get_user_stats_sync(
    _client_config: ClientConfig,
    user: str,
    filter: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UserStats:
    """Retrieves statistics for a specific user, including memo counts, tag counts, memo
    timestamps, and pinned memos. Use `filter` to select readable non-comment memos
    using a CEL expression compatible with ListMemos.

    GetUserStats returns statistics for a specific user.

    Args:
        user: The user id.
        filter: Optional. CEL expression selecting the readable non-comment memos to include.
            Supports the same fields as ListMemos, including `space`.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v1/users/{encode_path_segment(user)}:getStats",
        params=serialize_query([("filter", filter, "form", True)]),
        operation_id="user_service_get_user_stats",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_validate_response_enums(_resp.data, "UserStats"), UserStats)


UserServiceImportMemosError: TypeAlias = Status


async def user_service_import_memos(
    _client_config: ClientConfig,
    user: str,
    name: str,
    write_offset: str,
    spec: ImportMemosSpec | NotGiven = NOT_GIVEN,
    upload_id: str | NotGiven = NOT_GIVEN,
    data: str | NotGiven = NOT_GIVEN,
    finish_write: bool | NotGiven = NOT_GIVEN,
    validate_only: bool | NotGiven = NOT_GIVEN,
    conflict_policy: Literal["CONFLICT_POLICY_UNSPECIFIED", "SKIP", "REPLACE", "DUPLICATE"]
    | str
    | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ImportMemosResponse:
    """Imports a Memos export archive into a user's memos through bounded chunk uploads.
    Start with `spec`, then use the returned `uploadId` for subsequent chunks; a
    finishing call can validate the archive without importing it or import it and return
    a report. Uploads are bound to the authenticated user and expire after 30 minutes of
    inactivity.

    ImportMemos uploads a Memos export file in bounded chunks and imports it into the
    user's memos. The first call carries the spec and returns an upload_id; later calls
    carry that upload_id. A finishing call with validate_only returns the plan and keeps
    the archive staged; a finishing call without it imports and returns the report.
    Uploads are bound to the authenticated user, expire after 30 minutes of inactivity,
    and do not survive a server restart.

    Args:
        user: The user id.
        name: Required. The user who receives the memos. Must be the caller. Format:
            users/{user}
        write_offset: Required. Zero-based byte offset at which data is written. Must equal the
            committed size, except when retrying the most recently accepted chunk with
            identical bytes and offset, which is accepted without writing again.
        spec: Starts a new upload. The same call may also carry data and finish_write.
        upload_id: Continues the upload identified by a previous response.
        data: Optional. Archive bytes, at most max_chunk_size long. With no data and
            finish_write false, the call reports progress without writing, and write_offset
            is ignored.
        finish_write: Optional. Finish the upload after writing data. The committed size must then
            equal total_size. The archive is validated and, unless validate_only is set,
            imported. Any later call for an imported upload returns the same report.
        validate_only: Optional. On a finishing call, validate the archive and return the plan without
            importing. The upload stays staged so a later finishing call can import it.
        conflict_policy: Optional. Read on the finishing call that imports. Unspecified means SKIP.
    """

    _resp = await sdk_request(
        "POST",
        f"/api/v1/users/{encode_path_segment(user)}:importMemos",
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "writeOffset": (
                    NOT_GIVEN if write_offset is NOT_GIVEN else to_wire(write_offset, "str")
                ),
                "spec": (NOT_GIVEN if spec is NOT_GIVEN else to_wire(spec, "ImportMemosSpec")),
                "uploadId": (NOT_GIVEN if upload_id is NOT_GIVEN else to_wire(upload_id, "str")),
                "data": (NOT_GIVEN if data is NOT_GIVEN else to_wire(data, "str")),
                "finishWrite": (
                    NOT_GIVEN if finish_write is NOT_GIVEN else to_wire(finish_write, "bool")
                ),
                "validateOnly": (
                    NOT_GIVEN if validate_only is NOT_GIVEN else to_wire(validate_only, "bool")
                ),
                "conflictPolicy": (
                    NOT_GIVEN
                    if conflict_policy is NOT_GIVEN
                    else to_wire(
                        conflict_policy,
                        'Literal["CONFLICT_POLICY_UNSPECIFIED", "SKIP", "REPLACE", "DUPLICATE"] | str',
                    )
                ),
            }
        ),
        operation_id="user_service_import_memos",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ImportMemosResponse"), ImportMemosResponse
    )


def user_service_import_memos_sync(
    _client_config: ClientConfig,
    user: str,
    name: str,
    write_offset: str,
    spec: ImportMemosSpec | NotGiven = NOT_GIVEN,
    upload_id: str | NotGiven = NOT_GIVEN,
    data: str | NotGiven = NOT_GIVEN,
    finish_write: bool | NotGiven = NOT_GIVEN,
    validate_only: bool | NotGiven = NOT_GIVEN,
    conflict_policy: Literal["CONFLICT_POLICY_UNSPECIFIED", "SKIP", "REPLACE", "DUPLICATE"]
    | str
    | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ImportMemosResponse:
    """Imports a Memos export archive into a user's memos through bounded chunk uploads.
    Start with `spec`, then use the returned `uploadId` for subsequent chunks; a
    finishing call can validate the archive without importing it or import it and return
    a report. Uploads are bound to the authenticated user and expire after 30 minutes of
    inactivity.

    ImportMemos uploads a Memos export file in bounded chunks and imports it into the
    user's memos. The first call carries the spec and returns an upload_id; later calls
    carry that upload_id. A finishing call with validate_only returns the plan and keeps
    the archive staged; a finishing call without it imports and returns the report.
    Uploads are bound to the authenticated user, expire after 30 minutes of inactivity,
    and do not survive a server restart.

    Args:
        user: The user id.
        name: Required. The user who receives the memos. Must be the caller. Format:
            users/{user}
        write_offset: Required. Zero-based byte offset at which data is written. Must equal the
            committed size, except when retrying the most recently accepted chunk with
            identical bytes and offset, which is accepted without writing again.
        spec: Starts a new upload. The same call may also carry data and finish_write.
        upload_id: Continues the upload identified by a previous response.
        data: Optional. Archive bytes, at most max_chunk_size long. With no data and
            finish_write false, the call reports progress without writing, and write_offset
            is ignored.
        finish_write: Optional. Finish the upload after writing data. The committed size must then
            equal total_size. The archive is validated and, unless validate_only is set,
            imported. Any later call for an imported upload returns the same report.
        validate_only: Optional. On a finishing call, validate the archive and return the plan without
            importing. The upload stays staged so a later finishing call can import it.
        conflict_policy: Optional. Read on the finishing call that imports. Unspecified means SKIP.
    """

    _resp = sdk_request_sync(
        "POST",
        f"/api/v1/users/{encode_path_segment(user)}:importMemos",
        json=omit_unset(
            {
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "writeOffset": (
                    NOT_GIVEN if write_offset is NOT_GIVEN else to_wire(write_offset, "str")
                ),
                "spec": (NOT_GIVEN if spec is NOT_GIVEN else to_wire(spec, "ImportMemosSpec")),
                "uploadId": (NOT_GIVEN if upload_id is NOT_GIVEN else to_wire(upload_id, "str")),
                "data": (NOT_GIVEN if data is NOT_GIVEN else to_wire(data, "str")),
                "finishWrite": (
                    NOT_GIVEN if finish_write is NOT_GIVEN else to_wire(finish_write, "bool")
                ),
                "validateOnly": (
                    NOT_GIVEN if validate_only is NOT_GIVEN else to_wire(validate_only, "bool")
                ),
                "conflictPolicy": (
                    NOT_GIVEN
                    if conflict_policy is NOT_GIVEN
                    else to_wire(
                        conflict_policy,
                        'Literal["CONFLICT_POLICY_UNSPECIFIED", "SKIP", "REPLACE", "DUPLICATE"] | str',
                    )
                ),
            }
        ),
        operation_id="user_service_import_memos",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ImportMemosResponse"), ImportMemosResponse
    )


UserServiceBatchGetUsersError: TypeAlias = Status


async def user_service_batch_get_users(
    _client_config: ClientConfig,
    usernames: list[str] | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> BatchGetUsersResponse:
    """Lists active users matching the supplied usernames. Provide `usernames` as an array
    of strings to identify the users to look up. The response contains the matching user
    records.

    BatchGetUsers returns active users by usernames.

    Args:
        usernames: Optional array value serialized in the `usernames` wire field.
    """

    _resp = await sdk_request(
        "POST",
        "/api/v1/users:batchGet",
        json=omit_unset(
            {
                "usernames": (
                    NOT_GIVEN if usernames is NOT_GIVEN else to_wire(usernames, "list[str]")
                ),
            }
        ),
        operation_id="user_service_batch_get_users",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "BatchGetUsersResponse"), BatchGetUsersResponse
    )


def user_service_batch_get_users_sync(
    _client_config: ClientConfig,
    usernames: list[str] | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> BatchGetUsersResponse:
    """Lists active users matching the supplied usernames. Provide `usernames` as an array
    of strings to identify the users to look up. The response contains the matching user
    records.

    BatchGetUsers returns active users by usernames.

    Args:
        usernames: Optional array value serialized in the `usernames` wire field.
    """

    _resp = sdk_request_sync(
        "POST",
        "/api/v1/users:batchGet",
        json=omit_unset(
            {
                "usernames": (
                    NOT_GIVEN if usernames is NOT_GIVEN else to_wire(usernames, "list[str]")
                ),
            }
        ),
        operation_id="user_service_batch_get_users",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "BatchGetUsersResponse"), BatchGetUsersResponse
    )


UserServiceListAllUserStatsError: TypeAlias = Status


async def user_service_list_all_user_stats(
    _client_config: ClientConfig,
    state: Literal["STATE_UNSPECIFIED", "NORMAL", "ARCHIVED"] | str | NotGiven = NOT_GIVEN,
    filter: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ListAllUserStatsResponse:
    """Lists statistics for users, optionally scoped by memo state and filtered using the
    `ListMemos` filter syntax. `state` defaults to `NORMAL` and accepts
    `STATE_UNSPECIFIED`, `NORMAL`, or `ARCHIVED`.

    ListAllUserStats returns statistics for all users.

    Args:
        state: Optional. The state of memos to include. Defaults to NORMAL.
        filter: Optional. Filter to apply to memo stats. Uses the same filter syntax as
            ListMemos.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v1/users:stats",
        params=serialize_query([("state", state, "form", True), ("filter", filter, "form", True)]),
        operation_id="user_service_list_all_user_stats",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListAllUserStatsResponse"), ListAllUserStatsResponse
    )


def user_service_list_all_user_stats_sync(
    _client_config: ClientConfig,
    state: Literal["STATE_UNSPECIFIED", "NORMAL", "ARCHIVED"] | str | NotGiven = NOT_GIVEN,
    filter: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ListAllUserStatsResponse:
    """Lists statistics for users, optionally scoped by memo state and filtered using the
    `ListMemos` filter syntax. `state` defaults to `NORMAL` and accepts
    `STATE_UNSPECIFIED`, `NORMAL`, or `ARCHIVED`.

    ListAllUserStats returns statistics for all users.

    Args:
        state: Optional. The state of memos to include. Defaults to NORMAL.
        filter: Optional. Filter to apply to memo stats. Uses the same filter syntax as
            ListMemos.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v1/users:stats",
        params=serialize_query([("state", state, "form", True), ("filter", filter, "form", True)]),
        operation_id="user_service_list_all_user_stats",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListAllUserStatsResponse"), ListAllUserStatsResponse
    )


__all__ = [
    "UserServiceBatchGetUsersError",
    "UserServiceExportMemosError",
    "UserServiceGetUserStatsError",
    "UserServiceGetUserWebhookSigningSecretError",
    "UserServiceImportMemosError",
    "UserServiceListAllUserStatsError",
    "user_service_batch_get_users",
    "user_service_batch_get_users_sync",
    "user_service_export_memos",
    "user_service_export_memos_sync",
    "user_service_get_user_stats",
    "user_service_get_user_stats_sync",
    "user_service_get_user_webhook_signing_secret",
    "user_service_get_user_webhook_signing_secret_sync",
    "user_service_import_memos",
    "user_service_import_memos_sync",
    "user_service_list_all_user_stats",
    "user_service_list_all_user_stats_sync",
]
