# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from ._part001 import (
    AttachmentServiceCreateAttachmentError,
    AttachmentServiceDeleteAttachmentError,
    AttachmentServiceGetAttachmentError,
    AttachmentServiceListAttachmentsError,
    AttachmentServiceUpdateAttachmentError,
    attachment_service_create_attachment,
    attachment_service_create_attachment_sync,
    attachment_service_delete_attachment,
    attachment_service_delete_attachment_sync,
    attachment_service_get_attachment,
    attachment_service_get_attachment_sync,
    attachment_service_list_attachments,
    attachment_service_list_attachments_sync,
    attachment_service_update_attachment,
    attachment_service_update_attachment_sync,
)
from ._part002 import (
    AttachmentServiceBatchDeleteAttachmentsError,
    AttachmentServiceUploadAttachmentError,
    attachment_service_batch_delete_attachments,
    attachment_service_batch_delete_attachments_sync,
    attachment_service_upload_attachment,
    attachment_service_upload_attachment_sync,
)

__all__ = [
    "AttachmentServiceBatchDeleteAttachmentsError",
    "AttachmentServiceCreateAttachmentError",
    "AttachmentServiceDeleteAttachmentError",
    "AttachmentServiceGetAttachmentError",
    "AttachmentServiceListAttachmentsError",
    "AttachmentServiceUpdateAttachmentError",
    "AttachmentServiceUploadAttachmentError",
    "attachment_service_batch_delete_attachments",
    "attachment_service_batch_delete_attachments_sync",
    "attachment_service_create_attachment",
    "attachment_service_create_attachment_sync",
    "attachment_service_delete_attachment",
    "attachment_service_delete_attachment_sync",
    "attachment_service_get_attachment",
    "attachment_service_get_attachment_sync",
    "attachment_service_list_attachments",
    "attachment_service_list_attachments_sync",
    "attachment_service_update_attachment",
    "attachment_service_update_attachment_sync",
    "attachment_service_upload_attachment",
    "attachment_service_upload_attachment_sync",
]
