# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime
from typing import Any, TypeAlias

from pydantic import TypeAdapter

import memos_unofficial_sdk.types as _response_types
from memos_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    encode_path_segment,
    omit_unset,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from memos_unofficial_sdk.types import (
    Attachment,
    ListAttachmentsResponse,
    MediaMetadata,
    MotionMedia,
    Status,
)
from memos_unofficial_sdk.validation import validate_date_time
from memos_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


AttachmentServiceListAttachmentsError: TypeAlias = Status


async def attachment_service_list_attachments(
    _client_config: ClientConfig,
    page_size: int | NotGiven = NOT_GIVEN,
    page_token: str | NotGiven = NOT_GIVEN,
    filter: str | NotGiven = NOT_GIVEN,
    order_by: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ListAttachmentsResponse:
    """Lists attachments linked to readable memos and unlinked uploads belonging to the
    authenticated user. Use `filter` to narrow the results and `orderBy` to sort them;
    use `pageToken` to retrieve subsequent pages.

    ListAttachments lists attachments linked to readable memos and the caller's unlinked
    uploads.

    Args:
        page_size: Optional. The maximum number of attachments to return. The service may return
            fewer than this value. If unspecified, at most 50 attachments will be returned.
            The maximum value is 1000; values above 1000 will be coerced to 1000.
        page_token: Optional. A page token, received from a previous `ListAttachments` call. Provide
            this to retrieve the subsequent page.
        filter: Optional. Filter to apply to the list results. Example:
            "mime_type==\\"image/png\\"" or "filename.contains(\\"test\\")" Supported operators:
            =, !=, <, <=, >, >=, : (contains), in Supported fields: creator, filename,
            mime_type, create_time, memo_id, space. `creator` is the linked memo's creator,
            or the uploader for an unlinked attachment. It supports equality with a User
            resource name. `space` only supports a non-negated `==` comparison with a Space
            resource name or null. `space` is the linked memo's space resource name, or null
            when the attachment is unlinked or its linked memo has no space.
        order_by: Optional. The order to sort results by. Example: "create_time desc" or "filename
            asc"
    """

    _resp = await sdk_request(
        "GET",
        "/api/v1/attachments",
        params=serialize_query(
            [
                ("pageSize", page_size, "form", True),
                ("pageToken", page_token, "form", True),
                ("filter", filter, "form", True),
                ("orderBy", order_by, "form", True),
            ]
        ),
        operation_id="attachment_service_list_attachments",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListAttachmentsResponse"), ListAttachmentsResponse
    )


def attachment_service_list_attachments_sync(
    _client_config: ClientConfig,
    page_size: int | NotGiven = NOT_GIVEN,
    page_token: str | NotGiven = NOT_GIVEN,
    filter: str | NotGiven = NOT_GIVEN,
    order_by: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ListAttachmentsResponse:
    """Lists attachments linked to readable memos and unlinked uploads belonging to the
    authenticated user. Use `filter` to narrow the results and `orderBy` to sort them;
    use `pageToken` to retrieve subsequent pages.

    ListAttachments lists attachments linked to readable memos and the caller's unlinked
    uploads.

    Args:
        page_size: Optional. The maximum number of attachments to return. The service may return
            fewer than this value. If unspecified, at most 50 attachments will be returned.
            The maximum value is 1000; values above 1000 will be coerced to 1000.
        page_token: Optional. A page token, received from a previous `ListAttachments` call. Provide
            this to retrieve the subsequent page.
        filter: Optional. Filter to apply to the list results. Example:
            "mime_type==\\"image/png\\"" or "filename.contains(\\"test\\")" Supported operators:
            =, !=, <, <=, >, >=, : (contains), in Supported fields: creator, filename,
            mime_type, create_time, memo_id, space. `creator` is the linked memo's creator,
            or the uploader for an unlinked attachment. It supports equality with a User
            resource name. `space` only supports a non-negated `==` comparison with a Space
            resource name or null. `space` is the linked memo's space resource name, or null
            when the attachment is unlinked or its linked memo has no space.
        order_by: Optional. The order to sort results by. Example: "create_time desc" or "filename
            asc"
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v1/attachments",
        params=serialize_query(
            [
                ("pageSize", page_size, "form", True),
                ("pageToken", page_token, "form", True),
                ("filter", filter, "form", True),
                ("orderBy", order_by, "form", True),
            ]
        ),
        operation_id="attachment_service_list_attachments",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListAttachmentsResponse"), ListAttachmentsResponse
    )


AttachmentServiceCreateAttachmentError: TypeAlias = Status


async def attachment_service_create_attachment(
    _client_config: ClientConfig,
    filename: str,
    type: str,
    attachment_id: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    create_time: datetime.datetime | NotGiven = NOT_GIVEN,
    content: str | NotGiven = NOT_GIVEN,
    external_link: str | NotGiven = NOT_GIVEN,
    size: str | NotGiven = NOT_GIVEN,
    memo: str | NotGiven = NOT_GIVEN,
    motion_media: MotionMedia | NotGiven = NOT_GIVEN,
    media_metadata: MediaMetadata | NotGiven = NOT_GIVEN,
    creator: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Attachment:
    """Creates a new attachment. Supply the required `filename` and `type`, and optionally
    associate the attachment with a memo using `memo`. Set `attachmentId` to choose an
    ID, or omit it to have one generated.

    CreateAttachment creates a new attachment.

    Args:
        filename: The filename of the attachment.
        type: The MIME type of the attachment.
        attachment_id: Optional. The attachment ID to use for this attachment. If empty, a unique ID
            will be generated. Format: ^[a-zA-Z0-9]([a-zA-Z0-9-]{0,34}[a-zA-Z0-9])?$
        name: The name of the attachment. Format: attachments/{attachment}
        create_time: Output only. The creation timestamp.
        content: Input only. The content of the attachment.
        external_link: Optional. The external link of the attachment.
        size: Output only. The size of the attachment in bytes.
        memo: Optional. The related memo. Refer to `Memo.name`. Format: memos/{memo}
        motion_media: Optional. Motion media metadata.
        media_metadata: Optional. Immutable normalized media metadata explicitly supplied by the client
            at creation time.
        creator: Output only. The user who uploaded this attachment, which may differ from the
            creator of the linked memo. Format: users/{user}.
    """

    if not isinstance(create_time, NotGiven) and create_time is not None:
        validate_date_time("createTime", create_time)

    _resp = await sdk_request(
        "POST",
        "/api/v1/attachments",
        params=serialize_query([("attachmentId", attachment_id, "form", True)]),
        json=omit_unset(
            {
                "filename": (NOT_GIVEN if filename is NOT_GIVEN else to_wire(filename, "str")),
                "type": (NOT_GIVEN if type is NOT_GIVEN else to_wire(type, "str")),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "createTime": (
                    NOT_GIVEN
                    if create_time is NOT_GIVEN
                    else to_wire(create_time, "datetime.datetime")
                ),
                "content": (NOT_GIVEN if content is NOT_GIVEN else to_wire(content, "str")),
                "externalLink": (
                    NOT_GIVEN if external_link is NOT_GIVEN else to_wire(external_link, "str")
                ),
                "size": (NOT_GIVEN if size is NOT_GIVEN else to_wire(size, "str")),
                "memo": (NOT_GIVEN if memo is NOT_GIVEN else to_wire(memo, "str")),
                "motionMedia": (
                    NOT_GIVEN if motion_media is NOT_GIVEN else to_wire(motion_media, "MotionMedia")
                ),
                "mediaMetadata": (
                    NOT_GIVEN
                    if media_metadata is NOT_GIVEN
                    else to_wire(media_metadata, "MediaMetadata")
                ),
                "creator": (NOT_GIVEN if creator is NOT_GIVEN else to_wire(creator, "str")),
            }
        ),
        operation_id="attachment_service_create_attachment",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "Attachment"), Attachment
    )


def attachment_service_create_attachment_sync(
    _client_config: ClientConfig,
    filename: str,
    type: str,
    attachment_id: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    create_time: datetime.datetime | NotGiven = NOT_GIVEN,
    content: str | NotGiven = NOT_GIVEN,
    external_link: str | NotGiven = NOT_GIVEN,
    size: str | NotGiven = NOT_GIVEN,
    memo: str | NotGiven = NOT_GIVEN,
    motion_media: MotionMedia | NotGiven = NOT_GIVEN,
    media_metadata: MediaMetadata | NotGiven = NOT_GIVEN,
    creator: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Attachment:
    """Creates a new attachment. Supply the required `filename` and `type`, and optionally
    associate the attachment with a memo using `memo`. Set `attachmentId` to choose an
    ID, or omit it to have one generated.

    CreateAttachment creates a new attachment.

    Args:
        filename: The filename of the attachment.
        type: The MIME type of the attachment.
        attachment_id: Optional. The attachment ID to use for this attachment. If empty, a unique ID
            will be generated. Format: ^[a-zA-Z0-9]([a-zA-Z0-9-]{0,34}[a-zA-Z0-9])?$
        name: The name of the attachment. Format: attachments/{attachment}
        create_time: Output only. The creation timestamp.
        content: Input only. The content of the attachment.
        external_link: Optional. The external link of the attachment.
        size: Output only. The size of the attachment in bytes.
        memo: Optional. The related memo. Refer to `Memo.name`. Format: memos/{memo}
        motion_media: Optional. Motion media metadata.
        media_metadata: Optional. Immutable normalized media metadata explicitly supplied by the client
            at creation time.
        creator: Output only. The user who uploaded this attachment, which may differ from the
            creator of the linked memo. Format: users/{user}.
    """

    if not isinstance(create_time, NotGiven) and create_time is not None:
        validate_date_time("createTime", create_time)

    _resp = sdk_request_sync(
        "POST",
        "/api/v1/attachments",
        params=serialize_query([("attachmentId", attachment_id, "form", True)]),
        json=omit_unset(
            {
                "filename": (NOT_GIVEN if filename is NOT_GIVEN else to_wire(filename, "str")),
                "type": (NOT_GIVEN if type is NOT_GIVEN else to_wire(type, "str")),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "createTime": (
                    NOT_GIVEN
                    if create_time is NOT_GIVEN
                    else to_wire(create_time, "datetime.datetime")
                ),
                "content": (NOT_GIVEN if content is NOT_GIVEN else to_wire(content, "str")),
                "externalLink": (
                    NOT_GIVEN if external_link is NOT_GIVEN else to_wire(external_link, "str")
                ),
                "size": (NOT_GIVEN if size is NOT_GIVEN else to_wire(size, "str")),
                "memo": (NOT_GIVEN if memo is NOT_GIVEN else to_wire(memo, "str")),
                "motionMedia": (
                    NOT_GIVEN if motion_media is NOT_GIVEN else to_wire(motion_media, "MotionMedia")
                ),
                "mediaMetadata": (
                    NOT_GIVEN
                    if media_metadata is NOT_GIVEN
                    else to_wire(media_metadata, "MediaMetadata")
                ),
                "creator": (NOT_GIVEN if creator is NOT_GIVEN else to_wire(creator, "str")),
            }
        ),
        operation_id="attachment_service_create_attachment",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "Attachment"), Attachment
    )


AttachmentServiceGetAttachmentError: TypeAlias = Status


async def attachment_service_get_attachment(
    _client_config: ClientConfig,
    attachment: str,
    *,
    request_options: RequestOptions | None = None,
) -> Attachment:
    """Retrieves an attachment by its identifier. Use the `attachment` path value to select
    the attachment you want to retrieve.

    GetAttachment returns an attachment by name.

    Args:
        attachment: The attachment id.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v1/attachments/{encode_path_segment(attachment)}",
        operation_id="attachment_service_get_attachment",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "Attachment"), Attachment
    )


def attachment_service_get_attachment_sync(
    _client_config: ClientConfig,
    attachment: str,
    *,
    request_options: RequestOptions | None = None,
) -> Attachment:
    """Retrieves an attachment by its identifier. Use the `attachment` path value to select
    the attachment you want to retrieve.

    GetAttachment returns an attachment by name.

    Args:
        attachment: The attachment id.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v1/attachments/{encode_path_segment(attachment)}",
        operation_id="attachment_service_get_attachment",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "Attachment"), Attachment
    )


AttachmentServiceDeleteAttachmentError: TypeAlias = Status


async def attachment_service_delete_attachment(
    _client_config: ClientConfig,
    attachment: str,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Deletes an attachment by its identifier. Use the `attachment` path value to select
    the attachment to remove.

    DeleteAttachment deletes an attachment by name.

    Args:
        attachment: The attachment id.
    """

    _resp = await sdk_request(
        "DELETE",
        f"/api/v1/attachments/{encode_path_segment(attachment)}",
        operation_id="attachment_service_delete_attachment",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


def attachment_service_delete_attachment_sync(
    _client_config: ClientConfig,
    attachment: str,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Deletes an attachment by its identifier. Use the `attachment` path value to select
    the attachment to remove.

    DeleteAttachment deletes an attachment by name.

    Args:
        attachment: The attachment id.
    """

    _resp = sdk_request_sync(
        "DELETE",
        f"/api/v1/attachments/{encode_path_segment(attachment)}",
        operation_id="attachment_service_delete_attachment",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


AttachmentServiceUpdateAttachmentError: TypeAlias = Status


async def attachment_service_update_attachment(
    _client_config: ClientConfig,
    attachment: str,
    filename: str,
    type: str,
    update_mask: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    create_time: datetime.datetime | NotGiven = NOT_GIVEN,
    content: str | NotGiven = NOT_GIVEN,
    external_link: str | NotGiven = NOT_GIVEN,
    size: str | NotGiven = NOT_GIVEN,
    memo: str | NotGiven = NOT_GIVEN,
    motion_media: MotionMedia | NotGiven = NOT_GIVEN,
    media_metadata: MediaMetadata | NotGiven = NOT_GIVEN,
    creator: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Attachment:
    """Updates an attachment identified by its resource name. Supply the attachment fields
    and use `updateMask` to specify which fields to update. The request body schema
    requires `filename` and `type`.

    UpdateAttachment updates an attachment.

    Args:
        attachment: The attachment id.
        filename: The filename of the attachment.
        type: The MIME type of the attachment.
        update_mask: Required. The list of fields to update.
        name: The name of the attachment. Format: attachments/{attachment}
        create_time: Output only. The creation timestamp.
        content: Input only. The content of the attachment.
        external_link: Optional. The external link of the attachment.
        size: Output only. The size of the attachment in bytes.
        memo: Optional. The related memo. Refer to `Memo.name`. Format: memos/{memo}
        motion_media: Optional. Motion media metadata.
        media_metadata: Optional. Immutable normalized media metadata explicitly supplied by the client
            at creation time.
        creator: Output only. The user who uploaded this attachment, which may differ from the
            creator of the linked memo. Format: users/{user}.
    """

    if not isinstance(create_time, NotGiven) and create_time is not None:
        validate_date_time("createTime", create_time)

    _resp = await sdk_request(
        "PATCH",
        f"/api/v1/attachments/{encode_path_segment(attachment)}",
        params=serialize_query([("updateMask", update_mask, "form", True)]),
        json=omit_unset(
            {
                "filename": (NOT_GIVEN if filename is NOT_GIVEN else to_wire(filename, "str")),
                "type": (NOT_GIVEN if type is NOT_GIVEN else to_wire(type, "str")),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "createTime": (
                    NOT_GIVEN
                    if create_time is NOT_GIVEN
                    else to_wire(create_time, "datetime.datetime")
                ),
                "content": (NOT_GIVEN if content is NOT_GIVEN else to_wire(content, "str")),
                "externalLink": (
                    NOT_GIVEN if external_link is NOT_GIVEN else to_wire(external_link, "str")
                ),
                "size": (NOT_GIVEN if size is NOT_GIVEN else to_wire(size, "str")),
                "memo": (NOT_GIVEN if memo is NOT_GIVEN else to_wire(memo, "str")),
                "motionMedia": (
                    NOT_GIVEN if motion_media is NOT_GIVEN else to_wire(motion_media, "MotionMedia")
                ),
                "mediaMetadata": (
                    NOT_GIVEN
                    if media_metadata is NOT_GIVEN
                    else to_wire(media_metadata, "MediaMetadata")
                ),
                "creator": (NOT_GIVEN if creator is NOT_GIVEN else to_wire(creator, "str")),
            }
        ),
        operation_id="attachment_service_update_attachment",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "Attachment"), Attachment
    )


def attachment_service_update_attachment_sync(
    _client_config: ClientConfig,
    attachment: str,
    filename: str,
    type: str,
    update_mask: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    create_time: datetime.datetime | NotGiven = NOT_GIVEN,
    content: str | NotGiven = NOT_GIVEN,
    external_link: str | NotGiven = NOT_GIVEN,
    size: str | NotGiven = NOT_GIVEN,
    memo: str | NotGiven = NOT_GIVEN,
    motion_media: MotionMedia | NotGiven = NOT_GIVEN,
    media_metadata: MediaMetadata | NotGiven = NOT_GIVEN,
    creator: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Attachment:
    """Updates an attachment identified by its resource name. Supply the attachment fields
    and use `updateMask` to specify which fields to update. The request body schema
    requires `filename` and `type`.

    UpdateAttachment updates an attachment.

    Args:
        attachment: The attachment id.
        filename: The filename of the attachment.
        type: The MIME type of the attachment.
        update_mask: Required. The list of fields to update.
        name: The name of the attachment. Format: attachments/{attachment}
        create_time: Output only. The creation timestamp.
        content: Input only. The content of the attachment.
        external_link: Optional. The external link of the attachment.
        size: Output only. The size of the attachment in bytes.
        memo: Optional. The related memo. Refer to `Memo.name`. Format: memos/{memo}
        motion_media: Optional. Motion media metadata.
        media_metadata: Optional. Immutable normalized media metadata explicitly supplied by the client
            at creation time.
        creator: Output only. The user who uploaded this attachment, which may differ from the
            creator of the linked memo. Format: users/{user}.
    """

    if not isinstance(create_time, NotGiven) and create_time is not None:
        validate_date_time("createTime", create_time)

    _resp = sdk_request_sync(
        "PATCH",
        f"/api/v1/attachments/{encode_path_segment(attachment)}",
        params=serialize_query([("updateMask", update_mask, "form", True)]),
        json=omit_unset(
            {
                "filename": (NOT_GIVEN if filename is NOT_GIVEN else to_wire(filename, "str")),
                "type": (NOT_GIVEN if type is NOT_GIVEN else to_wire(type, "str")),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "createTime": (
                    NOT_GIVEN
                    if create_time is NOT_GIVEN
                    else to_wire(create_time, "datetime.datetime")
                ),
                "content": (NOT_GIVEN if content is NOT_GIVEN else to_wire(content, "str")),
                "externalLink": (
                    NOT_GIVEN if external_link is NOT_GIVEN else to_wire(external_link, "str")
                ),
                "size": (NOT_GIVEN if size is NOT_GIVEN else to_wire(size, "str")),
                "memo": (NOT_GIVEN if memo is NOT_GIVEN else to_wire(memo, "str")),
                "motionMedia": (
                    NOT_GIVEN if motion_media is NOT_GIVEN else to_wire(motion_media, "MotionMedia")
                ),
                "mediaMetadata": (
                    NOT_GIVEN
                    if media_metadata is NOT_GIVEN
                    else to_wire(media_metadata, "MediaMetadata")
                ),
                "creator": (NOT_GIVEN if creator is NOT_GIVEN else to_wire(creator, "str")),
            }
        ),
        operation_id="attachment_service_update_attachment",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "Attachment"), Attachment
    )


__all__ = [
    "AttachmentServiceCreateAttachmentError",
    "AttachmentServiceDeleteAttachmentError",
    "AttachmentServiceGetAttachmentError",
    "AttachmentServiceListAttachmentsError",
    "AttachmentServiceUpdateAttachmentError",
    "attachment_service_create_attachment",
    "attachment_service_create_attachment_sync",
    "attachment_service_delete_attachment",
    "attachment_service_delete_attachment_sync",
    "attachment_service_get_attachment",
    "attachment_service_get_attachment_sync",
    "attachment_service_list_attachments",
    "attachment_service_list_attachments_sync",
    "attachment_service_update_attachment",
    "attachment_service_update_attachment_sync",
]
