# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any, TypeAlias

from pydantic import TypeAdapter

import memos_unofficial_sdk.types as _response_types
from memos_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    omit_unset,
    sdk_request,
    sdk_request_sync,
)
from memos_unofficial_sdk.types import Status, UploadAttachmentResponse, UploadAttachmentSpec
from memos_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


AttachmentServiceBatchDeleteAttachmentsError: TypeAlias = Status


async def attachment_service_batch_delete_attachments(
    _client_config: ClientConfig,
    names: list[str],
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Deletes multiple attachments in one request. Provide their resource names in the
    required `names` array. The operation removes each attachment identified in that
    array.

    BatchDeleteAttachments deletes multiple attachments in one request.

    Args:
        names: Required array value serialized in the `names` wire field.
    """

    _resp = await sdk_request(
        "POST",
        "/api/v1/attachments:batchDelete",
        json=omit_unset(
            {
                "names": (NOT_GIVEN if names is NOT_GIVEN else to_wire(names, "list[str]")),
            }
        ),
        operation_id="attachment_service_batch_delete_attachments",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


def attachment_service_batch_delete_attachments_sync(
    _client_config: ClientConfig,
    names: list[str],
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Deletes multiple attachments in one request. Provide their resource names in the
    required `names` array. The operation removes each attachment identified in that
    array.

    BatchDeleteAttachments deletes multiple attachments in one request.

    Args:
        names: Required array value serialized in the `names` wire field.
    """

    _resp = sdk_request_sync(
        "POST",
        "/api/v1/attachments:batchDelete",
        json=omit_unset(
            {
                "names": (NOT_GIVEN if names is NOT_GIVEN else to_wire(names, "list[str]")),
            }
        ),
        operation_id="attachment_service_batch_delete_attachments",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


AttachmentServiceUploadAttachmentError: TypeAlias = Status


async def attachment_service_upload_attachment(
    _client_config: ClientConfig,
    write_offset: str,
    spec: UploadAttachmentSpec | NotGiven = NOT_GIVEN,
    upload_id: str | NotGiven = NOT_GIVEN,
    data: str | NotGiven = NOT_GIVEN,
    finish_write: bool | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UploadAttachmentResponse:
    """Uploads a file in chunks to create an attachment. Start an upload with `spec`, then
    use the returned `uploadId` to continue; each write must use the current committed
    byte offset. Uploads are bound to the authenticated user, expire after 30 minutes of
    inactivity, and do not survive a server restart.

    UploadAttachment uploads a file in bounded chunks. The first call carries the spec
    and returns an upload_id; later calls carry that upload_id. Uploads are bound to the
    authenticated user, expire after 30 minutes of inactivity, and do not survive a
    server restart.

    Args:
        write_offset: Required. Zero-based byte offset at which data is written. Must equal the
            committed size, except when retrying the most recently accepted chunk with
            identical bytes and offset, which is accepted without writing again.
        spec: Starts a new upload. The same call may also carry data and finish_write.
        upload_id: Continues the upload identified by a previous response.
        data: Optional. File bytes, at most max_chunk_size long. With no data and finish_write
            false, the call reports progress without writing, and write_offset is ignored.
        finish_write: Optional. Finalize the upload after writing data. The committed size must then
            equal total_size. Any later call for the same upload_id returns the created
            attachment.
    """

    _resp = await sdk_request(
        "POST",
        "/api/v1/attachments:upload",
        json=omit_unset(
            {
                "writeOffset": (
                    NOT_GIVEN if write_offset is NOT_GIVEN else to_wire(write_offset, "str")
                ),
                "spec": (NOT_GIVEN if spec is NOT_GIVEN else to_wire(spec, "UploadAttachmentSpec")),
                "uploadId": (NOT_GIVEN if upload_id is NOT_GIVEN else to_wire(upload_id, "str")),
                "data": (NOT_GIVEN if data is NOT_GIVEN else to_wire(data, "str")),
                "finishWrite": (
                    NOT_GIVEN if finish_write is NOT_GIVEN else to_wire(finish_write, "bool")
                ),
            }
        ),
        operation_id="attachment_service_upload_attachment",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UploadAttachmentResponse"), UploadAttachmentResponse
    )


def attachment_service_upload_attachment_sync(
    _client_config: ClientConfig,
    write_offset: str,
    spec: UploadAttachmentSpec | NotGiven = NOT_GIVEN,
    upload_id: str | NotGiven = NOT_GIVEN,
    data: str | NotGiven = NOT_GIVEN,
    finish_write: bool | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UploadAttachmentResponse:
    """Uploads a file in chunks to create an attachment. Start an upload with `spec`, then
    use the returned `uploadId` to continue; each write must use the current committed
    byte offset. Uploads are bound to the authenticated user, expire after 30 minutes of
    inactivity, and do not survive a server restart.

    UploadAttachment uploads a file in bounded chunks. The first call carries the spec
    and returns an upload_id; later calls carry that upload_id. Uploads are bound to the
    authenticated user, expire after 30 minutes of inactivity, and do not survive a
    server restart.

    Args:
        write_offset: Required. Zero-based byte offset at which data is written. Must equal the
            committed size, except when retrying the most recently accepted chunk with
            identical bytes and offset, which is accepted without writing again.
        spec: Starts a new upload. The same call may also carry data and finish_write.
        upload_id: Continues the upload identified by a previous response.
        data: Optional. File bytes, at most max_chunk_size long. With no data and finish_write
            false, the call reports progress without writing, and write_offset is ignored.
        finish_write: Optional. Finalize the upload after writing data. The committed size must then
            equal total_size. Any later call for the same upload_id returns the created
            attachment.
    """

    _resp = sdk_request_sync(
        "POST",
        "/api/v1/attachments:upload",
        json=omit_unset(
            {
                "writeOffset": (
                    NOT_GIVEN if write_offset is NOT_GIVEN else to_wire(write_offset, "str")
                ),
                "spec": (NOT_GIVEN if spec is NOT_GIVEN else to_wire(spec, "UploadAttachmentSpec")),
                "uploadId": (NOT_GIVEN if upload_id is NOT_GIVEN else to_wire(upload_id, "str")),
                "data": (NOT_GIVEN if data is NOT_GIVEN else to_wire(data, "str")),
                "finishWrite": (
                    NOT_GIVEN if finish_write is NOT_GIVEN else to_wire(finish_write, "bool")
                ),
            }
        ),
        operation_id="attachment_service_upload_attachment",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UploadAttachmentResponse"), UploadAttachmentResponse
    )


__all__ = [
    "AttachmentServiceBatchDeleteAttachmentsError",
    "AttachmentServiceUploadAttachmentError",
    "attachment_service_batch_delete_attachments",
    "attachment_service_batch_delete_attachments_sync",
    "attachment_service_upload_attachment",
    "attachment_service_upload_attachment_sync",
]
