# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any, TypeAlias

from pydantic import TypeAdapter

import memos_unofficial_sdk.types as _response_types
from memos_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    omit_unset,
    sdk_request,
    sdk_request_sync,
)
from memos_unofficial_sdk.types import (
    GetCurrentUserResponse,
    RefreshTokenResponse,
    SignInRequest_PasswordCredentials,
    SignInRequest_SSOCredentials,
    SignInResponse,
    Status,
)
from memos_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


AuthServiceGetCurrentUserError: TypeAlias = Status


async def auth_service_get_current_user(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> GetCurrentUserResponse:
    """Retrieves information about the authenticated user by validating the access token.
    Use this endpoint to obtain the user's details, similar to an OIDC userinfo request.

    GetCurrentUser returns the authenticated user's information. Validates the access
    token and returns user details. Similar to OIDC's /userinfo endpoint.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v1/auth/me",
        operation_id="auth_service_get_current_user",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetCurrentUserResponse"), GetCurrentUserResponse
    )


def auth_service_get_current_user_sync(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> GetCurrentUserResponse:
    """Retrieves information about the authenticated user by validating the access token.
    Use this endpoint to obtain the user's details, similar to an OIDC userinfo request.

    GetCurrentUser returns the authenticated user's information. Validates the access
    token and returns user details. Similar to OIDC's /userinfo endpoint.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v1/auth/me",
        operation_id="auth_service_get_current_user",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GetCurrentUserResponse"), GetCurrentUserResponse
    )


AuthServiceRefreshTokenError: TypeAlias = Status


async def auth_service_refresh_token(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> RefreshTokenResponse:
    """Exchanges the refresh token in the HttpOnly cookie for a new short-lived access
    token. Send the request with the refresh token cookie; the response includes the
    token's expiration time.

    RefreshToken exchanges a valid refresh token for a new access token. The refresh
    token is read from the HttpOnly cookie. Returns a new short-lived access token.
    """

    _resp = await sdk_request(
        "POST",
        "/api/v1/auth/refresh",
        operation_id="auth_service_refresh_token",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "RefreshTokenResponse"), RefreshTokenResponse
    )


def auth_service_refresh_token_sync(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> RefreshTokenResponse:
    """Exchanges the refresh token in the HttpOnly cookie for a new short-lived access
    token. Send the request with the refresh token cookie; the response includes the
    token's expiration time.

    RefreshToken exchanges a valid refresh token for a new access token. The refresh
    token is read from the HttpOnly cookie. Returns a new short-lived access token.
    """

    _resp = sdk_request_sync(
        "POST",
        "/api/v1/auth/refresh",
        operation_id="auth_service_refresh_token",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "RefreshTokenResponse"), RefreshTokenResponse
    )


AuthServiceSignInError: TypeAlias = Status


async def auth_service_sign_in(
    _client_config: ClientConfig,
    password_credentials: SignInRequest_PasswordCredentials | NotGiven = NOT_GIVEN,
    sso_credentials: SignInRequest_SSOCredentials | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> SignInResponse:
    """Authenticates a user with password credentials or an SSO provider. Supply the
    relevant credential object; password sign-in requires `username` and `password`,
    while SSO sign-in requires `idpName`, `code`, and `redirectUri`. The response
    includes an access token and sets a refresh-token cookie.

    SignIn authenticates a user with credentials and returns tokens. On success, returns
    an access token and sets a refresh token cookie. Supports password-based and SSO
    authentication methods.

    Args:
        password_credentials: Username and password authentication.
        sso_credentials: SSO provider authentication.
    """

    _resp = await sdk_request(
        "POST",
        "/api/v1/auth/signin",
        json=omit_unset(
            {
                "passwordCredentials": (
                    NOT_GIVEN
                    if password_credentials is NOT_GIVEN
                    else to_wire(password_credentials, "SignInRequest_PasswordCredentials")
                ),
                "ssoCredentials": (
                    NOT_GIVEN
                    if sso_credentials is NOT_GIVEN
                    else to_wire(sso_credentials, "SignInRequest_SSOCredentials")
                ),
            }
        ),
        operation_id="auth_service_sign_in",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "SignInResponse"), SignInResponse
    )


def auth_service_sign_in_sync(
    _client_config: ClientConfig,
    password_credentials: SignInRequest_PasswordCredentials | NotGiven = NOT_GIVEN,
    sso_credentials: SignInRequest_SSOCredentials | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> SignInResponse:
    """Authenticates a user with password credentials or an SSO provider. Supply the
    relevant credential object; password sign-in requires `username` and `password`,
    while SSO sign-in requires `idpName`, `code`, and `redirectUri`. The response
    includes an access token and sets a refresh-token cookie.

    SignIn authenticates a user with credentials and returns tokens. On success, returns
    an access token and sets a refresh token cookie. Supports password-based and SSO
    authentication methods.

    Args:
        password_credentials: Username and password authentication.
        sso_credentials: SSO provider authentication.
    """

    _resp = sdk_request_sync(
        "POST",
        "/api/v1/auth/signin",
        json=omit_unset(
            {
                "passwordCredentials": (
                    NOT_GIVEN
                    if password_credentials is NOT_GIVEN
                    else to_wire(password_credentials, "SignInRequest_PasswordCredentials")
                ),
                "ssoCredentials": (
                    NOT_GIVEN
                    if sso_credentials is NOT_GIVEN
                    else to_wire(sso_credentials, "SignInRequest_SSOCredentials")
                ),
            }
        ),
        operation_id="auth_service_sign_in",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "SignInResponse"), SignInResponse
    )


AuthServiceSignOutError: TypeAlias = Status


async def auth_service_sign_out(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Terminates the authenticated user's session by revoking the refresh token and
    clearing the authentication cookie. Call this operation when the user signs out so
    the refresh token can no longer be used to obtain access tokens.

    SignOut terminates the user's authentication. Revokes the refresh token and clears
    the authentication cookie.
    """

    _resp = await sdk_request(
        "POST",
        "/api/v1/auth/signout",
        operation_id="auth_service_sign_out",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


def auth_service_sign_out_sync(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Terminates the authenticated user's session by revoking the refresh token and
    clearing the authentication cookie. Call this operation when the user signs out so
    the refresh token can no longer be used to obtain access tokens.

    SignOut terminates the user's authentication. Revokes the refresh token and clears
    the authentication cookie.
    """

    _resp = sdk_request_sync(
        "POST",
        "/api/v1/auth/signout",
        operation_id="auth_service_sign_out",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


__all__ = [
    "AuthServiceGetCurrentUserError",
    "AuthServiceRefreshTokenError",
    "AuthServiceSignInError",
    "AuthServiceSignOutError",
    "auth_service_get_current_user",
    "auth_service_get_current_user_sync",
    "auth_service_refresh_token",
    "auth_service_refresh_token_sync",
    "auth_service_sign_in",
    "auth_service_sign_in_sync",
    "auth_service_sign_out",
    "auth_service_sign_out_sync",
]
