# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any, Literal, TypeAlias

from pydantic import TypeAdapter

import memos_unofficial_sdk.types as _response_types
from memos_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    encode_path_segment,
    omit_unset,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from memos_unofficial_sdk.types import (
    IdentityProvider,
    IdentityProviderConfig,
    ListIdentityProvidersResponse,
    Status,
)
from memos_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


IdentityProviderServiceListIdentityProvidersError: TypeAlias = Status


async def identity_provider_service_list_identity_providers(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> ListIdentityProvidersResponse:
    """Lists the identity providers configured for the instance. Use this operation to
    retrieve provider types, display titles, identifier filters, and configuration
    details before choosing or managing an identity provider.

    ListIdentityProviders lists identity providers.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v1/identity-providers",
        operation_id="identity_provider_service_list_identity_providers",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListIdentityProvidersResponse"),
        ListIdentityProvidersResponse,
    )


def identity_provider_service_list_identity_providers_sync(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> ListIdentityProvidersResponse:
    """Lists the identity providers configured for the instance. Use this operation to
    retrieve provider types, display titles, identifier filters, and configuration
    details before choosing or managing an identity provider.

    ListIdentityProviders lists identity providers.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v1/identity-providers",
        operation_id="identity_provider_service_list_identity_providers",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListIdentityProvidersResponse"),
        ListIdentityProvidersResponse,
    )


IdentityProviderServiceCreateIdentityProviderError: TypeAlias = Status


async def identity_provider_service_create_identity_provider(
    _client_config: ClientConfig,
    type: Literal["TYPE_UNSPECIFIED", "OAUTH2"] | str,
    title: str,
    config: IdentityProviderConfig,
    identity_provider_id: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    identifier_filter: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> IdentityProvider:
    """Creates an identity provider for the instance. Supply `type`, `title`, and `config`;
    use `identityProviderId` to choose the resource ID, or omit it to have one
    generated. The provider type must be `TYPE_UNSPECIFIED` or `OAUTH2`.

    CreateIdentityProvider creates an identity provider.

    Args:
        type: Required. The type of the identity provider.
        title: Required. The display title of the identity provider.
        config: Required. Configuration for the identity provider.
        identity_provider_id: Optional. The ID to use for the identity provider, which will become the final
            component of the resource name. If not provided, the system will generate one.
            Format: ^[a-zA-Z0-9]([a-zA-Z0-9-]{0,34}[a-zA-Z0-9])?$
        name: The resource name of the identity provider. Format: identity-providers/{idp}
        identifier_filter: Optional. Filter applied to user identifiers.
    """

    _resp = await sdk_request(
        "POST",
        "/api/v1/identity-providers",
        params=serialize_query([("identityProviderId", identity_provider_id, "form", True)]),
        json=omit_unset(
            {
                "type": (
                    NOT_GIVEN
                    if type is NOT_GIVEN
                    else to_wire(type, 'Literal["TYPE_UNSPECIFIED", "OAUTH2"] | str')
                ),
                "title": (NOT_GIVEN if title is NOT_GIVEN else to_wire(title, "str")),
                "config": (
                    NOT_GIVEN if config is NOT_GIVEN else to_wire(config, "IdentityProviderConfig")
                ),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "identifierFilter": (
                    NOT_GIVEN
                    if identifier_filter is NOT_GIVEN
                    else to_wire(identifier_filter, "str")
                ),
            }
        ),
        operation_id="identity_provider_service_create_identity_provider",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "IdentityProvider"), IdentityProvider
    )


def identity_provider_service_create_identity_provider_sync(
    _client_config: ClientConfig,
    type: Literal["TYPE_UNSPECIFIED", "OAUTH2"] | str,
    title: str,
    config: IdentityProviderConfig,
    identity_provider_id: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    identifier_filter: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> IdentityProvider:
    """Creates an identity provider for the instance. Supply `type`, `title`, and `config`;
    use `identityProviderId` to choose the resource ID, or omit it to have one
    generated. The provider type must be `TYPE_UNSPECIFIED` or `OAUTH2`.

    CreateIdentityProvider creates an identity provider.

    Args:
        type: Required. The type of the identity provider.
        title: Required. The display title of the identity provider.
        config: Required. Configuration for the identity provider.
        identity_provider_id: Optional. The ID to use for the identity provider, which will become the final
            component of the resource name. If not provided, the system will generate one.
            Format: ^[a-zA-Z0-9]([a-zA-Z0-9-]{0,34}[a-zA-Z0-9])?$
        name: The resource name of the identity provider. Format: identity-providers/{idp}
        identifier_filter: Optional. Filter applied to user identifiers.
    """

    _resp = sdk_request_sync(
        "POST",
        "/api/v1/identity-providers",
        params=serialize_query([("identityProviderId", identity_provider_id, "form", True)]),
        json=omit_unset(
            {
                "type": (
                    NOT_GIVEN
                    if type is NOT_GIVEN
                    else to_wire(type, 'Literal["TYPE_UNSPECIFIED", "OAUTH2"] | str')
                ),
                "title": (NOT_GIVEN if title is NOT_GIVEN else to_wire(title, "str")),
                "config": (
                    NOT_GIVEN if config is NOT_GIVEN else to_wire(config, "IdentityProviderConfig")
                ),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "identifierFilter": (
                    NOT_GIVEN
                    if identifier_filter is NOT_GIVEN
                    else to_wire(identifier_filter, "str")
                ),
            }
        ),
        operation_id="identity_provider_service_create_identity_provider",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "IdentityProvider"), IdentityProvider
    )


IdentityProviderServiceGetIdentityProviderError: TypeAlias = Status


async def identity_provider_service_get_identity_provider(
    _client_config: ClientConfig,
    identity_provider: str,
    *,
    request_options: RequestOptions | None = None,
) -> IdentityProvider:
    """Retrieves a configured identity provider by its ID. Use the identity provider's
    identifier to get its resource name, type, display title, identifier filter, and
    configuration.

    GetIdentityProvider gets an identity provider.

    Args:
        identity_provider: The identity-provider id.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v1/identity-providers/{encode_path_segment(identity_provider)}",
        operation_id="identity_provider_service_get_identity_provider",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "IdentityProvider"), IdentityProvider
    )


def identity_provider_service_get_identity_provider_sync(
    _client_config: ClientConfig,
    identity_provider: str,
    *,
    request_options: RequestOptions | None = None,
) -> IdentityProvider:
    """Retrieves a configured identity provider by its ID. Use the identity provider's
    identifier to get its resource name, type, display title, identifier filter, and
    configuration.

    GetIdentityProvider gets an identity provider.

    Args:
        identity_provider: The identity-provider id.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v1/identity-providers/{encode_path_segment(identity_provider)}",
        operation_id="identity_provider_service_get_identity_provider",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "IdentityProvider"), IdentityProvider
    )


IdentityProviderServiceDeleteIdentityProviderError: TypeAlias = Status


async def identity_provider_service_delete_identity_provider(
    _client_config: ClientConfig,
    identity_provider: str,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Deletes an identity provider from the instance. Supply the identity provider's ID to
    select the resource to remove. Use this operation when the provider should no longer
    be available for authentication.

    DeleteIdentityProvider deletes an identity provider.

    Args:
        identity_provider: The identity-provider id.
    """

    _resp = await sdk_request(
        "DELETE",
        f"/api/v1/identity-providers/{encode_path_segment(identity_provider)}",
        operation_id="identity_provider_service_delete_identity_provider",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


def identity_provider_service_delete_identity_provider_sync(
    _client_config: ClientConfig,
    identity_provider: str,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Deletes an identity provider from the instance. Supply the identity provider's ID to
    select the resource to remove. Use this operation when the provider should no longer
    be available for authentication.

    DeleteIdentityProvider deletes an identity provider.

    Args:
        identity_provider: The identity-provider id.
    """

    _resp = sdk_request_sync(
        "DELETE",
        f"/api/v1/identity-providers/{encode_path_segment(identity_provider)}",
        operation_id="identity_provider_service_delete_identity_provider",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


IdentityProviderServiceUpdateIdentityProviderError: TypeAlias = Status


async def identity_provider_service_update_identity_provider(
    _client_config: ClientConfig,
    identity_provider: str,
    type: Literal["TYPE_UNSPECIFIED", "OAUTH2"] | str,
    title: str,
    config: IdentityProviderConfig,
    update_mask: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    identifier_filter: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> IdentityProvider:
    """Updates an identity provider using the supplied resource fields and update mask.
    Include `type`, `title`, and `config` in the request body, and use `updateMask` to
    select the top-level fields to update. Only top-level fields of the identity
    provider are supported by the mask.

    UpdateIdentityProvider updates an identity provider.

    Args:
        identity_provider: The identity-provider id.
        type: Required. The type of the identity provider.
        title: Required. The display title of the identity provider.
        config: Required. Configuration for the identity provider.
        update_mask: Required. The update mask applies to the resource. Only the top level fields of
            IdentityProvider are supported.
        name: The resource name of the identity provider. Format: identity-providers/{idp}
        identifier_filter: Optional. Filter applied to user identifiers.
    """

    _resp = await sdk_request(
        "PATCH",
        f"/api/v1/identity-providers/{encode_path_segment(identity_provider)}",
        params=serialize_query([("updateMask", update_mask, "form", True)]),
        json=omit_unset(
            {
                "type": (
                    NOT_GIVEN
                    if type is NOT_GIVEN
                    else to_wire(type, 'Literal["TYPE_UNSPECIFIED", "OAUTH2"] | str')
                ),
                "title": (NOT_GIVEN if title is NOT_GIVEN else to_wire(title, "str")),
                "config": (
                    NOT_GIVEN if config is NOT_GIVEN else to_wire(config, "IdentityProviderConfig")
                ),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "identifierFilter": (
                    NOT_GIVEN
                    if identifier_filter is NOT_GIVEN
                    else to_wire(identifier_filter, "str")
                ),
            }
        ),
        operation_id="identity_provider_service_update_identity_provider",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "IdentityProvider"), IdentityProvider
    )


def identity_provider_service_update_identity_provider_sync(
    _client_config: ClientConfig,
    identity_provider: str,
    type: Literal["TYPE_UNSPECIFIED", "OAUTH2"] | str,
    title: str,
    config: IdentityProviderConfig,
    update_mask: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    identifier_filter: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> IdentityProvider:
    """Updates an identity provider using the supplied resource fields and update mask.
    Include `type`, `title`, and `config` in the request body, and use `updateMask` to
    select the top-level fields to update. Only top-level fields of the identity
    provider are supported by the mask.

    UpdateIdentityProvider updates an identity provider.

    Args:
        identity_provider: The identity-provider id.
        type: Required. The type of the identity provider.
        title: Required. The display title of the identity provider.
        config: Required. Configuration for the identity provider.
        update_mask: Required. The update mask applies to the resource. Only the top level fields of
            IdentityProvider are supported.
        name: The resource name of the identity provider. Format: identity-providers/{idp}
        identifier_filter: Optional. Filter applied to user identifiers.
    """

    _resp = sdk_request_sync(
        "PATCH",
        f"/api/v1/identity-providers/{encode_path_segment(identity_provider)}",
        params=serialize_query([("updateMask", update_mask, "form", True)]),
        json=omit_unset(
            {
                "type": (
                    NOT_GIVEN
                    if type is NOT_GIVEN
                    else to_wire(type, 'Literal["TYPE_UNSPECIFIED", "OAUTH2"] | str')
                ),
                "title": (NOT_GIVEN if title is NOT_GIVEN else to_wire(title, "str")),
                "config": (
                    NOT_GIVEN if config is NOT_GIVEN else to_wire(config, "IdentityProviderConfig")
                ),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "identifierFilter": (
                    NOT_GIVEN
                    if identifier_filter is NOT_GIVEN
                    else to_wire(identifier_filter, "str")
                ),
            }
        ),
        operation_id="identity_provider_service_update_identity_provider",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "IdentityProvider"), IdentityProvider
    )


__all__ = [
    "IdentityProviderServiceCreateIdentityProviderError",
    "IdentityProviderServiceDeleteIdentityProviderError",
    "IdentityProviderServiceGetIdentityProviderError",
    "IdentityProviderServiceListIdentityProvidersError",
    "IdentityProviderServiceUpdateIdentityProviderError",
    "identity_provider_service_create_identity_provider",
    "identity_provider_service_create_identity_provider_sync",
    "identity_provider_service_delete_identity_provider",
    "identity_provider_service_delete_identity_provider_sync",
    "identity_provider_service_get_identity_provider",
    "identity_provider_service_get_identity_provider_sync",
    "identity_provider_service_list_identity_providers",
    "identity_provider_service_list_identity_providers_sync",
    "identity_provider_service_update_identity_provider",
    "identity_provider_service_update_identity_provider_sync",
]
