# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

from ..client import ClientConfig, LoggingConfig
from .ai_service import _AiServiceNamespace
from .attachment_service import _AttachmentServiceNamespace
from .auth_service import _AuthServiceNamespace
from .identity_provider_service import _IdentityProviderServiceNamespace
from .instance_service import _InstanceServiceNamespace
from .memo_service import _MemoServiceNamespace
from .space_service import _SpaceServiceNamespace
from .user_service import _UserServiceNamespace


class Sdk:
    def __init__(self, config: ClientConfig) -> None:
        self._config = config
        self.ai_service = _AiServiceNamespace(config)
        self.attachment_service = _AttachmentServiceNamespace(config)
        self.auth_service = _AuthServiceNamespace(config)
        self.identity_provider_service = _IdentityProviderServiceNamespace(config)
        self.instance_service = _InstanceServiceNamespace(config)
        self.memo_service = _MemoServiceNamespace(config)
        self.space_service = _SpaceServiceNamespace(config)
        self.user_service = _UserServiceNamespace(config)

    def set_logging_config(
        self, config: LoggingConfig | None = None, **fields: Any
    ) -> LoggingConfig:
        """Turn SDK logging on and configure it.

        Logging is OFF by default — this SDK reports nothing until you call this
        (or construct the client with logging enabled). Reports go to the endpoint
        this build was generated with, or to the endpoint you pass; with neither,
        nothing is sent. Pass enabled=False to turn logging back off.
        """
        if self._config.logging is None:
            self._config.logging = LoggingConfig()
        current = self._config.logging
        if config is not None:
            for key, value in vars(config).items():
                if key != "enabled":
                    setattr(current, key, value)
        current.enabled = True
        for key, value in fields.items():
            if not hasattr(current, key):
                raise TypeError(f"LoggingConfig has no field {key!r}")
            setattr(current, key, value)
        return current


__all__ = ["Sdk"]
