# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.ai_service import ai_service_transcribe, ai_service_transcribe_sync


class _AiServiceNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.transcribe = partial(ai_service_transcribe, config)
        self.transcribe.__doc__ = ai_service_transcribe.__doc__
        self.transcribe_sync = partial(ai_service_transcribe_sync, config)
        self.transcribe_sync.__doc__ = ai_service_transcribe_sync.__doc__
