# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.auth_service import (
    auth_service_get_current_user,
    auth_service_get_current_user_sync,
    auth_service_refresh_token,
    auth_service_refresh_token_sync,
    auth_service_sign_in,
    auth_service_sign_in_sync,
    auth_service_sign_out,
    auth_service_sign_out_sync,
)


class _AuthServiceNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.get_current_user = partial(auth_service_get_current_user, config)
        self.get_current_user.__doc__ = auth_service_get_current_user.__doc__
        self.get_current_user_sync = partial(auth_service_get_current_user_sync, config)
        self.get_current_user_sync.__doc__ = auth_service_get_current_user_sync.__doc__
        self.refresh_token = partial(auth_service_refresh_token, config)
        self.refresh_token.__doc__ = auth_service_refresh_token.__doc__
        self.refresh_token_sync = partial(auth_service_refresh_token_sync, config)
        self.refresh_token_sync.__doc__ = auth_service_refresh_token_sync.__doc__
        self.sign_in = partial(auth_service_sign_in, config)
        self.sign_in.__doc__ = auth_service_sign_in.__doc__
        self.sign_in_sync = partial(auth_service_sign_in_sync, config)
        self.sign_in_sync.__doc__ = auth_service_sign_in_sync.__doc__
        self.sign_out = partial(auth_service_sign_out, config)
        self.sign_out.__doc__ = auth_service_sign_out.__doc__
        self.sign_out_sync = partial(auth_service_sign_out_sync, config)
        self.sign_out_sync.__doc__ = auth_service_sign_out_sync.__doc__
