# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.identity_provider_service import (
    identity_provider_service_create_identity_provider,
    identity_provider_service_create_identity_provider_sync,
    identity_provider_service_delete_identity_provider,
    identity_provider_service_delete_identity_provider_sync,
    identity_provider_service_get_identity_provider,
    identity_provider_service_get_identity_provider_sync,
    identity_provider_service_list_identity_providers,
    identity_provider_service_list_identity_providers_sync,
    identity_provider_service_update_identity_provider,
    identity_provider_service_update_identity_provider_sync,
)


class _IdentityProviderServiceNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.list_identity_providers = partial(
            identity_provider_service_list_identity_providers, config
        )
        self.list_identity_providers.__doc__ = (
            identity_provider_service_list_identity_providers.__doc__
        )
        self.list_identity_providers_sync = partial(
            identity_provider_service_list_identity_providers_sync, config
        )
        self.list_identity_providers_sync.__doc__ = (
            identity_provider_service_list_identity_providers_sync.__doc__
        )
        self.create_identity_provider = partial(
            identity_provider_service_create_identity_provider, config
        )
        self.create_identity_provider.__doc__ = (
            identity_provider_service_create_identity_provider.__doc__
        )
        self.create_identity_provider_sync = partial(
            identity_provider_service_create_identity_provider_sync, config
        )
        self.create_identity_provider_sync.__doc__ = (
            identity_provider_service_create_identity_provider_sync.__doc__
        )
        self.get_identity_provider = partial(
            identity_provider_service_get_identity_provider, config
        )
        self.get_identity_provider.__doc__ = identity_provider_service_get_identity_provider.__doc__
        self.get_identity_provider_sync = partial(
            identity_provider_service_get_identity_provider_sync, config
        )
        self.get_identity_provider_sync.__doc__ = (
            identity_provider_service_get_identity_provider_sync.__doc__
        )
        self.delete_identity_provider = partial(
            identity_provider_service_delete_identity_provider, config
        )
        self.delete_identity_provider.__doc__ = (
            identity_provider_service_delete_identity_provider.__doc__
        )
        self.delete_identity_provider_sync = partial(
            identity_provider_service_delete_identity_provider_sync, config
        )
        self.delete_identity_provider_sync.__doc__ = (
            identity_provider_service_delete_identity_provider_sync.__doc__
        )
        self.update_identity_provider = partial(
            identity_provider_service_update_identity_provider, config
        )
        self.update_identity_provider.__doc__ = (
            identity_provider_service_update_identity_provider.__doc__
        )
        self.update_identity_provider_sync = partial(
            identity_provider_service_update_identity_provider_sync, config
        )
        self.update_identity_provider_sync.__doc__ = (
            identity_provider_service_update_identity_provider_sync.__doc__
        )
