# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.instance_service import (
    instance_service_batch_get_instance_settings,
    instance_service_batch_get_instance_settings_sync,
    instance_service_get_instance_profile,
    instance_service_get_instance_profile_sync,
    instance_service_get_instance_setting,
    instance_service_get_instance_setting_sync,
    instance_service_get_instance_stats,
    instance_service_get_instance_stats_sync,
    instance_service_test_instance_email_setting,
    instance_service_test_instance_email_setting_sync,
    instance_service_update_instance_setting,
    instance_service_update_instance_setting_sync,
)


class _InstanceServiceNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.get_instance_profile = partial(instance_service_get_instance_profile, config)
        self.get_instance_profile.__doc__ = instance_service_get_instance_profile.__doc__
        self.get_instance_profile_sync = partial(instance_service_get_instance_profile_sync, config)
        self.get_instance_profile_sync.__doc__ = instance_service_get_instance_profile_sync.__doc__
        self.test_instance_email_setting = partial(
            instance_service_test_instance_email_setting, config
        )
        self.test_instance_email_setting.__doc__ = (
            instance_service_test_instance_email_setting.__doc__
        )
        self.test_instance_email_setting_sync = partial(
            instance_service_test_instance_email_setting_sync, config
        )
        self.test_instance_email_setting_sync.__doc__ = (
            instance_service_test_instance_email_setting_sync.__doc__
        )
        self.batch_get_instance_settings = partial(
            instance_service_batch_get_instance_settings, config
        )
        self.batch_get_instance_settings.__doc__ = (
            instance_service_batch_get_instance_settings.__doc__
        )
        self.batch_get_instance_settings_sync = partial(
            instance_service_batch_get_instance_settings_sync, config
        )
        self.batch_get_instance_settings_sync.__doc__ = (
            instance_service_batch_get_instance_settings_sync.__doc__
        )
        self.get_instance_stats = partial(instance_service_get_instance_stats, config)
        self.get_instance_stats.__doc__ = instance_service_get_instance_stats.__doc__
        self.get_instance_stats_sync = partial(instance_service_get_instance_stats_sync, config)
        self.get_instance_stats_sync.__doc__ = instance_service_get_instance_stats_sync.__doc__
        self.get_instance_setting = partial(instance_service_get_instance_setting, config)
        self.get_instance_setting.__doc__ = instance_service_get_instance_setting.__doc__
        self.get_instance_setting_sync = partial(instance_service_get_instance_setting_sync, config)
        self.get_instance_setting_sync.__doc__ = instance_service_get_instance_setting_sync.__doc__
        self.update_instance_setting = partial(instance_service_update_instance_setting, config)
        self.update_instance_setting.__doc__ = instance_service_update_instance_setting.__doc__
        self.update_instance_setting_sync = partial(
            instance_service_update_instance_setting_sync, config
        )
        self.update_instance_setting_sync.__doc__ = (
            instance_service_update_instance_setting_sync.__doc__
        )
