# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.memo_service import (
    memo_service_batch_get_link_metadata,
    memo_service_batch_get_link_metadata_sync,
    memo_service_create_memo,
    memo_service_create_memo_comment,
    memo_service_create_memo_comment_sync,
    memo_service_create_memo_share,
    memo_service_create_memo_share_sync,
    memo_service_create_memo_sync,
    memo_service_delete_memo,
    memo_service_delete_memo_reaction,
    memo_service_delete_memo_reaction_sync,
    memo_service_delete_memo_share,
    memo_service_delete_memo_share_sync,
    memo_service_delete_memo_sync,
    memo_service_get_link_metadata,
    memo_service_get_link_metadata_sync,
    memo_service_get_memo,
    memo_service_get_memo_sync,
    memo_service_get_shared_memo,
    memo_service_get_shared_memo_sync,
    memo_service_list_memo_attachments,
    memo_service_list_memo_attachments_sync,
    memo_service_list_memo_comments,
    memo_service_list_memo_comments_sync,
    memo_service_list_memo_reactions,
    memo_service_list_memo_reactions_sync,
    memo_service_list_memo_relations,
    memo_service_list_memo_relations_sync,
    memo_service_list_memo_shares,
    memo_service_list_memo_shares_sync,
    memo_service_list_memos,
    memo_service_list_memos_sync,
    memo_service_set_memo_attachments,
    memo_service_set_memo_attachments_sync,
    memo_service_set_memo_relations,
    memo_service_set_memo_relations_sync,
    memo_service_update_memo,
    memo_service_update_memo_sync,
    memo_service_upsert_memo_reaction,
    memo_service_upsert_memo_reaction_sync,
)


class _MemoServiceNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.list_memos = partial(memo_service_list_memos, config)
        self.list_memos.__doc__ = memo_service_list_memos.__doc__
        self.list_memos_sync = partial(memo_service_list_memos_sync, config)
        self.list_memos_sync.__doc__ = memo_service_list_memos_sync.__doc__
        self.create_memo = partial(memo_service_create_memo, config)
        self.create_memo.__doc__ = memo_service_create_memo.__doc__
        self.create_memo_sync = partial(memo_service_create_memo_sync, config)
        self.create_memo_sync.__doc__ = memo_service_create_memo_sync.__doc__
        self.get_link_metadata = partial(memo_service_get_link_metadata, config)
        self.get_link_metadata.__doc__ = memo_service_get_link_metadata.__doc__
        self.get_link_metadata_sync = partial(memo_service_get_link_metadata_sync, config)
        self.get_link_metadata_sync.__doc__ = memo_service_get_link_metadata_sync.__doc__
        self.batch_get_link_metadata = partial(memo_service_batch_get_link_metadata, config)
        self.batch_get_link_metadata.__doc__ = memo_service_batch_get_link_metadata.__doc__
        self.batch_get_link_metadata_sync = partial(
            memo_service_batch_get_link_metadata_sync, config
        )
        self.batch_get_link_metadata_sync.__doc__ = (
            memo_service_batch_get_link_metadata_sync.__doc__
        )
        self.get_memo = partial(memo_service_get_memo, config)
        self.get_memo.__doc__ = memo_service_get_memo.__doc__
        self.get_memo_sync = partial(memo_service_get_memo_sync, config)
        self.get_memo_sync.__doc__ = memo_service_get_memo_sync.__doc__
        self.delete_memo = partial(memo_service_delete_memo, config)
        self.delete_memo.__doc__ = memo_service_delete_memo.__doc__
        self.delete_memo_sync = partial(memo_service_delete_memo_sync, config)
        self.delete_memo_sync.__doc__ = memo_service_delete_memo_sync.__doc__
        self.update_memo = partial(memo_service_update_memo, config)
        self.update_memo.__doc__ = memo_service_update_memo.__doc__
        self.update_memo_sync = partial(memo_service_update_memo_sync, config)
        self.update_memo_sync.__doc__ = memo_service_update_memo_sync.__doc__
        self.list_memo_attachments = partial(memo_service_list_memo_attachments, config)
        self.list_memo_attachments.__doc__ = memo_service_list_memo_attachments.__doc__
        self.list_memo_attachments_sync = partial(memo_service_list_memo_attachments_sync, config)
        self.list_memo_attachments_sync.__doc__ = memo_service_list_memo_attachments_sync.__doc__
        self.set_memo_attachments = partial(memo_service_set_memo_attachments, config)
        self.set_memo_attachments.__doc__ = memo_service_set_memo_attachments.__doc__
        self.set_memo_attachments_sync = partial(memo_service_set_memo_attachments_sync, config)
        self.set_memo_attachments_sync.__doc__ = memo_service_set_memo_attachments_sync.__doc__
        self.list_memo_comments = partial(memo_service_list_memo_comments, config)
        self.list_memo_comments.__doc__ = memo_service_list_memo_comments.__doc__
        self.list_memo_comments_sync = partial(memo_service_list_memo_comments_sync, config)
        self.list_memo_comments_sync.__doc__ = memo_service_list_memo_comments_sync.__doc__
        self.create_memo_comment = partial(memo_service_create_memo_comment, config)
        self.create_memo_comment.__doc__ = memo_service_create_memo_comment.__doc__
        self.create_memo_comment_sync = partial(memo_service_create_memo_comment_sync, config)
        self.create_memo_comment_sync.__doc__ = memo_service_create_memo_comment_sync.__doc__
        self.list_memo_reactions = partial(memo_service_list_memo_reactions, config)
        self.list_memo_reactions.__doc__ = memo_service_list_memo_reactions.__doc__
        self.list_memo_reactions_sync = partial(memo_service_list_memo_reactions_sync, config)
        self.list_memo_reactions_sync.__doc__ = memo_service_list_memo_reactions_sync.__doc__
        self.upsert_memo_reaction = partial(memo_service_upsert_memo_reaction, config)
        self.upsert_memo_reaction.__doc__ = memo_service_upsert_memo_reaction.__doc__
        self.upsert_memo_reaction_sync = partial(memo_service_upsert_memo_reaction_sync, config)
        self.upsert_memo_reaction_sync.__doc__ = memo_service_upsert_memo_reaction_sync.__doc__
        self.delete_memo_reaction = partial(memo_service_delete_memo_reaction, config)
        self.delete_memo_reaction.__doc__ = memo_service_delete_memo_reaction.__doc__
        self.delete_memo_reaction_sync = partial(memo_service_delete_memo_reaction_sync, config)
        self.delete_memo_reaction_sync.__doc__ = memo_service_delete_memo_reaction_sync.__doc__
        self.list_memo_relations = partial(memo_service_list_memo_relations, config)
        self.list_memo_relations.__doc__ = memo_service_list_memo_relations.__doc__
        self.list_memo_relations_sync = partial(memo_service_list_memo_relations_sync, config)
        self.list_memo_relations_sync.__doc__ = memo_service_list_memo_relations_sync.__doc__
        self.set_memo_relations = partial(memo_service_set_memo_relations, config)
        self.set_memo_relations.__doc__ = memo_service_set_memo_relations.__doc__
        self.set_memo_relations_sync = partial(memo_service_set_memo_relations_sync, config)
        self.set_memo_relations_sync.__doc__ = memo_service_set_memo_relations_sync.__doc__
        self.list_memo_shares = partial(memo_service_list_memo_shares, config)
        self.list_memo_shares.__doc__ = memo_service_list_memo_shares.__doc__
        self.list_memo_shares_sync = partial(memo_service_list_memo_shares_sync, config)
        self.list_memo_shares_sync.__doc__ = memo_service_list_memo_shares_sync.__doc__
        self.create_memo_share = partial(memo_service_create_memo_share, config)
        self.create_memo_share.__doc__ = memo_service_create_memo_share.__doc__
        self.create_memo_share_sync = partial(memo_service_create_memo_share_sync, config)
        self.create_memo_share_sync.__doc__ = memo_service_create_memo_share_sync.__doc__
        self.delete_memo_share = partial(memo_service_delete_memo_share, config)
        self.delete_memo_share.__doc__ = memo_service_delete_memo_share.__doc__
        self.delete_memo_share_sync = partial(memo_service_delete_memo_share_sync, config)
        self.delete_memo_share_sync.__doc__ = memo_service_delete_memo_share_sync.__doc__
        self.get_shared_memo = partial(memo_service_get_shared_memo, config)
        self.get_shared_memo.__doc__ = memo_service_get_shared_memo.__doc__
        self.get_shared_memo_sync = partial(memo_service_get_shared_memo_sync, config)
        self.get_shared_memo_sync.__doc__ = memo_service_get_shared_memo_sync.__doc__
