# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.space_service import (
    space_service_accept_space_invitation,
    space_service_accept_space_invitation_sync,
    space_service_create_space,
    space_service_create_space_invitation,
    space_service_create_space_invitation_sync,
    space_service_create_space_sync,
    space_service_decline_space_invitation,
    space_service_decline_space_invitation_sync,
    space_service_delete_space,
    space_service_delete_space_invitation,
    space_service_delete_space_invitation_sync,
    space_service_delete_space_member,
    space_service_delete_space_member_sync,
    space_service_delete_space_sync,
    space_service_get_space,
    space_service_get_space_invitation,
    space_service_get_space_invitation_sync,
    space_service_get_space_member,
    space_service_get_space_member_sync,
    space_service_get_space_sync,
    space_service_list_space_invitations,
    space_service_list_space_invitations_sync,
    space_service_list_space_members,
    space_service_list_space_members_sync,
    space_service_list_spaces,
    space_service_list_spaces_sync,
    space_service_list_user_space_invitations,
    space_service_list_user_space_invitations_sync,
    space_service_update_space,
    space_service_update_space_member,
    space_service_update_space_member_sync,
    space_service_update_space_sync,
)


class _SpaceServiceNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.list_spaces = partial(space_service_list_spaces, config)
        self.list_spaces.__doc__ = space_service_list_spaces.__doc__
        self.list_spaces_sync = partial(space_service_list_spaces_sync, config)
        self.list_spaces_sync.__doc__ = space_service_list_spaces_sync.__doc__
        self.create_space = partial(space_service_create_space, config)
        self.create_space.__doc__ = space_service_create_space.__doc__
        self.create_space_sync = partial(space_service_create_space_sync, config)
        self.create_space_sync.__doc__ = space_service_create_space_sync.__doc__
        self.get_space = partial(space_service_get_space, config)
        self.get_space.__doc__ = space_service_get_space.__doc__
        self.get_space_sync = partial(space_service_get_space_sync, config)
        self.get_space_sync.__doc__ = space_service_get_space_sync.__doc__
        self.delete_space = partial(space_service_delete_space, config)
        self.delete_space.__doc__ = space_service_delete_space.__doc__
        self.delete_space_sync = partial(space_service_delete_space_sync, config)
        self.delete_space_sync.__doc__ = space_service_delete_space_sync.__doc__
        self.update_space = partial(space_service_update_space, config)
        self.update_space.__doc__ = space_service_update_space.__doc__
        self.update_space_sync = partial(space_service_update_space_sync, config)
        self.update_space_sync.__doc__ = space_service_update_space_sync.__doc__
        self.list_space_invitations = partial(space_service_list_space_invitations, config)
        self.list_space_invitations.__doc__ = space_service_list_space_invitations.__doc__
        self.list_space_invitations_sync = partial(
            space_service_list_space_invitations_sync, config
        )
        self.list_space_invitations_sync.__doc__ = space_service_list_space_invitations_sync.__doc__
        self.create_space_invitation = partial(space_service_create_space_invitation, config)
        self.create_space_invitation.__doc__ = space_service_create_space_invitation.__doc__
        self.create_space_invitation_sync = partial(
            space_service_create_space_invitation_sync, config
        )
        self.create_space_invitation_sync.__doc__ = (
            space_service_create_space_invitation_sync.__doc__
        )
        self.get_space_invitation = partial(space_service_get_space_invitation, config)
        self.get_space_invitation.__doc__ = space_service_get_space_invitation.__doc__
        self.get_space_invitation_sync = partial(space_service_get_space_invitation_sync, config)
        self.get_space_invitation_sync.__doc__ = space_service_get_space_invitation_sync.__doc__
        self.delete_space_invitation = partial(space_service_delete_space_invitation, config)
        self.delete_space_invitation.__doc__ = space_service_delete_space_invitation.__doc__
        self.delete_space_invitation_sync = partial(
            space_service_delete_space_invitation_sync, config
        )
        self.delete_space_invitation_sync.__doc__ = (
            space_service_delete_space_invitation_sync.__doc__
        )
        self.accept_space_invitation = partial(space_service_accept_space_invitation, config)
        self.accept_space_invitation.__doc__ = space_service_accept_space_invitation.__doc__
        self.accept_space_invitation_sync = partial(
            space_service_accept_space_invitation_sync, config
        )
        self.accept_space_invitation_sync.__doc__ = (
            space_service_accept_space_invitation_sync.__doc__
        )
        self.decline_space_invitation = partial(space_service_decline_space_invitation, config)
        self.decline_space_invitation.__doc__ = space_service_decline_space_invitation.__doc__
        self.decline_space_invitation_sync = partial(
            space_service_decline_space_invitation_sync, config
        )
        self.decline_space_invitation_sync.__doc__ = (
            space_service_decline_space_invitation_sync.__doc__
        )
        self.list_space_members = partial(space_service_list_space_members, config)
        self.list_space_members.__doc__ = space_service_list_space_members.__doc__
        self.list_space_members_sync = partial(space_service_list_space_members_sync, config)
        self.list_space_members_sync.__doc__ = space_service_list_space_members_sync.__doc__
        self.get_space_member = partial(space_service_get_space_member, config)
        self.get_space_member.__doc__ = space_service_get_space_member.__doc__
        self.get_space_member_sync = partial(space_service_get_space_member_sync, config)
        self.get_space_member_sync.__doc__ = space_service_get_space_member_sync.__doc__
        self.delete_space_member = partial(space_service_delete_space_member, config)
        self.delete_space_member.__doc__ = space_service_delete_space_member.__doc__
        self.delete_space_member_sync = partial(space_service_delete_space_member_sync, config)
        self.delete_space_member_sync.__doc__ = space_service_delete_space_member_sync.__doc__
        self.update_space_member = partial(space_service_update_space_member, config)
        self.update_space_member.__doc__ = space_service_update_space_member.__doc__
        self.update_space_member_sync = partial(space_service_update_space_member_sync, config)
        self.update_space_member_sync.__doc__ = space_service_update_space_member_sync.__doc__
        self.list_user_space_invitations = partial(
            space_service_list_user_space_invitations, config
        )
        self.list_user_space_invitations.__doc__ = space_service_list_user_space_invitations.__doc__
        self.list_user_space_invitations_sync = partial(
            space_service_list_user_space_invitations_sync, config
        )
        self.list_user_space_invitations_sync.__doc__ = (
            space_service_list_user_space_invitations_sync.__doc__
        )
