# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.user_service import (
    user_service_batch_get_users,
    user_service_batch_get_users_sync,
    user_service_create_linked_identity,
    user_service_create_linked_identity_sync,
    user_service_create_memo_view,
    user_service_create_memo_view_sync,
    user_service_create_personal_access_token,
    user_service_create_personal_access_token_sync,
    user_service_create_user,
    user_service_create_user_sync,
    user_service_create_user_webhook,
    user_service_create_user_webhook_sync,
    user_service_delete_linked_identity,
    user_service_delete_linked_identity_sync,
    user_service_delete_memo_view,
    user_service_delete_memo_view_sync,
    user_service_delete_personal_access_token,
    user_service_delete_personal_access_token_sync,
    user_service_delete_user,
    user_service_delete_user_notification,
    user_service_delete_user_notification_sync,
    user_service_delete_user_sync,
    user_service_delete_user_webhook,
    user_service_delete_user_webhook_sync,
    user_service_export_memos,
    user_service_export_memos_sync,
    user_service_get_linked_identity,
    user_service_get_linked_identity_sync,
    user_service_get_memo_view,
    user_service_get_memo_view_sync,
    user_service_get_user,
    user_service_get_user_setting,
    user_service_get_user_setting_sync,
    user_service_get_user_stats,
    user_service_get_user_stats_sync,
    user_service_get_user_sync,
    user_service_get_user_webhook_signing_secret,
    user_service_get_user_webhook_signing_secret_sync,
    user_service_import_memos,
    user_service_import_memos_sync,
    user_service_list_all_user_stats,
    user_service_list_all_user_stats_sync,
    user_service_list_linked_identities,
    user_service_list_linked_identities_sync,
    user_service_list_memo_views,
    user_service_list_memo_views_sync,
    user_service_list_personal_access_tokens,
    user_service_list_personal_access_tokens_sync,
    user_service_list_user_notifications,
    user_service_list_user_notifications_sync,
    user_service_list_user_settings,
    user_service_list_user_settings_sync,
    user_service_list_user_webhooks,
    user_service_list_user_webhooks_sync,
    user_service_list_users,
    user_service_list_users_sync,
    user_service_update_memo_view,
    user_service_update_memo_view_sync,
    user_service_update_user,
    user_service_update_user_notification,
    user_service_update_user_notification_sync,
    user_service_update_user_setting,
    user_service_update_user_setting_sync,
    user_service_update_user_sync,
    user_service_update_user_webhook,
    user_service_update_user_webhook_sync,
)


class _UserServiceNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.list_users = partial(user_service_list_users, config)
        self.list_users.__doc__ = user_service_list_users.__doc__
        self.list_users_sync = partial(user_service_list_users_sync, config)
        self.list_users_sync.__doc__ = user_service_list_users_sync.__doc__
        self.create_user = partial(user_service_create_user, config)
        self.create_user.__doc__ = user_service_create_user.__doc__
        self.create_user_sync = partial(user_service_create_user_sync, config)
        self.create_user_sync.__doc__ = user_service_create_user_sync.__doc__
        self.get_user = partial(user_service_get_user, config)
        self.get_user.__doc__ = user_service_get_user.__doc__
        self.get_user_sync = partial(user_service_get_user_sync, config)
        self.get_user_sync.__doc__ = user_service_get_user_sync.__doc__
        self.delete_user = partial(user_service_delete_user, config)
        self.delete_user.__doc__ = user_service_delete_user.__doc__
        self.delete_user_sync = partial(user_service_delete_user_sync, config)
        self.delete_user_sync.__doc__ = user_service_delete_user_sync.__doc__
        self.update_user = partial(user_service_update_user, config)
        self.update_user.__doc__ = user_service_update_user.__doc__
        self.update_user_sync = partial(user_service_update_user_sync, config)
        self.update_user_sync.__doc__ = user_service_update_user_sync.__doc__
        self.list_linked_identities = partial(user_service_list_linked_identities, config)
        self.list_linked_identities.__doc__ = user_service_list_linked_identities.__doc__
        self.list_linked_identities_sync = partial(user_service_list_linked_identities_sync, config)
        self.list_linked_identities_sync.__doc__ = user_service_list_linked_identities_sync.__doc__
        self.create_linked_identity = partial(user_service_create_linked_identity, config)
        self.create_linked_identity.__doc__ = user_service_create_linked_identity.__doc__
        self.create_linked_identity_sync = partial(user_service_create_linked_identity_sync, config)
        self.create_linked_identity_sync.__doc__ = user_service_create_linked_identity_sync.__doc__
        self.get_linked_identity = partial(user_service_get_linked_identity, config)
        self.get_linked_identity.__doc__ = user_service_get_linked_identity.__doc__
        self.get_linked_identity_sync = partial(user_service_get_linked_identity_sync, config)
        self.get_linked_identity_sync.__doc__ = user_service_get_linked_identity_sync.__doc__
        self.delete_linked_identity = partial(user_service_delete_linked_identity, config)
        self.delete_linked_identity.__doc__ = user_service_delete_linked_identity.__doc__
        self.delete_linked_identity_sync = partial(user_service_delete_linked_identity_sync, config)
        self.delete_linked_identity_sync.__doc__ = user_service_delete_linked_identity_sync.__doc__
        self.list_user_notifications = partial(user_service_list_user_notifications, config)
        self.list_user_notifications.__doc__ = user_service_list_user_notifications.__doc__
        self.list_user_notifications_sync = partial(
            user_service_list_user_notifications_sync, config
        )
        self.list_user_notifications_sync.__doc__ = (
            user_service_list_user_notifications_sync.__doc__
        )
        self.delete_user_notification = partial(user_service_delete_user_notification, config)
        self.delete_user_notification.__doc__ = user_service_delete_user_notification.__doc__
        self.delete_user_notification_sync = partial(
            user_service_delete_user_notification_sync, config
        )
        self.delete_user_notification_sync.__doc__ = (
            user_service_delete_user_notification_sync.__doc__
        )
        self.update_user_notification = partial(user_service_update_user_notification, config)
        self.update_user_notification.__doc__ = user_service_update_user_notification.__doc__
        self.update_user_notification_sync = partial(
            user_service_update_user_notification_sync, config
        )
        self.update_user_notification_sync.__doc__ = (
            user_service_update_user_notification_sync.__doc__
        )
        self.list_personal_access_tokens = partial(user_service_list_personal_access_tokens, config)
        self.list_personal_access_tokens.__doc__ = user_service_list_personal_access_tokens.__doc__
        self.list_personal_access_tokens_sync = partial(
            user_service_list_personal_access_tokens_sync, config
        )
        self.list_personal_access_tokens_sync.__doc__ = (
            user_service_list_personal_access_tokens_sync.__doc__
        )
        self.create_personal_access_token = partial(
            user_service_create_personal_access_token, config
        )
        self.create_personal_access_token.__doc__ = (
            user_service_create_personal_access_token.__doc__
        )
        self.create_personal_access_token_sync = partial(
            user_service_create_personal_access_token_sync, config
        )
        self.create_personal_access_token_sync.__doc__ = (
            user_service_create_personal_access_token_sync.__doc__
        )
        self.delete_personal_access_token = partial(
            user_service_delete_personal_access_token, config
        )
        self.delete_personal_access_token.__doc__ = (
            user_service_delete_personal_access_token.__doc__
        )
        self.delete_personal_access_token_sync = partial(
            user_service_delete_personal_access_token_sync, config
        )
        self.delete_personal_access_token_sync.__doc__ = (
            user_service_delete_personal_access_token_sync.__doc__
        )
        self.list_user_settings = partial(user_service_list_user_settings, config)
        self.list_user_settings.__doc__ = user_service_list_user_settings.__doc__
        self.list_user_settings_sync = partial(user_service_list_user_settings_sync, config)
        self.list_user_settings_sync.__doc__ = user_service_list_user_settings_sync.__doc__
        self.get_user_setting = partial(user_service_get_user_setting, config)
        self.get_user_setting.__doc__ = user_service_get_user_setting.__doc__
        self.get_user_setting_sync = partial(user_service_get_user_setting_sync, config)
        self.get_user_setting_sync.__doc__ = user_service_get_user_setting_sync.__doc__
        self.update_user_setting = partial(user_service_update_user_setting, config)
        self.update_user_setting.__doc__ = user_service_update_user_setting.__doc__
        self.update_user_setting_sync = partial(user_service_update_user_setting_sync, config)
        self.update_user_setting_sync.__doc__ = user_service_update_user_setting_sync.__doc__
        self.list_memo_views = partial(user_service_list_memo_views, config)
        self.list_memo_views.__doc__ = user_service_list_memo_views.__doc__
        self.list_memo_views_sync = partial(user_service_list_memo_views_sync, config)
        self.list_memo_views_sync.__doc__ = user_service_list_memo_views_sync.__doc__
        self.create_memo_view = partial(user_service_create_memo_view, config)
        self.create_memo_view.__doc__ = user_service_create_memo_view.__doc__
        self.create_memo_view_sync = partial(user_service_create_memo_view_sync, config)
        self.create_memo_view_sync.__doc__ = user_service_create_memo_view_sync.__doc__
        self.get_memo_view = partial(user_service_get_memo_view, config)
        self.get_memo_view.__doc__ = user_service_get_memo_view.__doc__
        self.get_memo_view_sync = partial(user_service_get_memo_view_sync, config)
        self.get_memo_view_sync.__doc__ = user_service_get_memo_view_sync.__doc__
        self.delete_memo_view = partial(user_service_delete_memo_view, config)
        self.delete_memo_view.__doc__ = user_service_delete_memo_view.__doc__
        self.delete_memo_view_sync = partial(user_service_delete_memo_view_sync, config)
        self.delete_memo_view_sync.__doc__ = user_service_delete_memo_view_sync.__doc__
        self.update_memo_view = partial(user_service_update_memo_view, config)
        self.update_memo_view.__doc__ = user_service_update_memo_view.__doc__
        self.update_memo_view_sync = partial(user_service_update_memo_view_sync, config)
        self.update_memo_view_sync.__doc__ = user_service_update_memo_view_sync.__doc__
        self.list_user_webhooks = partial(user_service_list_user_webhooks, config)
        self.list_user_webhooks.__doc__ = user_service_list_user_webhooks.__doc__
        self.list_user_webhooks_sync = partial(user_service_list_user_webhooks_sync, config)
        self.list_user_webhooks_sync.__doc__ = user_service_list_user_webhooks_sync.__doc__
        self.create_user_webhook = partial(user_service_create_user_webhook, config)
        self.create_user_webhook.__doc__ = user_service_create_user_webhook.__doc__
        self.create_user_webhook_sync = partial(user_service_create_user_webhook_sync, config)
        self.create_user_webhook_sync.__doc__ = user_service_create_user_webhook_sync.__doc__
        self.delete_user_webhook = partial(user_service_delete_user_webhook, config)
        self.delete_user_webhook.__doc__ = user_service_delete_user_webhook.__doc__
        self.delete_user_webhook_sync = partial(user_service_delete_user_webhook_sync, config)
        self.delete_user_webhook_sync.__doc__ = user_service_delete_user_webhook_sync.__doc__
        self.update_user_webhook = partial(user_service_update_user_webhook, config)
        self.update_user_webhook.__doc__ = user_service_update_user_webhook.__doc__
        self.update_user_webhook_sync = partial(user_service_update_user_webhook_sync, config)
        self.update_user_webhook_sync.__doc__ = user_service_update_user_webhook_sync.__doc__
        self.get_user_webhook_signing_secret = partial(
            user_service_get_user_webhook_signing_secret, config
        )
        self.get_user_webhook_signing_secret.__doc__ = (
            user_service_get_user_webhook_signing_secret.__doc__
        )
        self.get_user_webhook_signing_secret_sync = partial(
            user_service_get_user_webhook_signing_secret_sync, config
        )
        self.get_user_webhook_signing_secret_sync.__doc__ = (
            user_service_get_user_webhook_signing_secret_sync.__doc__
        )
        self.export_memos = partial(user_service_export_memos, config)
        self.export_memos.__doc__ = user_service_export_memos.__doc__
        self.export_memos_sync = partial(user_service_export_memos_sync, config)
        self.export_memos_sync.__doc__ = user_service_export_memos_sync.__doc__
        self.get_user_stats = partial(user_service_get_user_stats, config)
        self.get_user_stats.__doc__ = user_service_get_user_stats.__doc__
        self.get_user_stats_sync = partial(user_service_get_user_stats_sync, config)
        self.get_user_stats_sync.__doc__ = user_service_get_user_stats_sync.__doc__
        self.import_memos = partial(user_service_import_memos, config)
        self.import_memos.__doc__ = user_service_import_memos.__doc__
        self.import_memos_sync = partial(user_service_import_memos_sync, config)
        self.import_memos_sync.__doc__ = user_service_import_memos_sync.__doc__
        self.batch_get_users = partial(user_service_batch_get_users, config)
        self.batch_get_users.__doc__ = user_service_batch_get_users.__doc__
        self.batch_get_users_sync = partial(user_service_batch_get_users_sync, config)
        self.batch_get_users_sync.__doc__ = user_service_batch_get_users_sync.__doc__
        self.list_all_user_stats = partial(user_service_list_all_user_stats, config)
        self.list_all_user_stats.__doc__ = user_service_list_all_user_stats.__doc__
        self.list_all_user_stats_sync = partial(user_service_list_all_user_stats_sync, config)
        self.list_all_user_stats_sync.__doc__ = user_service_list_all_user_stats_sync.__doc__
